### ISSUE TITLE
English Screenshots as Reference - Website - Aug 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#100]
### 1. FAQ - Info Source
![Screen Shot 2020-07-27 at 1 10 26 PM](https://user-images.githubusercontent.com/48343061/88587392-bdc0c900-d00a-11ea-877a-8aae49db7479.png)

### 2. FAQ - To be listed 
**_Note:_** The last line on the paragraph below should not have been hyperlinked. The hyperlink is only for "http://www.bc211.ca". 

![Screen Shot 2020-07-27 at 1 10 40 PM](https://user-images.githubusercontent.com/48343061/88587446-d204c600-d00a-11ea-8e1a-bc1035a1f8cf.png)

### 3. FAQ - Website Version
![Screen Shot 2020-07-27 at 1 10 47 PM](https://user-images.githubusercontent.com/48343061/88587510-e3e66900-d00a-11ea-97b3-2ecaf322b7cb.png)

### 4. FAQ - Checkmarked & Bookmarked Topics
![Screen Shot 2020-07-27 at 1 10 56 PM](https://user-images.githubusercontent.com/48343061/88587581-ffea0a80-d00a-11ea-9696-47be1427abd2.png)

### 5. Home - Available in your language
![Screen Shot 2020-08-06 at 11 23 09 AM](https://user-images.githubusercontent.com/47794846/89567860-3e37b480-d7d7-11ea-8b8c-b5e5f94eabf8.png)

**Comment by rasmus-storjohann-PG** [comment]
This story was used to help translators, no work to do on them, closing.
