### ISSUE TITLE
Chinese Simplified QA: App Strings - Aug 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#102]
### 1. Content Alert
![Screen Shot 2020-07-27 at 4 37 07 PM](https://user-images.githubusercontent.com/48343061/88604499-60d60a80-d02c-11ea-85de-deb73842661c.png)
 
### 2. Search - Street
![Screen Shot 2020-08-06 at 9 55 10 AM](https://user-images.githubusercontent.com/48343061/89559773-fca10c80-d7ca-11ea-8a07-32c78e38f130.png)

### 3. Search - Near
![Screen Shot 2020-07-27 at 5 59 43 PM](https://user-images.githubusercontent.com/48343061/88607022-01c7c400-d033-11ea-89fb-f5c7cd889b42.png)
 
### 4. Feedback - Suggest an update 
<img width="365" alt="Screen Shot 2020-08-03 at 9 56 30 PM" src="https://user-images.githubusercontent.com/48343061/89254572-4e337680-d5d4-11ea-9c7d-b980eb79b7cc.png">

### 5. Feedback - Discard Changes 
![Screen Shot 2020-07-27 at 5 28 33 PM](https://user-images.githubusercontent.com/48343061/88605416-b0b5d100-d02e-11ea-9293-819f1044306d.png)

### 6. Feedback - System Explainer (ALL)
<img width="367" alt="Screen Shot 2020-08-03 at 9 56 57 PM" src="https://user-images.githubusercontent.com/48343061/89254587-58557500-d5d4-11ea-9332-f098a2435edc.png">

### 7. Feedback - Thank You
![Screen Shot 2020-07-27 at 6 00 30 PM](https://user-images.githubusercontent.com/48343061/88607064-1efc9280-d033-11ea-97f9-b16abc06b4ee.png)
 
### 8. Feedback - Other Suggestions
![Screen Shot 2020-07-27 at 6 01 29 PM](https://user-images.githubusercontent.com/48343061/88607116-3e93bb00-d033-11ea-9d85-6831e3b4e1a0.png)
 
### 9. Feedback - Service No Longer Exists
![Screen Shot 2020-07-27 at 6 02 15 PM](https://user-images.githubusercontent.com/48343061/88607164-5f5c1080-d033-11ea-8b1a-1e27bfbe8365.png)
 
### 10. Feedback - Contact Info (ALL) 
![Screen Shot 2020-07-27 at 6 12 38 PM](https://user-images.githubusercontent.com/48343061/88607723-c5956300-d034-11ea-8fa4-5caca0272b6a.png)

### 11. Feedback - Form
![Screen Shot 2020-07-27 at 6 13 14 PM](https://user-images.githubusercontent.com/48343061/88607797-f83f5b80-d034-11ea-846c-949aa1b0adf8.png)

### 12. Open External Link
![Screen Shot 2020-07-27 at 5 31 11 PM](https://user-images.githubusercontent.com/48343061/88605554-1b670c80-d02f-11ea-9497-12f90c0f5724.png)

### 13. Onboarding 2
![Screen Shot 2020-07-27 at 5 23 48 PM](https://user-images.githubusercontent.com/48343061/88605170-076edb00-d02e-11ea-8165-05ee23db0c13.png)

**Comment by cjburnaby** [comment]
1. Content Alert: PASS 
2. Search - Street:  
English Texts: Street:
Suggested Texts: To change “:” to dash “——“, please copy the previous one or the one after this line to make them same.
Rationale: Punctuation marks consistency.

3. Search - Near: PASS 
4. Feedback - Suggest an update: PASS 
5. Feedback - Discard Changes: PASS 
6. Feedback - System Explainer: PASS 
7. Feedback - Thank You: PASS 
8. Feedback - Other Suggestions: PASS 
9. Feedback - Service No Longer Exists: PASS 
10. Feedback - Contact Info: PASS  
11. Feedback - Form: PASS 
12. Open External Link: PASS 
13. Revised Onboarding 2: PASS

**Comment by jparlina** [comment]
Moved the following to [Frontend issue #1245](https://app.zenhub.com/workspaces/arrival-advisor-5977956f40fbe90e67bb4155/issues/pg-irc/pathways-frontend/1245)
2. Search - Street:  
English Texts: Street:
Suggested Texts: To change “:” to dash “——“, please copy the previous one or the one after this line to make them same.
Rationale: Punctuation marks consistency.

**Comment by jparlina** [comment]
Fixed on Staging 1.43.0
![Screen Shot 2020-08-17 at 10 27 31 AM](https://user-images.githubusercontent.com/48343061/90425484-a3f82c00-e074-11ea-924a-123d1853f9ab.png)
