### ISSUE TITLE
Chinese Traditional QA: App Strings - Aug 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#103]
### 1. Content Alert
![Screen Shot 2020-08-06 at 11 51 58 AM](https://user-images.githubusercontent.com/48343061/89570604-4abe0c00-d7db-11ea-9859-627dec4263c6.png)

### 2. Search - Street
<img width="358" alt="Screen Shot 2020-07-28 at 11 51 26 AM" src="https://user-images.githubusercontent.com/48343061/88708840-1d7da980-d0c9-11ea-93c0-ab0ed6d26847.png">
 
### 3. Search - Near
<img width="357" alt="Screen Shot 2020-07-28 at 11 46 50 AM" src="https://user-images.githubusercontent.com/48343061/88708264-3fc2f780-d0c8-11ea-83af-4b386a137101.png">
 
### 4. Feedback - Suggest an update
<img width="360" alt="Screen Shot 2020-08-03 at 9 59 34 PM" src="https://user-images.githubusercontent.com/48343061/89254729-baae7580-d5d4-11ea-89df-23822a94a4db.png">

### 5. Feedback - Discard Changes 
![Screen Shot 2020-07-28 at 11 28 42 AM](https://user-images.githubusercontent.com/48343061/88706358-9f6bd380-d0c5-11ea-8465-f650ad282a0d.png)

### 6. Feedback - System Explainer (ALL)
<img width="357" alt="Screen Shot 2020-08-03 at 9 59 53 PM" src="https://user-images.githubusercontent.com/48343061/89254744-c26e1a00-d5d4-11ea-895a-3c637c908574.png">

### 7. Feedback - Thank You
<img width="359" alt="Screen Shot 2020-07-28 at 11 33 55 AM" src="https://user-images.githubusercontent.com/48343061/88706866-4cdee700-d0c6-11ea-81c3-256968178e2b.png">
 
### 8. Feedback - Other Suggestions
<img width="365" alt="Screen Shot 2020-07-28 at 11 39 45 AM" src="https://user-images.githubusercontent.com/48343061/88707457-1ce41380-d0c7-11ea-9acb-3593d8c35df8.png">

### 9. Feedback - Service No Longer Exists
<img width="367" alt="Screen Shot 2020-07-28 at 11 37 31 AM" src="https://user-images.githubusercontent.com/48343061/88707219-cf67a680-d0c6-11ea-8f20-bcacf2135373.png">
 
### 10. Feedback - Contact Info (ALL) 
<img width="356" alt="Screen Shot 2020-07-28 at 11 40 58 AM" src="https://user-images.githubusercontent.com/48343061/88707551-3edd9600-d0c7-11ea-8812-0f83f294e208.png">

### 11. Feedback - Form
<img width="368" alt="Screen Shot 2020-07-28 at 11 41 34 AM" src="https://user-images.githubusercontent.com/48343061/88707665-6d5b7100-d0c7-11ea-81b0-06b2bcc206e2.png">

### 12. Open External Link
![Screen Shot 2020-07-28 at 10 48 22 AM](https://user-images.githubusercontent.com/48343061/88702431-29b13900-d0c0-11ea-8b1e-c103afbeb732.png)

### 13. Onboarding 2
![Screen Shot 2020-07-28 at 10 47 26 AM](https://user-images.githubusercontent.com/48343061/88702128-ccb58300-d0bf-11ea-8d9f-7962a266f027.png)

**Comment by ian-lin-PG** [comment]
1. Content Alert: PASS
2. Search - Street: PASS
3. Search - Near: PASS
4. Feedback - Suggest an update: PASS
5. Feedback - Discard Changes: PASS
6. Feedback - System Explainer: PASS
7. Feedback - Thank You: PASS
8. Feedback - Other Suggestions: PASS
9. Feedback - Service No Longer Exists: PASS
10. Feedback - Contact Info: PASS
11. Feedback - Form: PASS
12. Open External Link: PASS
13. Revised Onboarding 2: PASS
