### ISSUE TITLE
Punjabi QA - February 2021

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/arrival-advisor-qa#109]
### 1. Release Notes
![Screenshot_20210205-095120_Google Play Store.jpg](https://images.zenhubusercontent.com/5c6c8cff9d62b128eab447ff/96b1aff6-ec3e-45c0-ad2e-0bfafc3c5961)

### 2. Service Detail Screen
![Simulator Screen Shot - iPhone X - 2021-02-05 at 11 14 00](https://user-images.githubusercontent.com/47794846/107078757-a1fd6300-67a3-11eb-8a45-11c87feb4d84.png)

### 3. Service Review Screen
![Simulator Screen Shot - iPhone X - 2021-02-05 at 11 14 10](https://user-images.githubusercontent.com/47794846/107078777-aa559e00-67a3-11eb-9ad0-f8116e67b42a.png)

### 4. Service Bookmarks & Prompt Button
![Simulator Screen Shot - iPhone X - 2021-02-05 at 11 14 18](https://user-images.githubusercontent.com/47794846/107078803-b6d9f680-67a3-11eb-9183-446cff213555.png)

**Comment by aalam** [comment]
Release Notes - PASS
Service Detail Screen - PASS
Service Review Screen - PASS
Service Bookmark & Prompt Button - PASS
