### ISSUE TITLE
Tagalog QA - February 2021

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/arrival-advisor-qa#110]
### 1. Release Notes
![Screenshot_20210205-095218_Google Play Store.jpg](https://images.zenhubusercontent.com/5c6c8cff9d62b128eab447ff/11ff095c-b2d1-4956-bb60-136604f3c0b3)

### 2. Service Detail Screen
![Simulator Screen Shot - iPhone X - 2021-02-05 at 11 32 13](https://user-images.githubusercontent.com/47794846/107080589-5dbf9200-67a6-11eb-9c4b-613788e9820b.png)

### 3. Service Review Screen
![Simulator Screen Shot - iPhone X - 2021-02-05 at 11 32 22](https://user-images.githubusercontent.com/47794846/107080631-69ab5400-67a6-11eb-995d-cc6e49be9abe.png)

### 4. Service Bookmarks & Prompt Button
![Simulator Screen Shot - iPhone X - 2021-02-05 at 11 32 25](https://user-images.githubusercontent.com/47794846/107080655-72038f00-67a6-11eb-97c7-f23d52b62013.png)

**Comment by sheen-indonela** [comment]
1. Screen Name: Release Note
2. English Text: What's New
3. Current Text: Ano'ng bago
4. Suggested Text: Ano ang bago
5. Rationale: formality and other meaning (anong can also mean which)

**Comment by sheen-indonela** [comment]
2. Screen Name: Service Detail Screen-Pass

**Comment by sheen-indonela** [comment]
3. Screen Name: Service Review Screen- Pass
4. Screen Nama: Service Bookmarks & Prompt Button- Pass

**Comment by jparlina** [comment]
@tomy-pg Please fix Release Notes (see suggested edit above), thanks!

**Comment by tomy-pg** [comment]
`What's new` translation is out of our control. Google Play does this translation.
