### ISSUE TITLE
Korean QA - February 2021

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/arrival-advisor-qa#111]
### 1. Release Notes
![Screenshot_20210205-095318_Google Play Store.jpg](https://images.zenhubusercontent.com/5c6c8cff9d62b128eab447ff/60b5a0a2-ee9a-432f-a3cd-866db71d8d1c)

### 2. Service Detail Screen
![Simulator Screen Shot - iPhone X - 2021-02-05 at 11 18 10](https://user-images.githubusercontent.com/47794846/107079105-39fb4c80-67a4-11eb-9b45-d3226dc4894b.png)

### 3. Service Review Screen
![Simulator Screen Shot - iPhone X - 2021-02-05 at 11 18 16](https://user-images.githubusercontent.com/47794846/107079130-4089c400-67a4-11eb-9d81-673df1b4f9aa.png)

### 4. Service Bookmarks & Prompt Button
![Simulator Screen Shot - iPhone X - 2021-02-05 at 11 18 26](https://user-images.githubusercontent.com/47794846/107079152-48e1ff00-67a4-11eb-8d44-abf1dd3c35fd.png)

**Comment by harjul0618** [comment]
1. Release Notes: PASS
2. Service Detail Screen: PASS
3. Service Review Screen: PASS
4. Service Bookmark & Prompt Button: PASS
