### ISSUE TITLE
Simplified Chinese QA - February 2021

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/arrival-advisor-qa#112]
### 1. Release Notes
![Screenshot_20210205-095511_Google Play Store.jpg](https://images.zenhubusercontent.com/5c6c8cff9d62b128eab447ff/819f4bb0-8276-4212-a28b-ca0df7d03564)

### 2. Service Detail Screen
![Simulator Screen Shot - iPhone X - 2021-02-05 at 11 38 17](https://user-images.githubusercontent.com/47794846/107081063-f81fd580-67a6-11eb-93db-aa8fccc53ae1.png)

### 3. Service Review Screen
![Simulator Screen Shot - iPhone X - 2021-02-05 at 11 38 23](https://user-images.githubusercontent.com/47794846/107081080-fe15b680-67a6-11eb-81ae-b858af55cb4b.png)

### 4. Service Bookmarks & Prompt Button
![Simulator Screen Shot - iPhone X - 2021-02-05 at 11 38 26](https://user-images.githubusercontent.com/47794846/107081089-040b9780-67a7-11eb-9409-5e9b5016d5e9.png)

**Comment by cjburnaby** [comment]
1. Release Notes: PASS
2. Service Detail Screen: PASS
3. Service Review Screen: PASS
4. Service Bookmark & Prompt Button: PASS
