### ISSUE TITLE
Traditional Chinese QA - February 2021

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/arrival-advisor-qa#113]
### 1. Release Notes
![Screenshot_20210205-095618_Google Play Store.jpg](https://images.zenhubusercontent.com/5c6c8cff9d62b128eab447ff/76802fba-0b5f-4893-a585-bc2cfc5b4631)

### 2. Service Detail Screen
![Simulator Screen Shot - iPhone X - 2021-02-05 at 11 41 34](https://user-images.githubusercontent.com/47794846/107081347-649ad480-67a7-11eb-94bb-bb111e665da1.png)

### 3. Service Review Screen
![Simulator Screen Shot - iPhone X - 2021-02-05 at 11 41 38](https://user-images.githubusercontent.com/47794846/107081372-6f556980-67a7-11eb-9ba2-aad452d76b1c.png)

### 4. Service Bookmarks & Prompt Button
![Simulator Screen Shot - iPhone X - 2021-02-05 at 11 41 40](https://user-images.githubusercontent.com/47794846/107081398-77ada480-67a7-11eb-842a-58ff778d9863.png)

**Comment by ian-lin-PG** [comment]
1. Release Notes: PASS
2. Service Detail Screen: PASS
3. Service Review Screen: PASS
4. Service Bookmark & Prompt Button: PASS
