### ISSUE TITLE
'Back' button has identical translation as 'Next'

### ISSUE THREAD

**Issue by aalam** [pg-irc/arrival-advisor-qa#13]
**Describe the bug**
on initial screen (or after delete all user data), once application started with Punjabi language, 'Back' button on second screen 'Find helpful services nearby' has wrong translation as 'Next'

**App version**
Staging (1.0.24) 

**To Reproduce**
1. Go to initial screen 'Get trusted information' while language is Panjabi
2. Click on 'Next'
3. check Left bottom button 'Back'
4. See Right Bottom button 'Next'

**Expected behavior**
Back' Button should be 'ਪਿੱਛੇ'

**Observed behavior**
'Back' Button has same translation as Next button

**Screenshots**
Screenshot attached. Please check Both buttons

**Linguistic issues**
- Current text: 'ਅੱਗੇ'
- Suggested text:'ਪਿੱਛੇ'
- Reason:  wrong translation

**Smartphone (please complete the following information):**
 - Device: Samsung Note 9 /iPhone
 - OS: Android 9 iOS 12.3.1

**Additional context**
![Screenshot_20190708-222719_Arrival Advisor](https://user-images.githubusercontent.com/600806/61172389-8b941480-a538-11e9-9822-91b8adce499c.jpg)

**Comment by ArtiBPG** [comment]
buttons removed so it should not be an issue anymore.
