### ISSUE TITLE
Korean_Not translated

### ISSUE THREAD

**Issue by rankanglee** [pg-irc/arrival-advisor-qa#17]
**Describe the bug**
Some texts are not translated.
*Please check if there's translated text already, if not, please let me know so I can provide the translation.

**App version**
1.0.24

**To Reproduce**
Landing page (Start settling in BC screen appears)

**Screenshots**
"https://screencast.com/t/bXlWMluL4H
https://screencast.com/t/tPBn8iKI
https://screencast.com/t/jsCkFC2b5S"

**Smartphone (please complete the following information):**
- Device: iPhone7
- OS: iOS 12.3.1

**Comment by ArtiBPG** [comment]
En was changed and will be sent out for QA soon, closing
