### ISSUE TITLE
French QA: "Delete All User Data" 

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#26]
Confirm the following texts are correctly translated into French (see screenshots in English and French):
- [ ] Do you want to delete all user data from this phone? This includes which answers are chosen in the questionnaire and which topics are bookmarked.
- [ ] Delete all user data
- [ ] CANCEL

![IMG_2457](https://user-images.githubusercontent.com/48343061/65353345-c1412380-dba1-11e9-8341-00b25bc7fa90.jpg)

![IMG_2458](https://user-images.githubusercontent.com/48343061/65353382-d322c680-dba1-11e9-947c-a507fbf1485a.jpg)

**Comment by BenoitGignac** [comment]
PASS
