### ISSUE TITLE
Punjabi QA: "Delete All Users Data"

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#29]
Confirm the following texts are correctly translated into Punjabi (see screenshots in English and Punjabi below):

- [ ] Do you want to delete all user data from this phone? This includes which answers are chosen in the questionnaire and which topics are bookmarked.
- [ ] Delete all user data
- [ ] CANCEL

Also confirm whether
- [ ] the line breaks make sense

If not, make your suggestions in the comment.

![IMG_2457](https://user-images.githubusercontent.com/48343061/65353933-2b0dfd00-dba3-11e9-9521-4f4f7af1df4b.jpg)

![IMG_2460](https://user-images.githubusercontent.com/48343061/65353939-2fd2b100-dba3-11e9-82ac-cf64b6910d2c.jpg)

**Comment by aalam** [comment]
Passed.
