### ISSUE TITLE
Tagalog QA: "Delete All Users Data"

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#30]
Confirm the following texts are correctly translated into Tagalog (see screenshots in English and Tagalog below):

- [ ] Do you want to delete all user data from this phone? This includes which answers are chosen in the questionnaire and which topics are bookmarked.
- [ ] Delete all user data
- [ ] CANCEL

Also confirm whether
- [ ] the line breaks make sense

If not, make your suggestions in the comment.

![IMG_2457](https://user-images.githubusercontent.com/48343061/65354066-76c0a680-dba3-11e9-8b7e-4f6100b1df50.jpg)

![IMG_2461](https://user-images.githubusercontent.com/48343061/65354074-7aecc400-dba3-11e9-8153-02dca2352819.jpg)

**Comment by teachermavel** [comment]
Pass
