### ISSUE TITLE
Language QA: English Screens as Reference - Mar 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#31]
### 1. My Bookmarks
<img width="378" alt="1  EN_MyBookmarks" src="https://user-images.githubusercontent.com/48343061/76674107-fcc51500-6568-11ea-8388-c2e644e90f03.png">

### 2. Questionnaire - New Topics Recommended
<img width="374" alt="2  EN_Questionnaire_NewTopics" src="https://user-images.githubusercontent.com/48343061/76674114-08184080-6569-11ea-9707-41852388d560.png">

### 3. Help
<img width="382" alt="3  EN_Help_MultilingualHealth" src="https://user-images.githubusercontent.com/48343061/76674116-09496d80-6569-11ea-9d16-c8fea7a473d4.png">

### 4. Search Input
<img width="379" alt="4  EN_SearchInput" src="https://user-images.githubusercontent.com/48343061/76674117-09496d80-6569-11ea-8844-2ed78fdf1ee2.png">

### 5a. Search Error - Invalid Location
<img width="374" alt="5a  EN_SearchError_InvalidLocation" src="https://user-images.githubusercontent.com/48343061/76674118-0a7a9a80-6569-11ea-964d-ca1240d33ec4.png">

### 5b. Search Error - No Results
<img width="377" alt="5b  EN_SearchError_NoResults" src="https://user-images.githubusercontent.com/48343061/76674119-0a7a9a80-6569-11ea-9310-0bcc673e37a0.png">

### 6. Search Results - Show More
![7  EN_SearchResults_ShowMore](https://user-images.githubusercontent.com/48343061/76674121-0b133100-6569-11ea-8337-7128a1435601.png)

### 7a. Service Detail 1
![8a  EN_ServiceDetail1](https://user-images.githubusercontent.com/48343061/76674122-0babc780-6569-11ea-9aad-d5765c58902a.png)

### 7b. Service Detail 2
![8b  EN_ServiceDetail2](https://user-images.githubusercontent.com/48343061/76674124-0c445e00-6569-11ea-8801-c05603b61388.png)

**Comment by rasmus-storjohann-PG** [comment]
This story was used to help translators, no work to do on them, closing.
