### ISSUE TITLE
French QA - Mar 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#33]
### 1. My Bookmarks
![Screen Shot 2020-03-13 at 9 37 48 PM](https://user-images.githubusercontent.com/48343061/76675047-e623bb80-6572-11ea-911c-c576f71d7823.png)

### 2. Questionnaire - New Topics Recommended
![Screen Shot 2020-03-13 at 9 38 09 PM](https://user-images.githubusercontent.com/48343061/76675051-f471d780-6572-11ea-90b4-f9fd08028ad9.png)

### 3. Help
![Screen Shot 2020-03-13 at 9 38 36 PM](https://user-images.githubusercontent.com/48343061/76675058-0b182e80-6573-11ea-8f46-2297feac1bd3.png)

### 4. Search Input
![Screen Shot 2020-03-13 at 9 39 18 PM](https://user-images.githubusercontent.com/48343061/76675065-1c613b00-6573-11ea-8c62-67b403e917ed.png)

### 5a. Search Error - Invalid Location
![Screen Shot 2020-03-13 at 9 44 09 PM](https://user-images.githubusercontent.com/48343061/76675162-d8bb0100-6573-11ea-9886-215ba4ef391a.png)

### 5b. Search Error - No Results
![Screen Shot 2020-03-13 at 9 40 16 PM](https://user-images.githubusercontent.com/48343061/76675155-bde88c80-6573-11ea-80bd-0059167e7bf7.png)

### 6. Search Results - Show More
![Screen Shot 2020-03-13 at 9 45 39 PM](https://user-images.githubusercontent.com/48343061/76675184-086a0900-6574-11ea-9ccc-130eb7b2637e.png)

### 7a. Service Detail 1
![Screen Shot 2020-03-13 at 9 47 35 PM](https://user-images.githubusercontent.com/48343061/76675221-554ddf80-6574-11ea-93dd-792975237715.png)

### 7b. Service Detail 2
![Screen Shot 2020-03-13 at 9 46 24 PM](https://user-images.githubusercontent.com/48343061/76675204-35b6b700-6574-11ea-88de-53d1335b4b59.png)

**Comment by ludivinegh** [comment]
Screen name: 4. Search Input
Issue (not linguistic): I am not including the current and suggested target strings, as this is a layout issue. The beginning of the string is truncated in French here: https://i.imgur.com/f3mPC0C.png. It currently only reads "only available in English". I was able to review the translation on the screen Search Error - Invalid Location and it is correct.

**_Jean's review (03/20/2020)_**: This is not an issue. Confirmed with Tony and Ian that this screenshot was taken after scrolling down the screen, hence the first line looks truncated here.

**Comment by ludivinegh** [comment]
Screen name: 4. Search Input
Issue (not linguistic): The string "Need suggestions? Try:" was not translated. See here: https://i.imgur.com/dQK0YI0.png.

_**Jean's review (03/20/2020)**_ Known issue. Will upload additional translations to weblate for next staging release.

**Comment by ludivinegh** [comment]
Screen name: 7a. Service Detail 1
English Texts: Provided by:
Current Texts: Fournisseur:
Suggested Texts: Fournisseur :
(Please make sure to insert a _non-breaking space_ before the colon.)

**Comment by ludivinegh** [comment]
Screen name: 7b. Service Detail 2
English Texts: Address: / Website: / Last verified:
Current Texts: Adresse: / Site Web: / Dernière vérification:
Suggested Texts: Adresse : / Site Web : / Dernière vérification :
(Please make sure to insert a _non-breaking space_ before the colon.)

**Comment by ludivinegh** [comment]
1. My Bookmarks: PASS

2. Questionnaire - New Topics Recommended: PASS

3. Help: PASS

5a. Search Error - Invalid Location: PASS

5b. Search Error - No Results: PASS

6. Search Results - Show More: PASS

**Comment by jparlina** [comment]
Moved to GitHub frontend [ issue #1073](https://app.zenhub.com/workspaces/arrival-advisor-5977956f40fbe90e67bb4155/issues/pg-irc/pathways-frontend/1073) to address missing a non-breaking space before colon on service detail page (screens 7a and 7b)
