### ISSUE TITLE
Chinese Simplified QA - Mar 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#36]
### 1. My Bookmarks
![Screenshot_20200317-170510](https://user-images.githubusercontent.com/52009863/76912781-50d63f00-6872-11ea-9609-2bcee61cf6e6.jpg)

### 2. Questionnaire - New Topics Recommended
![Screenshot_20200317-170530](https://user-images.githubusercontent.com/52009863/76912773-4ae05e00-6872-11ea-98de-aaa832c52123.jpg)

### 3. Help
![Screenshot_20200317-170542](https://user-images.githubusercontent.com/52009863/76912812-6a778680-6872-11ea-98c2-cba46bc1a6c6.jpg)

### 4. Search Input
![Screenshot_20200317-170557](https://user-images.githubusercontent.com/52009863/76912734-25ebeb00-6872-11ea-8fc1-e41faa0351fe.jpg)

### 5a. Search Error - Invalid Location
![Screenshot_20200317-170615](https://user-images.githubusercontent.com/52009863/76912733-22f0fa80-6872-11ea-80f9-135dcb6a9ffc.jpg)

### 5b. Search Error - No Results
![Screenshot_20200317-170640](https://user-images.githubusercontent.com/52009863/76912716-1371b180-6872-11ea-902a-269cf2376a1c.jpg)
### 6. Search Results - Show More
![Screenshot_20200317-170658](https://user-images.githubusercontent.com/52009863/76912710-0d7bd080-6872-11ea-89c1-c4a93b3cd610.jpg)

### 7a. Service Detail 1
![Screenshot_20200317-170707](https://user-images.githubusercontent.com/52009863/76912702-081e8600-6872-11ea-9283-ed877d1358b1.jpg)
### 7b. Service Detail 2
![Screenshot_20200317-170712](https://user-images.githubusercontent.com/52009863/76912696-05239580-6872-11ea-9285-d703956d7b9d.jpg)

**Comment by ian-lin-PG** [comment]
Screen Name: 4. Search Input
English Text: `call bc211`
Current Text: `请电话联系BC211`
Suggested Text: `电话联系BC211`
Rationale: the translation for please,`请`, showed up twice which makes it more awkward.
![Screenshot_20200317-164942](https://user-images.githubusercontent.com/52009863/76912110-ed4b1200-686f-11ea-9ba1-3d59bbc974a1.jpg)

**Comment by ian-lin-PG** [comment]
Screen Name: 1. My Bookmarks
English Text: My Bookarmarks
Current Text: 我的网页书签
Suggested Text: 我的书签
Rationale: The difference is between `My Web Bookmarks` and `My Bookmarks`.
![Screenshot_20200317-170510](https://user-images.githubusercontent.com/52009863/76990211-d60a3400-6904-11ea-9ad3-d3d8405e4187.jpg)

**Comment by ian-lin-PG** [comment]
1. My Bookmarks: PASS (see above)
2. Questionnaire - New Topics Recommended: PASS
3. Help: PASS
4. Search Input: FAIL (see above)
5a. Search Error - Invalid Location: PASS
5b. Search Error - No Results: PASS
6. Search Results - Show More: PASS
7a. Service Detail 1: PASS
7b. Service Detail 2: PASS

**Comment by jparlina** [comment]
Created issue on GitHub [frontend issue #1060](https://app.zenhub.com/workspaces/arrival-advisor-5977956f40fbe90e67bb4155/issues/pg-irc/pathways-frontend/1060).
