### ISSUE TITLE
Chinese Traditional QA - Mar 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#37]
### 1. My Bookmarks
![Screenshot_20200318-094443](https://user-images.githubusercontent.com/52009863/76985553-9ee45480-68fd-11ea-9b11-953438b06ec8.jpg)

### 2. Questionnaire - New Topics Recommended
![Screenshot_20200318-094503](https://user-images.githubusercontent.com/52009863/76985563-a1df4500-68fd-11ea-8291-2f44cdc12bbc.jpg)

### 3. Help
![Screenshot_20200318-094515](https://user-images.githubusercontent.com/52009863/76985571-a4da3580-68fd-11ea-8569-7192b771f0a7.jpg)

### 4. Search Input
![Screenshot_20200318-094542](https://user-images.githubusercontent.com/52009863/76985579-a86dbc80-68fd-11ea-967f-bb046cd4994d.jpg)

### 5a. Search Error - Invalid Location
![Screenshot_20200318-094558](https://user-images.githubusercontent.com/52009863/76985648-cb986c00-68fd-11ea-9a6d-5c41b5d72b13.jpg)

### 5b. Search Error - No Results
![Screenshot_20200318-094622](https://user-images.githubusercontent.com/52009863/76985683-d4893d80-68fd-11ea-9ebb-ae7c6c49bd53.jpg)

### 6. Search Results - Show More
![Screenshot_20200318-094635](https://user-images.githubusercontent.com/52009863/76985692-d81cc480-68fd-11ea-8976-aa6cd804426b.jpg)

### 7a. Service Detail 1
![Screenshot_20200318-094644](https://user-images.githubusercontent.com/52009863/76985699-dbb04b80-68fd-11ea-8cfa-d3ceb68f2556.jpg)

### 7b. Service Detail 2
![Screenshot_20200318-094652](https://user-images.githubusercontent.com/52009863/76985778-fb477400-68fd-11ea-94b9-4f0bc977a954.jpg)

**Comment by ian-lin-PG** [comment]
Screen Name: 4. Search Input
English Text: `call bc211`
Current Text: `請電話聯繫BC211`
Suggested Text: `請電話聯繫BC211`
Rationale: the translation for please,`請`, showed up twice which makes it more awkward.
![Screenshot_20200318-094542](https://user-images.githubusercontent.com/52009863/76986162-8294e780-68fe-11ea-8032-af529ac08544.jpg)

**Comment by ian-lin-PG** [comment]
Screen Name: 1. My Bookmarks
English Text: My Bookarmarks
Current Text: 我的最愛
Suggested Text: 我的書籤
Rationale: The difference is between `My Favourite` and `My Bookmarks`.
![Screenshot_20200318-094443](https://user-images.githubusercontent.com/52009863/76986600-1b2b6780-68ff-11ea-8009-5e8936dc27ea.jpg)

**Comment by ian-lin-PG** [comment]
1. My Bookmarks: DOUBLE CHECK (see above)
2. Questionnaire - New Topics Recommended: PASS
3. Help: PASS
4. Search Input: FAIL (see above)
5a. Search Error - Invalid Location: PASS
5b. Search Error - No Results: PASS
6. Search Results - Show More: PASS
7a. Service Detail 1: PASS
7b. Service Detail 2: PASS

**Comment by jparlina** [comment]
Created issue on GitHub [frontend issue #1065](https://app.zenhub.com/workspaces/arrival-advisor-5977956f40fbe90e67bb4155/issues/pg-irc/pathways-frontend/1065).

**Comment by jparlina** [comment]
Moved to GitHub frontline[ issue #1065](https://app.zenhub.com/workspaces/arrival-advisor-5977956f40fbe90e67bb4155/issues/pg-irc/pathways-frontend/1065)
