### ISSUE TITLE
QA Marketing Assets: English for Reference

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#38]
### 1a. Large Postcard - Front
![Screen Shot 2020-03-16 at 3 26 24 PM](https://user-images.githubusercontent.com/48343061/76804837-8576c780-679a-11ea-81f9-2c73ae5971ba.png)

### 1b. Large Postcard - Back
![Screen Shot 2020-03-16 at 3 26 53 PM](https://user-images.githubusercontent.com/48343061/76804861-945d7a00-679a-11ea-8288-e25c62ba1388.png)

### 2a. Small Postcard - Front
![Screen Shot 2020-03-16 at 3 25 29 PM](https://user-images.githubusercontent.com/48343061/76804778-624c1800-679a-11ea-9753-20d124495b7b.png)

### 2b. Small Postcard - Back
![Screen Shot 2020-03-16 at 3 25 51 PM](https://user-images.githubusercontent.com/48343061/76804799-6ed07080-679a-11ea-87f8-cfe461667a54.png)

### 3a. Large Poster - Register School
![Screen Shot 2020-03-16 at 3 22 24 PM](https://user-images.githubusercontent.com/48343061/76804647-0e413380-679a-11ea-9226-c95b4a90bddd.png)

### 3b. Large Poster - Services
![Screen Shot 2020-03-16 at 3 22 39 PM](https://user-images.githubusercontent.com/48343061/76804649-113c2400-679a-11ea-841a-ca7c28261b53.png)

### 3c. Large Poster - Learn English
![Screen Shot 2020-03-16 at 3 22 47 PM](https://user-images.githubusercontent.com/48343061/76804660-139e7e00-679a-11ea-8ad3-4720168913d8.png)

### 3d. Large Poster - Job
![Screen Shot 2020-03-16 at 3 22 59 PM](https://user-images.githubusercontent.com/48343061/76804716-36309700-679a-11ea-913f-f8b310a7260c.png)

**Comment by rasmus-storjohann-PG** [comment]
This story was used to help translators, no work to do on them, closing.
