### ISSUE TITLE
French QA - Marketing Assets

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#39]
### 1a. Large Postcard - Front
![Screen Shot 2020-03-16 at 3 41 21 PM](https://user-images.githubusercontent.com/48343061/76805697-b952ec80-679c-11ea-96e6-a642452f424f.png)

### 1b. Large Postcard - Back
![Screen Shot 2020-03-16 at 3 41 36 PM](https://user-images.githubusercontent.com/48343061/76805699-bc4ddd00-679c-11ea-9f44-4cb8b13b1681.png)

### 2a. Small Postcard - Front
![Screen Shot 2020-03-16 at 3 43 04 PM](https://user-images.githubusercontent.com/48343061/76805730-db4c6f00-679c-11ea-8d9b-00fbbae42c6b.png)

### 2b. Small Postcard - Back
![Screen Shot 2020-03-16 at 3 43 12 PM](https://user-images.githubusercontent.com/48343061/76805739-dedff600-679c-11ea-82be-a867cfe0f147.png)

### 3a. Large Poster - Register School
![Screen Shot 2020-03-16 at 3 44 03 PM](https://user-images.githubusercontent.com/48343061/76805783-ff0fb500-679c-11ea-9caf-846105e63f8f.png)

### 3b. Large Poster - Services
![Screen Shot 2020-03-16 at 3 44 32 PM](https://user-images.githubusercontent.com/48343061/76805799-0b940d80-679d-11ea-94d2-f28fcb190ff3.png)

### 3c. Large Poster - Learn English
![Screen Shot 2020-03-16 at 3 44 49 PM](https://user-images.githubusercontent.com/48343061/76805810-15b60c00-679d-11ea-91c9-10b2cdbd7c9f.png)

### 3d. Large Poster - Job
![Screen Shot 2020-03-16 at 3 45 07 PM](https://user-images.githubusercontent.com/48343061/76805822-2070a100-679d-11ea-8c80-07c8b864d262.png)

**Comment by ludivinegh** [comment]
Page Name: 1b. Large Postcard - Back
Issue (not linguistic): The App Store and Google Play logos are not present in French. Please double check if this is expected. See here: https://i.imgur.com/mGLudS9.png.

_Jean's update (Mar 23, 2020)_: Confirmed with @aron-chen-pg that this is expected. Logos are on the front for non-english postcards.

**Comment by ludivinegh** [comment]
Page Name: 1a. Large Postcard - Front
Issue (not linguistic): Please use the French version of the App Store and Google Play logos (here: https://i.imgur.com/DpNw79H.png). It was used for other pages, such as 2a. Small Postcard - Front.

_Jean's update (Mar 23, 2020)_: fixed
![Screen Shot 2020-03-24 at 6 30 56 PM](https://user-images.githubusercontent.com/48343061/77492386-b17af400-6dfd-11ea-9adc-6c6ecae890b5.png)

**Comment by ludivinegh** [comment]
Page Name: 2b. Small Postcard - Back
Issue (not linguistic): The formatting doesn't match in the source and target. The mismatches are highlighted here: https://i.imgur.com/px8cGOi.png.

Please make sure that the following is in bold:
- "Arrival Advisor peut vous aider à trouver les bons renseignements et services pour amorcer votre établissement dans une nouvelle communauté."
- "Arrival Advisor"
- "anglais"
- "français"
- "arabe"
- "chinois"
- "coréen"
- "punjabi"
- "tagalog"

Please make sure that the following is in italics: "(peacegeeks.org)".

Additionnally, the font size here: https://i.imgur.com/efIShhs.png doesn't match the source. Consider increasing it.

_Jean's update (Mar 23, 2020)_: fixed 
![Screen Shot 2020-03-24 at 6 34 13 PM](https://user-images.githubusercontent.com/48343061/77492612-37973a80-6dfe-11ea-89b0-9aeb513bde87.png)

**Comment by ludivinegh** [comment]
Page Name: 3a. Large Poster - Register School
Issue (not linguistic): The string "Download the Arrival Advisor app." was not translated in French (https://i.imgur.com/v4dqNyW.png).

_Jean's update (Mar 23, 2020)_: fixed 
![Screen Shot 2020-03-24 at 6 36 55 PM](https://user-images.githubusercontent.com/48343061/77492776-9eb4ef00-6dfe-11ea-9287-97d49e584871.png)

**Comment by ludivinegh** [comment]
Page Name: 3b. Large Poster - Services
English Texts: What services are available for immigrants and refugees?
Current Texts: Quels services sont-ils offerts aux immigrants et aux réfugiés?
Suggested Texts: Quels services sont offerts aux immigrants et aux réfugiés?

_Jean's update (Mar 23, 2020)_: fixed
![Screen Shot 2020-03-24 at 6 39 00 PM](https://user-images.githubusercontent.com/48343061/77492988-26026280-6dff-11ea-973b-192c6071afdb.png)

**Comment by ludivinegh** [comment]
3c. Large Poster - Learn English
Issue (not linguistic): The string "Download the Arrival Advisor app." was not translated in French (https://i.imgur.com/g0FPhbl.png).

_Jean's update (Mar 23, 2020)_: fixed
![Screen Shot 2020-03-24 at 6 44 33 PM](https://user-images.githubusercontent.com/48343061/77493187-acb73f80-6dff-11ea-8337-b052064976ff.png)

**Comment by ludivinegh** [comment]
3d. Large Poster - Job
Issue (not linguistic): The string "Download the Arrival Advisor app." was not translated in French (https://i.imgur.com/SBwY0Um.png).

_Jean's update (Mar 23, 2020)_: fixed
![Screen Shot 2020-03-24 at 6 44 41 PM](https://user-images.githubusercontent.com/48343061/77493202-b6d93e00-6dff-11ea-8c26-32ea3fbb4e63.png)

**Comment by ludivinegh** [comment]
2a. Small Postcard - Front: PASS

**Comment by ludivinegh** [comment]
3b. Large Poster - Services
Issue (not linguistic): In comparison with the source and other French pages, the font size used for this string is slightly too big (https://i.imgur.com/F4Im72a.png). Consider reducing it.

_Jean's update (Mar 23, 2020)_: fixed - see 3b update above

**Comment by jparlina** [comment]
@aron-chen-pg Please fix issues above. Thank you.

**Comment by jparlina** [comment]
All issues were fixed as updated in comments above.
