### ISSUE TITLE
Korean QA - Marketing Assets

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#40]
### 1a. Large Postcard - Front
![Screen Shot 2020-03-16 at 3 47 11 PM](https://user-images.githubusercontent.com/48343061/76805977-72192b80-679d-11ea-82c2-55f67049e432.png)

### 1b. Large Postcard - Back
![Screen Shot 2020-03-16 at 3 47 21 PM](https://user-images.githubusercontent.com/48343061/76805984-75141c00-679d-11ea-8918-63704bc7740d.png)

### 2a. Small Postcard - Front
![Screen Shot 2020-03-16 at 3 47 57 PM](https://user-images.githubusercontent.com/48343061/76806017-85c49200-679d-11ea-8f3d-405b2dec0b88.png)

### 2b. Small Postcard - Back
![Screen Shot 2020-03-16 at 3 48 16 PM](https://user-images.githubusercontent.com/48343061/76806031-9117bd80-679d-11ea-9cba-58f43066bffb.png)

### 3a. Large Poster - Register School
![Screen Shot 2020-03-16 at 3 50 45 PM](https://user-images.githubusercontent.com/48343061/76806158-e9e75600-679d-11ea-93f3-c7b14c16497b.png)

### 3b. Large Poster - Services
![Screen Shot 2020-03-16 at 3 51 02 PM](https://user-images.githubusercontent.com/48343061/76806174-f53a8180-679d-11ea-8492-e2881a6b07ac.png)

### 3c. Large Poster - Learn English
![Screen Shot 2020-03-16 at 3 51 24 PM](https://user-images.githubusercontent.com/48343061/76806202-008dad00-679e-11ea-8f30-56bf36b10d1c.png)

### 3d. Large Poster - Job
![Screen Shot 2020-03-16 at 3 51 41 PM](https://user-images.githubusercontent.com/48343061/76806222-0b484200-679e-11ea-88d6-53bc2b7f9258.png)

**Comment by rankanglee** [comment]
1a. Large Postcard - Front **PASS**
1b. Large Postcard - Back
Screenshot: https://www.screencast.com/t/ni83STSxPT9
English Text: Funded by:
Current: 의해 설립되다:
Suggested: 후원
Reason: Word-for-word translation. inappropriate for this context. 

2a. Small Postcard - Front **PASS**

**All the other remaining contents have the same issue as below:**
**Including:** 

- 3a. Large Poster - Register School
- 3b. Large Poster - Services
- 3c. Large Poster - Learn English
- 3d. Large Poster - Job

Screenshot: https://www.screencast.com/t/LOZzXehL (as an example)
English Text: Funded by:
Current: 의해 설립되다:
Suggested: 후원
Reason: Word-for-word translation. inappropriate for this context.

**Comment by jparlina** [comment]
@rankanglee Did the posters pass QA? 

- 3a. Large Poster - Register School
- 3b. Large Poster - Services
- 3c. Large Poster - Learn English
- 3d. Large Poster - Job

**Comment by rankanglee** [comment]
@jparlina Please see my edited comments above. Thanks!

**Comment by aron-chen-pg** [comment]
The documents have been updated and re-uploaded to the same Drive folder. Please review. @jparlina

**Comment by jparlina** [comment]
@aron-chen-pg The [back of the large postcard ](https://drive.google.com/file/d/1pt9q9dipZwB5hUqwamOzOvQ1q7GqLRDq/view?usp=sharing)hasn't been fixed. Please update. Thanks.

**Comment by aron-chen-pg** [comment]
The large postcard has been updated and reuploaded, please review. @jparlina

**Comment by jparlina** [comment]
All issues were fixed:

### 1b. Large Postcard - Back
![Screen Shot 2020-03-24 at 6 51 07 PM](https://user-images.githubusercontent.com/48343061/77493483-80e88980-6e00-11ea-94c5-7f5f76b86732.png)

### 2b. Small Postcard - Back
![Screen Shot 2020-03-24 at 6 54 01 PM](https://user-images.githubusercontent.com/48343061/77493639-e8063e00-6e00-11ea-9684-c5f4253dcd93.png)

### 3a. Large Poster - Register School
![Screen Shot 2020-03-24 at 6 56 30 PM](https://user-images.githubusercontent.com/48343061/77493924-a1651380-6e01-11ea-80d7-36cb6acd7f4b.png)

### 3b. Large Poster - Services
![Screen Shot 2020-03-24 at 6 56 40 PM](https://user-images.githubusercontent.com/48343061/77493934-a5913100-6e01-11ea-8440-86f528d2b864.png)

### 3c. Large Poster - Learn English
![Screen Shot 2020-03-24 at 6 56 47 PM](https://user-images.githubusercontent.com/48343061/77493940-a7f38b00-6e01-11ea-94ea-9be16dbd2470.png)

### 3d. Large Poster - Job
![Screen Shot 2020-03-24 at 6 56 54 PM](https://user-images.githubusercontent.com/48343061/77493945-ab871200-6e01-11ea-85a2-9942d08edbda.png)
