### ISSUE TITLE
Punjabi QA - Marketing Assets

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#41]
### 1a. Large Postcard - Front
![Screen Shot 2020-03-16 at 3 54 37 PM](https://user-images.githubusercontent.com/48343061/76806385-785bd780-679e-11ea-8f04-5a2b47729f10.png)

### 1b. Large Postcard - Back
![Screen Shot 2020-03-16 at 3 54 45 PM](https://user-images.githubusercontent.com/48343061/76806390-7b56c800-679e-11ea-8a1c-37f531d0a183.png)

### 2a. Small Postcard - Front
![Screen Shot 2020-03-16 at 3 55 17 PM](https://user-images.githubusercontent.com/48343061/76806412-8f9ac500-679e-11ea-93c7-0b0d2f54c8ab.png)

### 2b. Small Postcard - Back
![Screen Shot 2020-03-16 at 3 55 26 PM](https://user-images.githubusercontent.com/48343061/76806423-945f7900-679e-11ea-8d0b-0ea42f55c0ec.png)

### 3a. Large Poster - Register School
![Screen Shot 2020-03-16 at 3 56 03 PM](https://user-images.githubusercontent.com/48343061/76806473-b8bb5580-679e-11ea-978d-9da10a1d168b.png)

### 3b. Large Poster - Services
![Screen Shot 2020-03-16 at 3 56 16 PM](https://user-images.githubusercontent.com/48343061/76806484-bce77300-679e-11ea-8694-16278d7e0e76.png)

### 3c. Large Poster - Learn English
![Screen Shot 2020-03-16 at 3 56 25 PM](https://user-images.githubusercontent.com/48343061/76806488-bfe26380-679e-11ea-935e-c7b84c55d556.png)

### 3d. Large Poster - Job
![Screen Shot 2020-03-16 at 3 56 33 PM](https://user-images.githubusercontent.com/48343061/76806490-c244bd80-679e-11ea-8903-9fa8f716f540.png)

**Comment by aalam** [comment]
All pages have issue, which is Rendering issue with software. 
    1a. Large Postcard - Front - Issue
    1b. Large Postcard - Back - Issue

    2a. Small Postcard - Front - Issue
    2b. Small Postcard - Back - Issue

    3a. Large Poster - Register School - Issue
    3b. Large Poster - Services - Issue
    3c. Large Poster - Learn English - Issue
    3d. Large Poster - Job - Issue

Example: 1a. Large Postcard - Front - Issue
Original translated Text: ਅਸੀਂ ਬੀਸੀ 'ਚ ਨਵੇਂ ਹਾਂ। ਅਸੀਂ ਆਪਣੀ **ਕਮਉਿਨਟੀ** ਨਾਲ **ਕਵਿੇਂ** ਸ਼ੁਰੂਆਤ ਕਰੀਏ
Rendered Text: ਅਸੀਂ ਬੀਸੀ 'ਚ ਨਵੇਂ ਹਾਂ। ਅਸੀਂ ਆਪਣੀ **ਕਮਿਊਨਟੀ** ਨਾਲ **ਕਿਵੇਂ** ਸ਼ੁਰੂਆਤ ਕਰੀਏ

Suggestion to fix: If this is Adobe software to create PDF, then change 'Adobe Paragraph Composer' to 'Adobe world-Ready Paragraph Composer' as below for Punjabi text box.
Paragraph Style Options -> Justification -> Composer – **Adobe world-Ready Paragraph Composer**

**Comment by aron-chen-pg** [comment]
@aalam I have addressed issues by switching composer to Middle East & South Asian composer in Illustrator (which is the parallel version of Adobe world-Ready Paragraph Composer). However, I believe there are still some issues with the translation. Regarding example 1a. Large Postcard, the translations don't seem to be aligned. When typing in Middle East & South Asian composer, the string returns:
![image](https://user-images.githubusercontent.com/54860686/77103654-fc4cd400-69d7-11ea-82dd-b6dc5967d89b.png)
Whereas when typing in the original Adobe composer, the string returns:
![image](https://user-images.githubusercontent.com/54860686/77103765-30c09000-69d8-11ea-9bfb-cdaacdc9767f.png)
Which version is correct?

**Comment by aalam** [comment]
hi @aron-chen-pg 
Top image is good. Bottom one has rendering issue.

**Comment by aron-chen-pg** [comment]
The documents have been updated and re-uploaded to the same Drive folder. Please review. @jparlina

**Comment by jparlina** [comment]
Updated screenshots for QA: 

### 1a. Large Postcard - Front
![Screen Shot 2020-03-23 at 11 15 15 AM](https://user-images.githubusercontent.com/48343061/77351134-95daf500-6cfa-11ea-9524-038fe0b79584.png)

### 1b. Large Postcard - Back
![Screen Shot 2020-03-23 at 11 15 28 AM](https://user-images.githubusercontent.com/48343061/77350203-61b30480-6cf9-11ea-9307-9ce51a74015d.png)

### 2a. Small Postcard - Front
![Screen Shot 2020-03-23 at 11 37 32 AM](https://user-images.githubusercontent.com/48343061/77351226-b86d0e00-6cfa-11ea-9d4c-1264d52744ac.png)

### 2b. Small Postcard - Back
![Screen Shot 2020-03-23 at 11 37 41 AM](https://user-images.githubusercontent.com/48343061/77351234-bb67fe80-6cfa-11ea-85f7-ecf618fb8867.png)

### 3a. Large Poster - Register School
![Screen Shot 2020-03-23 at 11 39 44 AM](https://user-images.githubusercontent.com/48343061/77351498-18fc4b00-6cfb-11ea-8de7-f71ac4ea7980.png)

### 3b. Large Poster - Services
![Screen Shot 2020-03-23 at 11 39 55 AM](https://user-images.githubusercontent.com/48343061/77351507-1c8fd200-6cfb-11ea-8739-e5fb64460487.png)

### 3c. Large Poster - Learn English
![Screen Shot 2020-03-23 at 11 40 03 AM](https://user-images.githubusercontent.com/48343061/77351518-1f8ac280-6cfb-11ea-82b7-6bdf5136c4be.png)

### 3d. Large Poster - Job
![Screen Shot 2020-03-23 at 11 40 13 AM](https://user-images.githubusercontent.com/48343061/77351523-21ed1c80-6cfb-11ea-8485-9a088c7edebe.png)

**Comment by aalam** [comment]
2a. Small Postcard - Front - 
Rendering issue (Correct Text  - ਬ੍ਰਿਟਿਸ਼ (Yellow/blue)) - Critical issue
below/above base position (Yellow highlighted) -  Not critical issue

![image](https://user-images.githubusercontent.com/600806/77390188-753e8980-6d52-11ea-9df4-f8623bdf73d5.png)

2a. Small Postcard - Front
Rendering issue (Correct Text  - ਬ੍ਰਿਟਿਸ਼ (Yellow/blue)) - Critical issue
![image](https://user-images.githubusercontent.com/600806/77389935-bc784a80-6d51-11ea-9851-17a8f584e48f.png)

2b. Small Postcard - Back  - Not critical issue
below/above base position (Yellow highlighted) 
![image](https://user-images.githubusercontent.com/600806/77392801-fac53800-6d58-11ea-8bb0-26fe643576d2.png)

Is it possible to change fonts for Punjabi Text?

**Comment by aalam** [comment]
1a. Large Postcard - Front - PASS (minor text layout)
    1b. Large Postcard - Back

    2a. Small Postcard - Front
    2b. Small Postcard - Back

    3a. Large Poster - Register School - PASS
    3b. Large Poster - Services - PASS  (minor text layout)
    3c. Large Poster - Learn English - PASS
    3d. Large Poster - Job - PASS

**Comment by jparlina** [comment]
@aron-chen-pg Please see issues identified above. Thanks.

**Comment by aron-chen-pg** [comment]
@aalam Does changing fonts help solve the rendering issues? Just wanted to know why you wanted the font change. For your information, the current font we use is called Gurnukhi MN.

**Comment by aron-chen-pg** [comment]
I have used a different font for 1) Large Postcard and 2) Small Postcard which seems to solve the rendering issues. Please review.
### 1a. Large Postcard - Front
![image](https://user-images.githubusercontent.com/54860686/77481032-0e67b180-6de0-11ea-9fe5-d51edc0fff98.png)
### 1b. Large Postcard - Back
![image](https://user-images.githubusercontent.com/54860686/77481083-2808f900-6de0-11ea-9d86-3acc234afdf3.png)
### 2a. Small Postcard - Front
![image](https://user-images.githubusercontent.com/54860686/77481150-4c64d580-6de0-11ea-870a-b28462d845bc.png)
### 2b. Small Postcard - Back
![image](https://user-images.githubusercontent.com/54860686/77481188-5e467880-6de0-11ea-80af-8b76299548af.png)

Also, could you elaborate on the minor text layout issue? Would it cause any readability complication? Thanks. @aalam

**Comment by aalam** [comment]
Hi @aron-chen-pg 

Those cards are really beautiful with text as compared to previous fonts and rendering is perfect.
Even tiny text in screenshot is completely clear. 

![image](https://user-images.githubusercontent.com/600806/77483662-f561ff00-6de5-11ea-91ef-ef159fc562c1.png)

Old font:
![image](https://user-images.githubusercontent.com/600806/77483856-64d7ee80-6de6-11ea-95d4-5d8134d52aec.png)


Thanks for fixing. Readability is good too. 👍

**Comment by jparlina** [comment]
Great! Thank you @aalam and @aron-chen-pg!
