### ISSUE TITLE
Chinese Simplified QA - Marketing Assets

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#42]
### 1a. Large Postcard - Front
![Screen Shot 2020-03-16 at 4 06 12 PM](https://user-images.githubusercontent.com/48343061/76806959-17350380-67a0-11ea-9953-3f87fcfd186e.png)

### 1b. Large Postcard - Back
![Screen Shot 2020-03-16 at 4 06 19 PM](https://user-images.githubusercontent.com/48343061/76806965-1a2ff400-67a0-11ea-9564-8a09cbad0e8c.png)

### 2a. Small Postcard - Front
![Screen Shot 2020-03-16 at 4 04 33 PM](https://user-images.githubusercontent.com/48343061/76806970-1d2ae480-67a0-11ea-8cd6-ec420477f023.png)

### 2b. Small Postcard - Back
![Screen Shot 2020-03-16 at 4 04 42 PM](https://user-images.githubusercontent.com/48343061/76806972-1f8d3e80-67a0-11ea-93a7-b30f1c37dba2.png)

### 3a. Large Poster - Register School
![Screen Shot 2020-03-16 at 4 07 20 PM](https://user-images.githubusercontent.com/48343061/76807029-4d728300-67a0-11ea-996e-4d7a89334d15.png)

### 3b. Large Poster - Services
![Screen Shot 2020-03-16 at 4 07 30 PM](https://user-images.githubusercontent.com/48343061/76807035-506d7380-67a0-11ea-8e5d-c355840e1ffe.png)

### 3c. Large Poster - Learn English
![Screen Shot 2020-03-16 at 4 07 38 PM](https://user-images.githubusercontent.com/48343061/76807038-52cfcd80-67a0-11ea-9d36-9222acef964f.png)

### 3d. Large Poster - Job
![Screen Shot 2020-03-16 at 4 07 46 PM](https://user-images.githubusercontent.com/48343061/76807043-55cabe00-67a0-11ea-96fa-2364db68e726.png)

**Comment by ian-lin-PG** [comment]
1a, 3a, 3b, 3c, 3d:
English Text: `We can Help.`
Current Text: `我们帮助您。`
Suggested Text: `我们能帮您。`
Rationale: The difference is between `We help you.` and `We can help you.`.

**Comment by jparlina** [comment]
Noted on [Localized Print Marketing - REVISED Mar 2020](https://docs.google.com/spreadsheets/d/1jeLKFa3gSUoWjg1h9ojJ-BSCCrcRVGxpnYzurrujQKk/edit#gid=710912874) spreadsheet for Aron to fix

**Comment by aron-chen-pg** [comment]
Changes have been made, please review. All files are from the same drive folder with the same file name. https://drive.google.com/open?id=1jBqfvJaTcadvG_r9jia3AMwZQpOlUh-0

**Comment by jparlina** [comment]
@ian-lin-PG Please QA the revisions as per your suggested texts (circled in red on the screenshots) and indicate Pass/Fail for each item# in the comment. Thank you. 

English Text: We can Help.
**Revised Text: 我们能帮您。**

### 1a. Large Postcard - Front
<img width="706" alt="Screen Shot 2020-03-19 at 5 32 42 PM" src="https://user-images.githubusercontent.com/48343061/77127125-9e84b000-6a08-11ea-94d3-aca24bccf2d3.png">

### 3a. Large Poster - Register School
![Screen Shot 2020-03-19 at 5 40 24 PM](https://user-images.githubusercontent.com/48343061/77127607-6bdbb700-6a0a-11ea-9ab6-f41e61908ec5.png)


### 3b. Large Poster - Services
![Screen Shot 2020-03-19 at 5 40 47 PM](https://user-images.githubusercontent.com/48343061/77127611-70a06b00-6a0a-11ea-9a0f-2c047bc25164.png)


### 3c. Large Poster - Learn English
![Screen Shot 2020-03-19 at 5 40 55 PM](https://user-images.githubusercontent.com/48343061/77127616-739b5b80-6a0a-11ea-9219-eef915d60652.png)


### 3d. Large Poster - Job
![Screen Shot 2020-03-19 at 5 41 05 PM](https://user-images.githubusercontent.com/48343061/77127625-77c77900-6a0a-11ea-8f3c-8bee8b6a4485.png)

**Comment by ian-lin-PG** [comment]
1a. Large Postcard - Front: PASS
1b. Large Postcard - Back: PASS
2a. Small Postcard - Front: PASS
2b. Small Postcard - Back: PASS
3a. Large Poster - Register School: PASS
3b. Large Poster - Services: PASS
3c. Large Poster - Learn English: PASS
3d. Large Poster - Job: PASS
