### ISSUE TITLE
Chinese Traditional QA - Marketing Assets

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#43]
### 1a. Large Postcard - Front
![Screen Shot 2020-03-16 at 4 09 26 PM](https://user-images.githubusercontent.com/48343061/76807110-86125c80-67a0-11ea-810f-f23e10f26e39.png)

### 1b. Large Postcard - Back
![Screen Shot 2020-03-16 at 4 09 54 PM](https://user-images.githubusercontent.com/48343061/76807137-96c2d280-67a0-11ea-89ee-9a3b4d9b136c.png)

### 2a. Small Postcard - Front
![Screen Shot 2020-03-16 at 4 10 20 PM](https://user-images.githubusercontent.com/48343061/76807169-a6421b80-67a0-11ea-9899-6b3ac81cae48.png)

### 2b. Small Postcard - Back
![Screen Shot 2020-03-16 at 4 10 39 PM](https://user-images.githubusercontent.com/48343061/76807182-b1954700-67a0-11ea-83a2-16c57f701cdb.png)

### 3a. Large Poster - Register School
![Screen Shot 2020-03-16 at 4 15 24 PM](https://user-images.githubusercontent.com/48343061/76807379-6c254980-67a1-11ea-807e-ee085734ffed.png)

### 3b. Large Poster - Services
![Screen Shot 2020-03-16 at 4 15 33 PM](https://user-images.githubusercontent.com/48343061/76807383-70516700-67a1-11ea-8796-8e5e404bb8b4.png)

### 3c. Large Poster - Learn English
![Screen Shot 2020-03-16 at 4 15 40 PM](https://user-images.githubusercontent.com/48343061/76807389-72b3c100-67a1-11ea-8b65-ebb2895acbc4.png)

### 3d. Large Poster - Job
![Screen Shot 2020-03-16 at 4 15 48 PM](https://user-images.githubusercontent.com/48343061/76807391-75161b00-67a1-11ea-83d6-7443897a8988.png)

**Comment by ian-lin-PG** [comment]
1a, 3a, 3b, 3c, 3d:
English Text: `We can Help.`
Current Text: `我們幫助您。`
Suggested Text: `我們能幫您。`
Rationale: The difference is between `We help you.` and `We can help you.`.

**Comment by jparlina** [comment]
Noted on [Localized Print Marketing - REVISED Mar 2020](https://docs.google.com/spreadsheets/d/1jeLKFa3gSUoWjg1h9ojJ-BSCCrcRVGxpnYzurrujQKk/edit#gid=710912874) spreadsheet for Aron to fix

**Comment by aron-chen-pg** [comment]
Changes have been made, please review. All files are from the same drive folder with the same file name. https://drive.google.com/open?id=1jBqfvJaTcadvG_r9jia3AMwZQpOlUh-0

**Comment by jparlina** [comment]
@ian-lin-PG Please QA the revisions (circled in red on the screenshots) as per your suggested texts and indicate Pass/Fail for each in the comment. Thank you. 

English Text: We can Help.
**Revised Text: 我們能幫您。**

### 1a. Large Postcard - Front
<img width="706" alt="Screen Shot 2020-03-19 at 5 46 41 PM" src="https://user-images.githubusercontent.com/48343061/77127424-a2fd9880-6a09-11ea-81bc-6d5161cd8990.png">

### 3a. Large Poster - Register School
![Screen Shot 2020-03-19 at 5 48 27 PM](https://user-images.githubusercontent.com/48343061/77127662-9a599200-6a0a-11ea-9787-0bec5e4a763d.png)

### 3b. Large Poster - Services
![Screen Shot 2020-03-19 at 5 48 55 PM](https://user-images.githubusercontent.com/48343061/77127668-9f1e4600-6a0a-11ea-94d3-e7c24c8b796f.png)

### 3c. Large Poster - Learn English
![Screen Shot 2020-03-19 at 5 49 18 PM](https://user-images.githubusercontent.com/48343061/77127675-a5142700-6a0a-11ea-8c77-b0eaa6b28236.png)

### 3d. Large Poster - Job
![Screen Shot 2020-03-19 at 5 49 39 PM](https://user-images.githubusercontent.com/48343061/77127678-a8a7ae00-6a0a-11ea-957e-6db96a39e539.png)

**Comment by ian-lin-PG** [comment]
1a. Large Postcard - Front: PASS
1b. Large Postcard - Back: PASS
2a. Small Postcard - Front: PASS
2b. Small Postcard - Back: PASS
3a. Large Poster - Register School: PASS
3b. Large Poster - Services: PASS
3c. Large Poster - Learn English: PASS
3d. Large Poster - Job: PASS
