### ISSUE TITLE
Arabic QA - Marketing Assets

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#44]
### 1a. Large Postcard - Front
![Screen Shot 2020-03-16 at 6 27 54 PM](https://user-images.githubusercontent.com/48343061/76813022-e3fc6f80-67b3-11ea-8491-1cc6f4993933.png)

### 1b. Large Postcard - Back
![Screen Shot 2020-03-16 at 6 28 28 PM](https://user-images.githubusercontent.com/48343061/76813033-f1b1f500-67b3-11ea-81bf-60f42eccbfa3.png)

### 2a. Small Postcard - Front
![Screen Shot 2020-03-16 at 6 32 32 PM](https://user-images.githubusercontent.com/48343061/76813235-89afde80-67b4-11ea-98e3-132951dc1b90.png)

### 2b. Small Postcard - Back
![Screen Shot 2020-03-16 at 6 32 43 PM](https://user-images.githubusercontent.com/48343061/76813238-8caacf00-67b4-11ea-8855-03adb2b96fca.png)

### 3a. Large Poster - Register School
![Screen Shot 2020-03-16 at 6 33 30 PM](https://user-images.githubusercontent.com/48343061/76813267-a64c1680-67b4-11ea-92c8-d07f473b3f2d.png)

### 3b. Large Poster - Services
![Screen Shot 2020-03-16 at 6 33 48 PM](https://user-images.githubusercontent.com/48343061/76813281-b2d06f00-67b4-11ea-919d-d4c8c7b20b3e.png)

### 3c. Large Poster - Learn English
![Screen Shot 2020-03-16 at 6 34 08 PM](https://user-images.githubusercontent.com/48343061/76813292-bc59d700-67b4-11ea-861c-831bd8716f3e.png)

### 3d. Large Poster - Job
![Screen Shot 2020-03-16 at 6 34 32 PM](https://user-images.githubusercontent.com/48343061/76813316-caa7f300-67b4-11ea-973f-6b40f306e08d.png)

**Comment by hhaboh** [comment]
1a. Large Postcard - Front: PASS

1b. Large Postcard - Back: Fail (2 issues)
Source text: Download the App.
Current text: قيبطت لزّن Arrival Advisor.
Suggested text: نزّل تطبيق Arrival Advisor.
Rationale: Arabic text is in reverse order.

Source text: Whether you're looking for a job, applying for healthcare, or want to enrol your children in school, Arrival Advisor can help you find the right information.
Current text: سواء كنت تبحث عن وظيفة أو تتقدم بطلب للحصول على رعاية صحية أو ترغب في قيد أطفالك في المدارس، يمكن لتطبيق Advisor Arrival مساعدتك في البحث عن المعلومات المناسبة.
Suggested text: سواء كنت تبحث عن وظيفة أو تتقدم بطلب للحصول على رعاية صحية أو ترغب في قيد أطفالك في المدارس، يمكن لتطبيق Arrival Advisor مساعدتك في البحث عن المعلومات المناسبة.
Rationale: "Arrival Advisor" shows as "Advisor Arrival" in the current text.

2a. Small Postcard - Front: PASS

2b. Small Postcard - Back: PASS

3a. Large Poster - Register School: Fail (1 issue)
Source text: Download the Arrival Advisor app.
Current text: قيبطت لزّن Arrival Advisor.
Suggested text: نزّل تطبيق Arrival Advisor.
Rationale: Arabic text is in reverse order.

3b. Large Poster - Services: Fail (1 issue)
Source text: Download the Arrival Advisor app.
Current text: قيبطت لزّن Arrival Advisor.
Suggested text: نزّل تطبيق Arrival Advisor.
Rationale: Arabic text is in reverse order.

3c. Large Poster - Learn English: Fail (1 issue)
Source text: Download the Arrival Advisor app.
Current text: قيبطت لزّن Arrival Advisor.
Suggested text: نزّل تطبيق Arrival Advisor.
Rationale: Arabic text is in reverse order.

3d. Large Poster - Job: Fail (1 issue)
Source text: Download the Arrival Advisor app.
Current text: قيبطت لزّن Arrival Advisor.
Suggested text: نزّل تطبيق Arrival Advisor.
Rationale: Arabic text is in reverse order.

**Comment by aron-chen-pg** [comment]
The documents have been updated and re-uploaded to the same Drive folder. Please review. @jparlina

**Comment by jparlina** [comment]
All issues were fixed:

### 1b. Large Postcard - Back: 
Two issues: 

Source text: Download the App.
Current text: قيبطت لزّن Arrival Advisor.
Suggested text: نزّل تطبيق Arrival Advisor.
Rationale: Arabic text is in reverse order.

Source text: Whether you're looking for a job, applying for healthcare, or want to enrol your children in school, Arrival Advisor can help you find the right information.
Current text: سواء كنت تبحث عن وظيفة أو تتقدم بطلب للحصول على رعاية صحية أو ترغب في قيد أطفالك في المدارس، يمكن لتطبيق Advisor Arrival مساعدتك في البحث عن المعلومات المناسبة.
Suggested text: سواء كنت تبحث عن وظيفة أو تتقدم بطلب للحصول على رعاية صحية أو ترغب في قيد أطفالك في المدارس، يمكن لتطبيق Arrival Advisor مساعدتك في البحث عن المعلومات المناسبة.
Rationale: "Arrival Advisor" shows as "Advisor Arrival" in the current text.

![Screen Shot 2020-03-24 at 7 04 56 PM](https://user-images.githubusercontent.com/48343061/77494372-cd34c900-6e02-11ea-879b-686ab9c1ca97.png)

### 3a-d Large Posters
Source text: Download the Arrival Advisor app.
Current text: قيبطت لزّن Arrival Advisor.
Suggested text: نزّل تطبيق Arrival Advisor.
Rationale: Arabic text is in reverse order.

![Screen Shot 2020-03-24 at 7 10 33 PM](https://user-images.githubusercontent.com/48343061/77494660-872c3500-6e03-11ea-9d55-73a70cf0247f.png)

![Screen Shot 2020-03-24 at 7 10 43 PM](https://user-images.githubusercontent.com/48343061/77494665-898e8f00-6e03-11ea-80f8-0e24f1cc8ec5.png)

![Screen Shot 2020-03-24 at 7 10 52 PM](https://user-images.githubusercontent.com/48343061/77494673-8e534300-6e03-11ea-8c3b-bc6bd2aa4e78.png)

![Screen Shot 2020-03-24 at 7 11 02 PM](https://user-images.githubusercontent.com/48343061/77494684-93b08d80-6e03-11ea-8b5a-333233356719.png)
