### ISSUE TITLE
French QA: COVID-19 Information

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#49]
![IMG_4224](https://user-images.githubusercontent.com/48343061/77807709-df527980-7045-11ea-90c4-9f3b70da2193.jpeg)

**Comment by ludivinegh** [comment]
English Texts: Many of our listed services are transitioning to alternate service delivery methods. Please check service providers' websites for details.
Current Texts: La plupart de nos services répertoriés sont en train de passer à d’autres méthodes de prestations de services.Pour plus de détails, veuillez consulter les sites Web des fournisseurs de services.
Suggested Texts: La plupart de nos services répertoriés sont en train de passer à d’autres méthodes de prestations de services.Pour plus de détails, veuillez consulter les sites Web des fournisseurs de services.
Rationale: There's a missing space after the first full stop.

**Comment by jparlina** [comment]
Fixed on weblate. Jean to review after next staging release.

**Comment by jparlina** [comment]
Fixed on Staging V1.26.0, Server 1.3.25
<img width="431" alt="Screen Shot 2020-04-03 at 5 34 14 PM" src="https://user-images.githubusercontent.com/48343061/78414547-65843800-75d1-11ea-8320-92bc5de914fa.png">
