### ISSUE TITLE
Korean QA: COVID-19 Information

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#50]
![IMG_4225](https://user-images.githubusercontent.com/48343061/77807781-204a8e00-7046-11ea-848d-4bc319fa2569.jpeg)

**Comment by rankanglee** [comment]
**Screenshot:** 
![image](https://user-images.githubusercontent.com/47799302/77829905-4aea2480-70e2-11ea-8f47-b838e0816110.png)

**Current:**
많은 서비스들이 대체 서비스 제공 방안을 마련하고 있습니다.자세한 내용은 서비스 제공자의 웹사이트를 확인해 주세요.

**Suggested**
많은 서비스들이 대체 서비스 제공 방안을 마련하고 있습니다. 자세한 내용은 서비스 제공자의 웹사이트를 확인해 주세요.

**Reason** spacing error

**Comment by jparlina** [comment]
Fixed on weblate. Jean to review after next staging release.

**Comment by jparlina** [comment]
Fixed on Staging V1.25.0, server V1.3.25
<img width="434" alt="Screen Shot 2020-04-03 at 5 36 26 PM" src="https://user-images.githubusercontent.com/48343061/78414602-c57ade80-75d1-11ea-98a6-92a73c264689.png">
