### ISSUE TITLE
Punjabi QA: COVID-19 Information

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#51]
![IMG_4226](https://user-images.githubusercontent.com/48343061/77807868-6869b080-7046-11ea-96e7-3ab0c493a9fe.jpeg)

**Comment by aalam** [comment]
Translation update:
English Texts: Answer a few questions about your situation to get personalized recommendations of topics and services to help you settle in British Columbia.
Current Texts: ਬ੍ਰਿਟਿਸ਼ ਕੋਲੰਬੀਆਂ ਵਿੱਚ ਤੁਹਾਨੂੰ ਸੈਟਲ ਹੋਣ ਲਈ ਮਦਦ ਕਰਨ ਵਾਸਤੇ ਵਿਸ਼ਿਆ ਤੇ ਸੇਵਾਵਾਂ ਦੀ ਤੁਹਾਡੇ ਲਈ ਸਿਫਾਰਸ਼ਾਂ ਲੈਣ ਲਈ ਆਪਣੇ ਹਾਲਤ ਬਾਰੇ ਕੁਝ ਸਵਾਲਾਂ ਦੇ ਜਵਾਬ।
Suggested Texts:ਬ੍ਰਿਟਿਸ਼ ਕੋਲੰਬੀਆ ਵਿੱਚ ਤੁਹਾਨੂੰ ਸੈਟਲ ਹੋਣ ਲਈ ਮਦਦ ਕਰਨ ਵਾਸਤੇ ਵਿਸ਼ਿਆ ਤੇ ਸੇਵਾਵਾਂ ਦੀ ਤੁਹਾਡੇ ਲਈ ਸਿਫਾਰਸ਼ਾਂ ਲੈਣ ਲਈ ਆਪਣੇ ਹਾਲਤ ਬਾਰੇ ਕੁਝ ਸਵਾਲਾਂ ਦੇ ਜਵਾਬ ਦਿਓ।

**Comment by jparlina** [comment]
@aalam Thank you for also reviewing the bottom portion of the screen shot. Could you please explain the rational for your suggested texts or how it is different from the current texts? (e.g. typos, mistranslations, grammatical error).

What about the top portion regarding the COVID-19 information (highlighted in red box)? Please specify whether the language translations pass/fail. If anything need to be revised, please specify the same as the usual QA process: 
- English Texts
- Current Texts:
- Suggested Texts:
- Rationale: 

Let me know if you have any questions. Thanks.

**Comment by aalam** [comment]
Top portion is good. 
Translation is PASS.

**Comment by aalam** [comment]
bottom portion: this is **Enhancement** to clarify sentence, not error or typo.

**Comment by jparlina** [comment]
Thank you for clarifying @aalam. We will revise the bottom portion as per your suggestion.

**Comment by jparlina** [comment]
Uploaded suggested texts to weblate. Jean to review after the next staging release.

**Comment by jparlina** [comment]
Revised on Staging Version 1.26.0:
![Screen Shot 2020-04-03 at 5 45 25 PM](https://user-images.githubusercontent.com/48343061/78414847-08898180-75d3-11ea-8348-3739d96bdb96.png)

**Comment by aalam** [comment]
This is perfectly good.

Thanks @jparlina
