### ISSUE TITLE
Tagalog QA: Jan-Mar 2020 Translations

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#52]
Please refer to the [English screenshots here](https://github.com/pg-irc/arrival-advisor-qa/issues/62) for your reference. 

### 1. Home
![Screen Shot 2020-04-07 at 10 44 58 PM](https://user-images.githubusercontent.com/48343061/78748665-6e527200-7921-11ea-910b-38b31c711956.png)

### 2. Questionnaire - New Topics Recommended
<img width="442" alt="Screen Shot 2020-03-31 at 6 28 20 PM" src="https://user-images.githubusercontent.com/48343061/78089862-69b81780-737d-11ea-866c-03aadf438cce.png">

### 3. Help
<img width="432" alt="Screen Shot 2020-03-31 at 6 29 33 PM" src="https://user-images.githubusercontent.com/48343061/78089941-a1bf5a80-737d-11ea-9fd1-e100fc18ed5a.png">

### 4. Search Input
![Screen Shot 2020-04-09 at 8 18 00 PM](https://user-images.githubusercontent.com/48343061/78962637-92d95600-7aa9-11ea-9e9d-760f2293435f.png)

### 5. Search Error - No Results
![Screen Shot 2020-04-07 at 10 54 51 PM](https://user-images.githubusercontent.com/48343061/78749319-df465980-7922-11ea-87ba-d9c22ccee549.png)

### 6. Search Results - Show More
<img width="438" alt="Screen Shot 2020-03-31 at 6 34 38 PM" src="https://user-images.githubusercontent.com/48343061/78090381-cbc54c80-737e-11ea-92ac-da6055f29e0c.png">

### 7. Service Detail 1
![Screen Shot 2020-04-07 at 11 02 28 PM](https://user-images.githubusercontent.com/48343061/78750016-40baf800-7924-11ea-8ca6-e8f1ee56f4b6.png)

![Screen Shot 2020-04-07 at 11 07 30 PM](https://user-images.githubusercontent.com/48343061/78750260-baeb7c80-7924-11ea-87eb-e28408909905.png)

### 8. What's New
<img width="434" alt="Screen Shot 2020-04-09 at 8 12 58 PM" src="https://user-images.githubusercontent.com/48343061/78959022-90bdca00-7a9e-11ea-9846-5789d5a72e8c.png">

**Comment by niko-pg** [comment]
### Issue 1a: Screen Name: Home
English Texts:
"Questions about Covid-19?"
Translated Texts:
"May Tanong ba Kayo tungkol sa COVID-19"?
Suggested Texts:
"May tanong ba kayo tungkol sa COVID-19?"
Rationale:
Translation is correct. Just unnecessary capitalization were applied.

### Issue 1b: Screen Name: Home
English Texts:
"Get information based on your needs"
Translated Texts:
"Makakuha ng impormasyon batay sa pangangailangan mo"
Suggested Texts:
"Kumuha ng impormasyon batay sa pangangailangan mo"
Rationale:
"Makakuha" is a wrong verb tense which directly translates to "to be able to get". "Kumuha" is the correct translation for "get"

### Issue 2: Screen Name: Questionnaire - New Topics Recommended
English Texts:
"See recommendations"
Translated Texts:
"Tingnan ang mga rekomendasyo"
Suggested Texts:
"Tingnan ang mga rekomendasyon"
Rationale:
Translation is correct though "rekomendasyo" is missing "n" at the end. Should be "rekomendasyon"

### Issue 3: Screen Name: Help
English Texts:
"Multilingual health information services"
Translated Texts:
"Maramihang wika na mga serbisyo sa impormasyon sa kalusugan"
Suggested Texts:
"Serbisyong Impormasyong pangkalusugan sa maramihang wika"
Rationale:
Rearranged the phrase so it's easier to comprehend: 
"serbisyo sa impormasyon sa kalusugan"  has unnecessary prepositions which makes it tricky to understand (in english, Service on information on health)
"Serbisyong Impormasyong pangkalusugan" is a better phrase to convey "health information services"

### Issue 4a: Screen Name: Search Input
English Texts:
"Give Feedback"
Translated Texts:
"Komento"
Suggested Texts:
"Magbigay ng komento"
Rationale:
"Komento" just means comment. Translating "Give Feedback" yields "Magbigay ng komento"

### Issue 4b: Screen Name: Search Input
English Texts:
"Search is currently in beta and only available in English. For support in other languages, please call BC211"
Translated Texts:
"Search" ay kasalukuyang sa Ingles lamang tumawag sa BC211
Suggested Texts:
"Search" ay kasalukuyang sa Ingles lamang. Tumawag sa BC211 para sa ibang suporta.
Rationale:
Missing punctuation. Added a phrase to indicate support.

### Issue 7: Screen Name: Service Detail
English Texts:
1.  Service

Translated Texts:
1. Mga Serbisyo

Suggested Texts:
1. Serbisyo

Rationale:
"Mga" indicates plurality.
"Mga Serbisyo" = Services
"Serbisyo" = Service

### Issue 8a: Screen Name: What's New
English Texts:
"What's New"
Translated Texts:
"Ano'ng bago"
Suggested Texts:
"Anong bago"
Rationale:
Punctuation is unnecessary and "anong" is a valid word.

### Issue 8b: Screen Name: What's New
English Texts:
"Search is available in English"
Translated Texts:
"Magagamit ng paghahanap sa Tagalog"
Suggested Texts:
"Maaaring maghanap sa Tagalog"
Rationale:
"Magagamit" means "to be used". "Maaaring" is a better tagalog term for "available"

**Comment by niko-pg** [comment]
Search Error - No Results - PASS
Search Results - Show More - PASS

**Comment by jparlina** [comment]
@niko-pg: some questions for clarification: 

**- Issue 4b:** 
The texts "Search is currently in beta and only available in English. For support in other languages, please call BC211" are actually 2 separate strings in the backend:
_**String 1:**_ "Search is currently in beta and only available in English. For support in other languages, please"
**_String 2_**: "call bc211" (with embedded phone number so users can just click to call the number on their mobile device)
How would you translate each into Tagalog then? 

**- Issue 8b:** The keyword search function is not available in Tagalog, so should the suggested texts be: "Maaaring maghanap sa Ingles" then?

**Comment by niko-pg** [comment]
@jparlina 

Thanks for the clarification on  **Issue 4b**:
If these two strings are separated, a better tagalog translation would be:

String 1: "Search" ay kasalukuyang sa Ingles lamang. Kung nais ng suporta sa ibang wika,
String 2: "tumawag sa bc211"

For **Issue 8b**:
Yes, that should be Ingles. Great catch! Thanks for fixing

**Comment by jparlina** [comment]
Awesome! Thanks for looking into those @niko-pg!

**Comment by jparlina** [comment]
Uploaded [csv](https://docs.google.com/spreadsheets/d/15nBan7mQjk8OVof_-4XU7_TrSN62Z3EWwokqZvxAJIE/edit#gid=0) of edits to weblate for Issues 1a, 1b, 2, 3, 4a, 4b, 7. 
Edited strings directly on weblate: Issues 8a and 8b. 

@jparlina to review edits after the next staging release.

**Comment by jparlina** [comment]
Tested on Staging V1.29.0 Server V1.3.28 on iPhone 7 Plus:

**Issues 1a and 1b** - PASS
![Screen Shot 2020-04-21 at 5 26 53 PM](https://user-images.githubusercontent.com/48343061/79927730-80d6ac00-83f5-11ea-8cdf-3412f29cd09a.png)

**Issue 2** - PASS
![Screen Shot 2020-04-21 at 5 30 00 PM](https://user-images.githubusercontent.com/48343061/79927816-ca26fb80-83f5-11ea-93fa-a8054494c309.png)

**Issue 3** - PASS
![Screen Shot 2020-04-21 at 5 31 13 PM](https://user-images.githubusercontent.com/48343061/79927882-05c1c580-83f6-11ea-9dab-f06aaae3fda3.png)

**Issues 4a and 4b** - PASS
![Screen Shot 2020-04-21 at 5 32 31 PM](https://user-images.githubusercontent.com/48343061/79927979-5c2f0400-83f6-11ea-985a-a83980a19d79.png)

**Issue 7** - PASS
![Screen Shot 2020-04-21 at 5 36 11 PM](https://user-images.githubusercontent.com/48343061/79928073-aca66180-83f6-11ea-8564-6453512cc5bd.png)

**Comment by jparlina** [comment]
Pending QA: issues 8a and 8b "What's New"

**Comment by tomy-pg** [comment]
@jparlina can this be closed?

**Comment by tomy-pg** [comment]
8a. See comment regarding consistency [here](https://github.com/pg-irc/arrival-advisor-qa/issues/87#issuecomment-673615476) - 
8b. See [screenshot](https://drive.google.com/drive/folders/1dXzs4ztnGY4bZbq6gxKyTgDbzXMDMEcY) with fixed translation
