### ISSUE TITLE
Arabic QA - Apr 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#54]
See screenshots [here](https://drive.google.com/file/d/11o3ys4lQ_B0c3Dc2MwthsRxJYzQpDscM/view?usp=sharing)

**Comment by hhaboh** [comment]
1. Onboarding 1: PASS
2. Onboarding 2: PASS
3. Onboarding 3: PASS
4. Onboarding 4: PASS
5. My Bookmarks - No Topics: PASS
6. My Bookmarks - No Services: PASS
7. Search Error - Invalid Location: PASS
