### ISSUE TITLE
Chinese Simplified QA - Apr 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#56]
### 1. Onboarding 1 
<img width="403" alt="Screen Shot 2020-04-05 at 5 47 17 PM" src="https://user-images.githubusercontent.com/48343061/78514363-c47ab600-7765-11ea-85be-bfe9a3d995e7.png">

### 2. Onboarding 2 
<img width="402" alt="Screen Shot 2020-04-05 at 5 49 44 PM" src="https://user-images.githubusercontent.com/48343061/78514423-1f141200-7766-11ea-93e0-6c2ceafdbd6b.png">

### 3. Onboarding 3 
<img width="400" alt="Screen Shot 2020-04-05 at 6 14 24 PM" src="https://user-images.githubusercontent.com/48343061/78515104-7962a200-7769-11ea-9db2-ca16f5d692ac.png">

### 4. Onboarding 4 
_(note: the button at the bottom of the screen should say "**_Start_**" unlike the previous 3 screens)_

<img width="400" alt="Screen Shot 2020-04-05 at 6 16 23 PM" src="https://user-images.githubusercontent.com/48343061/78515343-62707f80-776a-11ea-9a05-e2c740b5ab07.png">

### 5. My Bookmarks - No Topics 
![Screen Shot 2020-04-05 at 6 23 22 PM](https://user-images.githubusercontent.com/48343061/78515388-9b105900-776a-11ea-8c61-a44901a87476.png)

### 6. My Bookmarks - No Services 
![Screen Shot 2020-04-05 at 6 24 17 PM](https://user-images.githubusercontent.com/48343061/78515426-baa78180-776a-11ea-8c23-4d07b655fc3d.png)

### 7. Search Error - Invalid Location
<img width="439" alt="Screen Shot 2020-04-05 at 9 52 32 PM" src="https://user-images.githubusercontent.com/48343061/78524515-0bc66e00-7789-11ea-8fd3-04af7b33bf3a.png">

**Comment by ian-lin-PG** [comment]
1. Onboarding 1 - PASS
2. Onboarding 2 - PASS
3. Onboarding 3 - PASS
4. Onboarding 4 - PASS
5. My Bookmarks - No Topics - PASS
6. My Bookmarks - No Services - FAIL
7. Search Error - Invalid Location - PASS

**Comment by ian-lin-PG** [comment]
Screen Name: My Bookmarks - No Services - FAIL
English Texts: `No services to show`
Current Texts: `无法显示所需服务`
Suggested Texts:`没有可显示的服务`
Rationale: The old translation translate to `Cannot show required services` which feels more like an error screen. I elected to follow the format of the translation for  `No topics to show` from screen 6. Most of the translation are the same as screen 6 except the last 2 characters are changed from 主题 (topics), to (服务)services.

**Comment by jparlina** [comment]
Fixed on weblate. Need to QA once revisions are released to staging.

**Comment by jparlina** [comment]
Revised on Staging V1.27.0 Server V1.3.26. 
@ian-lin-PG - please QA the revised string in the red box. Thank you.

![Screen Shot 2020-04-09 at 6 04 19 PM](https://user-images.githubusercontent.com/48343061/78953111-93172880-7a8c-11ea-822d-d163c9a957a1.png)

**Comment by ian-lin-PG** [comment]
PASS.
