### ISSUE TITLE
Chinese Traditional QA - Apr 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#57]
### 1. Onboarding 1
<img width="404" alt="Screen Shot 2020-04-05 at 6 30 09 PM" src="https://user-images.githubusercontent.com/48343061/78515728-c21b5a80-776b-11ea-9028-71f516e6d7e8.png">

### 2. Onboarding 2
<img width="411" alt="Screen Shot 2020-04-05 at 6 32 41 PM" src="https://user-images.githubusercontent.com/48343061/78515781-03136f00-776c-11ea-99c7-aa79f67c072f.png">

### 3. Onboarding 3
<img width="410" alt="Screen Shot 2020-04-05 at 6 34 46 PM" src="https://user-images.githubusercontent.com/48343061/78515844-4d94eb80-776c-11ea-97be-04f569103047.png">

### 4. Onboarding 4
_(note: the button at the bottom of the screen should say "Start" unlike the previous 3 screens)_
<img width="410" alt="Screen Shot 2020-04-05 at 6 36 21 PM" src="https://user-images.githubusercontent.com/48343061/78515967-b0868280-776c-11ea-9c1c-23f3ba71bf42.png">

### 5. My Bookmarks - No Topics
![Screen Shot 2020-04-05 at 6 25 37 PM](https://user-images.githubusercontent.com/48343061/78515608-49b49980-776b-11ea-9ba8-712395c6fc06.png)

### 6. My Bookmarks - No Services
![Screen Shot 2020-04-05 at 6 25 45 PM](https://user-images.githubusercontent.com/48343061/78515625-5e912d00-776b-11ea-9f08-8e7f786b98cb.png)

### 7. Search Error - Invalid Location
<img width="441" alt="Screen Shot 2020-04-05 at 9 52 52 PM" src="https://user-images.githubusercontent.com/48343061/78524561-2bf62d00-7789-11ea-9498-499198869946.png">

**Comment by ian-lin-PG** [comment]
1. Onboarding 1 - PASS
2. Onboarding 2 - PASS
3. Onboarding 3 - PASS
4. Onboarding 4 - PASS
5. My Bookmarks - No Topics - PASS
6. My Bookmarks - No Services - FAIL
7. Search Error - Invalid Location - PASS

**Comment by ian-lin-PG** [comment]
Screen Name: My Bookmarks - No Services - FAIL
English Texts: `No services to show`
Current Texts: `無網路服務顯示`
Suggested Texts:`沒有可顯示的服務`
Rationale: The old translation translates to `No internet services to show` which contains `internet`. I elected to follow the format of the translation for  `No topics to show` from screen 6. Most of the translation are the same as screen 6 except the last 2 characters are changed from 主题 (topics), to (服务)services. Similar change is suggested in simplified Chinese. Both versions had different translation of `No services to show` that were inconsistent with `No topics to show`.

**Comment by jparlina** [comment]
Fixed on weblate. Need to QA once revisions are released to staging.

**Comment by jparlina** [comment]
Revised on Staging V1.27.0 Server V1.3.26. 
@ian-lin-PG - please QA the revised string in the red box. Thank you.

![Screen Shot 2020-04-09 at 6 02 16 PM](https://user-images.githubusercontent.com/48343061/78953013-51867d80-7a8c-11ea-92c2-594069ab379d.png)

**Comment by ian-lin-PG** [comment]
PASS.
