### ISSUE TITLE
French QA - Apr 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#58]
### 1. Onboarding 1
<img width="408" alt="Screen Shot 2020-04-05 at 6 40 47 PM" src="https://user-images.githubusercontent.com/48343061/78516243-bfba0000-776d-11ea-85bf-9d9f1d153295.png">

### 2. Onboarding 2
<img width="411" alt="Screen Shot 2020-04-05 at 6 47 01 PM" src="https://user-images.githubusercontent.com/48343061/78516337-014aab00-776e-11ea-91d1-f03c24c170da.png">

### 3. Onboarding 3
<img width="411" alt="Screen Shot 2020-04-05 at 6 48 51 PM" src="https://user-images.githubusercontent.com/48343061/78516416-5090db80-776e-11ea-8d09-46c7432ae67c.png">

### 4. Onboarding 4
_(note: the button at the bottom of the screen should say "Start" unlike the previous 3 screens)_
<img width="409" alt="Screen Shot 2020-04-05 at 6 50 52 PM" src="https://user-images.githubusercontent.com/48343061/78516469-83d36a80-776e-11ea-84e4-db5bafdf1662.png">

### 5. My Bookmarks - No Topics
<img width="451" alt="Screen Shot 2020-04-05 at 7 20 04 PM" src="https://user-images.githubusercontent.com/48343061/78517570-98b1fd00-7772-11ea-8385-d5a8563b5042.png">

### 6. My Bookmarks - No Services
<img width="442" alt="Screen Shot 2020-04-05 at 7 20 37 PM" src="https://user-images.githubusercontent.com/48343061/78517576-9d76b100-7772-11ea-84f8-e639ce135c0a.png">

### 7. Search Error - Invalid Location
<img width="439" alt="Screen Shot 2020-04-05 at 9 50 53 PM" src="https://user-images.githubusercontent.com/48343061/78524435-ce61e080-7788-11ea-857b-cd229051c5a1.png">

**Comment by ludivinegh** [comment]
Screen Name: 1. Onboarding 1
English Texts: Skip
Current Texts: Ignorer la question
Suggested Texts: Ignorer
Rationale: The current string doesn't work in context, as it reads "Skip the question".

**Comment by ludivinegh** [comment]
Screen Name: 1. Onboarding 1
English Texts: Next
Current Texts: Prochaine question
Suggested Texts: Suivant
Rationale: The current string doesn't work in context, as it reads "Next question".

**Comment by ludivinegh** [comment]
Screen Name: 1. Onboarding 2
English Texts: Skip
Current Texts: Ignorer la question
Suggested Texts: Ignorer
Rationale: The current string doesn't work in context, as it reads "Skip the question".

**Comment by ludivinegh** [comment]
Screen Name: 1. Onboarding 2
English Texts: Next
Current Texts: Prochaine question
Suggested Texts: Suivant
Rationale: The current string doesn't work in context, as it reads "Next question".

**Comment by ludivinegh** [comment]
Screen Name: Onboarding 2
English Texts: Bookmark the topics that you find helpful for future use.
Current Texts: Ajoutez à vos favoris les sujets qui vous sont utiles, et consultez-les plus tard.
Suggested Texts: Ajoutez les sujets qui vous sont utiles à vos favoris et consultez-les plus tard.
Rationale: The current translation is not ungrammatical, but sounds a bit unnatural. The comma can also be omitted.

**Comment by ludivinegh** [comment]
Screen Name: 1. Onboarding 3
English Texts: Skip
Current Texts: Ignorer la question
Suggested Texts: Ignorer
Rationale: The current string doesn't work in context, as it reads "Skip the question".

**Comment by ludivinegh** [comment]
Screen Name: 1. Onboarding 3
English Texts: Next
Current Texts: Prochaine question
Suggested Texts: Suivant
Rationale: The current string doesn't work in context, as it reads "Next question".

**Comment by ludivinegh** [comment]
Screen Name: 1. Onboarding 4
English Texts: Skip
Current Texts: Ignorer la question
Suggested Texts: Ignorer
Rationale: The current string doesn't work in context, as it reads "Skip the question".

**Comment by ludivinegh** [comment]
Screen Name: 6. My Bookmarks - No Services
English Texts: No services to show
Current Texts: Pas de services à proposer
Suggested Texts: Aucun service à proposer
Rationale: The current translation is correct, but it is inconsistent with a similar string ("No topics to show") used on 5. My Bookmarks - No Topics. I believe both translations should be consistent for stylistic reasons.

**Comment by ludivinegh** [comment]
5. My Bookmarks - No Topics - PASS

**Comment by jparlina** [comment]
Fixed on weblate. Need to QA once revisions are released to staging.

**Comment by jparlina** [comment]
Revised on Staging V1.27.0 Server V1.3.26. - all PASS
![Screen Shot 2020-04-09 at 6 12 30 PM](https://user-images.githubusercontent.com/48343061/78954055-c0b1a100-7a8f-11ea-8dca-1756a5450145.png)

![Screen Shot 2020-04-09 at 6 15 11 PM](https://user-images.githubusercontent.com/48343061/78954061-c4ddbe80-7a8f-11ea-8fe4-ba61baedcd29.png)

![Screen Shot 2020-04-09 at 6 16 24 PM](https://user-images.githubusercontent.com/48343061/78954064-c7401880-7a8f-11ea-95f5-ad5c646a7c08.png)

![Screen Shot 2020-04-09 at 6 25 46 PM](https://user-images.githubusercontent.com/48343061/78954067-ca3b0900-7a8f-11ea-8676-2ff64043c7fb.png)

![Screen Shot 2020-04-09 at 6 28 13 PM](https://user-images.githubusercontent.com/48343061/78954107-e9d23180-7a8f-11ea-9ee0-8ff7e3ccc5a2.png)
