### ISSUE TITLE
Korean QA - Apr 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#59]
### 1. Onboarding 1
<img width="407" alt="Screen Shot 2020-04-05 at 7 34 29 PM" src="https://user-images.githubusercontent.com/48343061/78518207-ae282680-7774-11ea-9b1b-6bd04df1d385.png">

### 2. Onboarding 2
<img width="409" alt="Screen Shot 2020-04-05 at 7 36 34 PM" src="https://user-images.githubusercontent.com/48343061/78518286-edef0e00-7774-11ea-9193-c6a7e5a19ed4.png">

### 3. Onboarding 3
<img width="407" alt="Screen Shot 2020-04-05 at 7 38 37 PM" src="https://user-images.githubusercontent.com/48343061/78518387-34dd0380-7775-11ea-92b0-b6da3c673c5c.png">

### 4. Onboarding 4
_(note: the button at the bottom of the screen should say "Start" unlike the previous 3 screens)_
<img width="408" alt="Screen Shot 2020-04-05 at 7 40 07 PM" src="https://user-images.githubusercontent.com/48343061/78518473-6ce44680-7775-11ea-8e44-5cb81ba00338.png">

### 5. My Bookmarks - No Topics
<img width="445" alt="Screen Shot 2020-04-05 at 7 42 34 PM" src="https://user-images.githubusercontent.com/48343061/78518558-a7e67a00-7775-11ea-9adf-6590173633f8.png">

### 6. My Bookmarks - No Services
<img width="449" alt="Screen Shot 2020-04-05 at 7 43 13 PM" src="https://user-images.githubusercontent.com/48343061/78518586-bfbdfe00-7775-11ea-829e-725f6ec0cf4f.png">

### 7. Search Error - Invalid Location
<img width="443" alt="Screen Shot 2020-04-05 at 9 51 18 PM" src="https://user-images.githubusercontent.com/48343061/78524783-e0904e80-7789-11ea-8b57-3fc2a1cc7961.png">

**Comment by rankanglee** [comment]
ALL PASS.
