### ISSUE TITLE
Punjabi QA - Apr 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#60]
### 1. Onboarding 1
<img width="400" alt="Screen Shot 2020-04-05 at 9 25 17 PM" src="https://user-images.githubusercontent.com/48343061/78522989-2518eb80-7784-11ea-9a89-66fca8241ee9.png">

### 2. Onboarding 2
<img width="403" alt="Screen Shot 2020-04-05 at 9 27 11 PM" src="https://user-images.githubusercontent.com/48343061/78523056-68735a00-7784-11ea-822f-6c8304e33213.png">

### 3. Onboarding 3
<img width="401" alt="Screen Shot 2020-04-05 at 9 29 18 PM" src="https://user-images.githubusercontent.com/48343061/78523151-aec8b900-7784-11ea-8786-efab0b72ecda.png">

### 4. Onboarding 4
_(note: the button at the bottom of the screen should say "_**Start**_" unlike the previous 3 screens)_

<img width="401" alt="Screen Shot 2020-04-05 at 9 30 59 PM" src="https://user-images.githubusercontent.com/48343061/78523220-e5063880-7784-11ea-848d-fcc8066e7034.png">

### 5. My Bookmarks - No Topics
<img width="450" alt="Screen Shot 2020-04-05 at 9 32 48 PM" src="https://user-images.githubusercontent.com/48343061/78523311-24348980-7785-11ea-8392-87aec211c7ff.png">

### 6. My Bookmarks - No Services
<img width="440" alt="Screen Shot 2020-04-05 at 9 33 24 PM" src="https://user-images.githubusercontent.com/48343061/78523315-28f93d80-7785-11ea-93d9-6d8af9751366.png">

### 7. Search Error - Invalid Location
<img width="440" alt="Screen Shot 2020-04-05 at 9 51 40 PM" src="https://user-images.githubusercontent.com/48343061/78524847-0f0e2980-778a-11ea-8f8b-50144ee815fb.png">

**Comment by aalam** [comment]
1. Onboarding 1 - PASSED

    2. Onboarding 2 - PASSED

    3. Onboarding 3 - PASSED

    4. Onboarding 4 - PASSED

    5. My Bookmarks - PASSED

    6. My Bookmarks  - PASSED

    7. Search Error - Invalid Location - PASSED
