### ISSUE TITLE
Tagalog QA - Apr 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#61]
### 1. Onboarding 1
<img width="410" alt="Screen Shot 2020-04-05 at 10 14 29 PM" src="https://user-images.githubusercontent.com/48343061/78525105-079b5000-778b-11ea-9fd7-e2fd03ad2856.png">

### 2. Onboarding 2
<img width="406" alt="Screen Shot 2020-04-05 at 10 16 15 PM" src="https://user-images.githubusercontent.com/48343061/78525167-36b1c180-778b-11ea-91db-2581d25cf24b.png">

### 3. Onboarding 3
<img width="401" alt="Screen Shot 2020-04-05 at 10 17 40 PM" src="https://user-images.githubusercontent.com/48343061/78525227-6cef4100-778b-11ea-88fe-d6e94debf461.png">

### 4. Onboarding 4
_(note: the button at the bottom of the screen should say "Start" unlike the previous 3 screens)_

<img width="408" alt="Screen Shot 2020-04-05 at 10 19 06 PM" src="https://user-images.githubusercontent.com/48343061/78525317-a6c04780-778b-11ea-990b-4a5803f9d675.png">

### 5. My Bookmarks - No Topics
<img width="439" alt="Screen Shot 2020-04-05 at 10 20 48 PM" src="https://user-images.githubusercontent.com/48343061/78525364-c6577000-778b-11ea-9101-7d96d6ec3e0a.png">

### 6. My Bookmarks - No Services
<img width="429" alt="Screen Shot 2020-04-05 at 10 21 33 PM" src="https://user-images.githubusercontent.com/48343061/78525393-e0914e00-778b-11ea-8602-fbd14ac28e2c.png">

### 7. Search Error - Invalid Location 
<img width="442" alt="Screen Shot 2020-04-05 at 10 23 50 PM" src="https://user-images.githubusercontent.com/48343061/78525493-2b12ca80-778c-11ea-8b38-4a46ff0e53a6.png">

**Comment by niko-pg** [comment]
**Screen Name**: Onboarding 1
**English Texts:** 

1.  Skip 
2.  Welcome to Arrival Advisor
3.  Your go-to-guide to getting settled in your community.
4.  Next

**Current Texts:**

1. Laktawan 
2. Welcome to Arrival Advisor 
3. "Gabay" sa pagsisimulang paninirahan sa inyong bagong komunidad
4. Susunod

**Suggested Texts:**
4. Tuloy 
**Rationale**
Susunod is not a good use as it means "coming up" in English. A better translation is "Tuloy"

**Screen Name**: Onboarding 2
**English Texts:** 

1. Skip 
2. Bookmark the topics that you find helpful for future use
3. Next

**Current Texts:**

1. Laktawan 
2. Markahan ang mga paksa na sa wari mo ay makakatulong sa iyo sa susunod
3. Susunod

**Suggested Texts:**
2. I-bookmark ang mga paksa na sa wari mo ay makakatulong sa iyo sa susunod
4. Tuloy 
**Rationale**
2. Markahan just means "mark" in english. There's no direct translation for bookmark in Tagalog so I think it's okay to use "bookmark". Adding "I-" as in "I-bookmark" is a valid filipino prefix to indicate an imperative mood.
4. Susunod is not a good use as it means "coming up" in English. A better translation is "Tuloy"

**Screen Name**: Onboarding 3
**English Texts:** 

1. Skip 
2. Find service providers near you that can help you through your settlement journey
3. Next

**Current Texts:**

1. Laktawan 
2. Humanap ng mga service provider malapit sa iyo na makakatulong sa iyo hanggang sa matutuluyan mo sa paglalakbay
3. Susunod

**Suggested Texts:**
2. Humanap ng mga service provider malapit sa iyo na makakatulong sa iyong panibagong pakikipagsapalaran
4.Tuloy 
**Rationale**
2. The current tagalog translation doesn't make sense and ends up changing the context. "paninibagong pakikipagsapalarn" is a better translation for settlement journey.
4.  Susunod is not a good use as it means "coming up" in English. A better translation is "Tuloy"

**Screen Name**: Search Error - Invalid Location
**English Texts:** 

1. Invalid location. Try:

**Current Texts:**

1. Hindi wasto lokasyon: Subukan:

**Suggested Texts:**

1. Maling lokasyon. Subukan:

**Rationale**

1. Translation is wrong and is not a valid sentence in Filipino.

**Comment by niko-pg** [comment]
Onboarding 4 = PASS
My Bookmarks - No Topics = PASS
My Bookmarks - No Services = PASS

**Comment by jparlina** [comment]
Fixed on weblate. Need to QA once revisions are released to staging.

**Comment by jparlina** [comment]
Revised on Staging V1.27.0 Server V1.3.26. - all PASS

![Screen Shot 2020-04-09 at 6 34 18 PM](https://user-images.githubusercontent.com/48343061/78954845-3585da80-7a92-11ea-8843-b6b62bfe005d.png)

![Screen Shot 2020-04-09 at 6 37 00 PM](https://user-images.githubusercontent.com/48343061/78954848-39b1f800-7a92-11ea-8269-866438b0bd35.png)

![Screen Shot 2020-04-09 at 6 38 47 PM](https://user-images.githubusercontent.com/48343061/78954853-3cace880-7a92-11ea-941c-02d15c334690.png)

![Screen Shot 2020-04-09 at 6 42 38 PM](https://user-images.githubusercontent.com/48343061/78954858-40406f80-7a92-11ea-8320-b0ec9c626b97.png)
