### ISSUE TITLE
English Reference for Additional Translations - Apr 9, 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#63]
### Translation 1: Onboarding - Add Bookmark Services
**Current text:** Bookmark the topics that you find helpful for future use.
**Revised text to translate**: Bookmark the topics `and services` that you find helpful for future use.

_Note: Adding `and services` since the next release will include "service bookmark" feature._ 

![Screen Shot 2020-04-10 at 4 31 40 PM](https://user-images.githubusercontent.com/48343061/79029349-dfc03980-7b48-11ea-9826-cd173b079761.png)

### Translation 2: "near My Location"
![Screen Shot 2020-04-10 at 4 28 14 PM](https://user-images.githubusercontent.com/48343061/79029231-61fc2e00-7b48-11ea-8d0c-c3035f012f0a.png)

### Translation 3: "near"
![Screen Shot 2020-04-10 at 4 29 14 PM](https://user-images.githubusercontent.com/48343061/79029266-7f30fc80-7b48-11ea-8029-95552c9b43d8.png)

**Comment by rasmus-storjohann-PG** [comment]
This story was used to help translators, no work to do on them, closing.
