### ISSUE TITLE
Arabic QA - Apr 10, 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#65]
See screenshots [here](https://drive.google.com/file/d/1r57QOV0W4wafR8Hwbi2QNaq0PPXkYFNI/view?usp=sharing)

**Comment by hhaboh** [comment]
1. App Store Screenshot 1: PASS
2. App Store Screenshot 2: PASS
3. App Store Screenshot 3: PASS
4. App Store Screenshot 4: PASS
5. App Store Screenshot 5: PASS
6. App Store Screenshot 6: PASS
7. App Store Screenshot 7: PASS
8. App Store Screenshot 8: PASS

9. What’s New: FAIL (text is not updated)

English text: Thanks for using Arrival Advisor! We've made updates and improvements to make your experience even better.
Current texts: شكرا لك على استخدام تطبيق Arrival Advisor!
Suggested texts: شكرا لك على استخدام تطبيق Arrival Advisor! لقد أجرينا بعض التحديثات والتحسينات كي نجعل من خبرة استخدامك للتطبيق أفضل من ذي قبل.
Rationale: The second sentence was missing.

English texts: You can now search for services! Search is available in English.
Current texts: يمكنك الآن البحث عن الخدمات!
Suggested texts: يمكنك الآن البحث عن الخدمات! البحث متوفر باللغة الإنكليزية.
Rationale: Second sentence was missing.

10. Search is in Beta: PASS
11. Service Detail: PASS

**Comment by jparlina** [comment]
@tomy-pg There are strings not showing up on the What's New screen although the translations are already on weblate. 

![Screen Shot 2020-04-14 at 2 50 44 PM](https://user-images.githubusercontent.com/48343061/79279909-ef4ec380-7e63-11ea-99b5-96c00ff399e0.png)

**Comment by tomy-pg** [comment]
Thank you for pointing this out. This has now been addressed (see screenshot below)
![Screenshot_20200414-153400_Google Play Store](https://user-images.githubusercontent.com/47794846/79280574-8700e180-7e65-11ea-9a7b-7fe3d9bb73fb.jpg)

**Comment by jparlina** [comment]
@hhaboh Please review the updated screenshot [here](https://drive.google.com/file/d/19hPCWWOYGxDIVxDLE5LTVF-smWaV2LtF/view?usp=sharing) (in case you can't see the above image here on GitHub). Thank you.

**Comment by hhaboh** [comment]
PASS
