### ISSUE TITLE
Chinese Simplified QA - Apr 10, 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#67]
### 1. App Store Screenshot 1
![Screen Shot 2020-04-10 at 3 55 43 PM](https://user-images.githubusercontent.com/48343061/79028126-c5379180-7b43-11ea-848e-3f02023845fd.png)

### 2. App Store Screenshot 2 
![Screen Shot 2020-04-10 at 3 56 09 PM](https://user-images.githubusercontent.com/48343061/79028152-d41e4400-7b43-11ea-8e26-deb8af98d4b8.png)

### 3. App Store Screenshot 3 
![Screen Shot 2020-04-10 at 3 56 36 PM](https://user-images.githubusercontent.com/48343061/79028167-df716f80-7b43-11ea-81dd-10c46849e5df.png)

### 4. App Store Screenshot 4 
![Screen Shot 2020-04-10 at 3 56 54 PM](https://user-images.githubusercontent.com/48343061/79028183-ee582200-7b43-11ea-88aa-9630de05278a.png)

### 5. App Store Screenshot 5
![Screen Shot 2020-04-10 at 3 57 16 PM](https://user-images.githubusercontent.com/48343061/79028197-f748f380-7b43-11ea-8b5f-859e46cf12b3.png)

### 6. App Store Screenshot 6 
![Screen Shot 2020-04-10 at 3 57 32 PM](https://user-images.githubusercontent.com/48343061/79028216-05970f80-7b44-11ea-81d8-e9c138457732.png)

### 7. App Store Screenshot 7 
_Note: QA only the texts in the red box at the bottom of the screen_

![Screen Shot 2020-04-10 at 3 58 00 PM](https://user-images.githubusercontent.com/48343061/79028240-1a73a300-7b44-11ea-9638-a5dd04063dd2.png)

### 8. App Store Screenshot 8
![Screen Shot 2020-04-10 at 3 58 40 PM](https://user-images.githubusercontent.com/48343061/79028254-295a5580-7b44-11ea-91a5-7453353a5d9b.png)

### 9. What's New
<img width="319" alt="Screen Shot 2020-04-13 at 12 34 50 PM" src="https://user-images.githubusercontent.com/48343061/79153742-3022db80-7d83-11ea-8b62-610330db869a.png">
### 10. Search is in Beta
![Screen Shot 2020-04-10 at 3 59 14 PM](https://user-images.githubusercontent.com/48343061/79028285-442cca00-7b44-11ea-86de-2ba410f66db5.png)

### 11. Service Detail
![Screen Shot 2020-04-10 at 5 34 24 PM](https://user-images.githubusercontent.com/48343061/79031208-046cdf00-7b52-11ea-9e35-177550d79965.png)

**Comment by ian-lin-PG** [comment]
1. App Store Screenshot 1 - PASS
2. App Store Screenshot 2 - PASS
3. App Store Screenshot 3 - PASS
4. App Store Screenshot 4 - PASS
5. App Store Screenshot 5 - PASS
6. App Store Screenshot 6 - PASS
7. App Store Screenshot 7 - PASS
8. App Store Screenshot 8 - PASS
9. What's New - FAILED
10. Search is in Beta - PASS

**Comment by ian-lin-PG** [comment]
Screen Name: What's new
Problem: It's in Korean.

**Comment by jparlina** [comment]
@ian-lin-PG "What's New" screen has been corrected. Please review. Thank you.

**Comment by ian-lin-PG** [comment]
9. What's New - PASS
