### ISSUE TITLE
Chinese Traditional QA - Apr 10, 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#68]
### 1. App Store Screenshot 1
![Screen Shot 2020-04-10 at 4 02 28 PM](https://user-images.githubusercontent.com/48343061/79028404-b69daa00-7b44-11ea-94bd-3670fc558a4f.png)

### 2. App Store Screenshot 2 
![Screen Shot 2020-04-10 at 4 02 53 PM](https://user-images.githubusercontent.com/48343061/79028416-c4532f80-7b44-11ea-9121-a493766e91ca.png)

### 3. App Store Screenshot 3 
![Screen Shot 2020-04-10 at 4 03 16 PM](https://user-images.githubusercontent.com/48343061/79028424-ce752e00-7b44-11ea-8b0a-86656bec4b67.png)

### 4. App Store Screenshot 4 
![Screen Shot 2020-04-10 at 4 03 32 PM](https://user-images.githubusercontent.com/48343061/79028444-de8d0d80-7b44-11ea-96c7-ae63cededc55.png)

### 5. App Store Screenshot 5
![Screen Shot 2020-04-10 at 4 04 01 PM](https://user-images.githubusercontent.com/48343061/79028457-e8af0c00-7b44-11ea-8aeb-1dfd55c1a4b4.png)

### 6. App Store Screenshot 6 
![Screen Shot 2020-04-10 at 4 04 16 PM](https://user-images.githubusercontent.com/48343061/79028478-f6fd2800-7b44-11ea-8b7e-c1cf4f164ce0.png)

### 7. App Store Screenshot 7 
_Note: QA only the texts in the red box at the bottom of the screen_

![Screen Shot 2020-04-10 at 4 04 44 PM](https://user-images.githubusercontent.com/48343061/79028505-172ce700-7b45-11ea-9a15-304333eaaccc.png)

### 8. App Store Screenshot 8
![Screen Shot 2020-04-10 at 4 05 36 PM](https://user-images.githubusercontent.com/48343061/79028516-20b64f00-7b45-11ea-8eff-0b2c6cd8a4ca.png)

### 9. What's New
![Screen Shot 2020-04-10 at 4 05 58 PM](https://user-images.githubusercontent.com/48343061/79028533-2e6bd480-7b45-11ea-81dd-6b38fb02f16f.png)

### 10. Search is in Beta
![Screen Shot 2020-04-10 at 4 06 16 PM](https://user-images.githubusercontent.com/48343061/79028553-42173b00-7b45-11ea-9aa6-316409df2a10.png)

### 11. Service Detail
![Screen Shot 2020-04-10 at 5 39 38 PM](https://user-images.githubusercontent.com/48343061/79031279-9379f700-7b52-11ea-8924-4d9c79df55d5.png)

**Comment by ian-lin-PG** [comment]
1. App Store Screenshot 1 - PASS
2. App Store Screenshot 2 - PASS
3. App Store Screenshot 3 - PASS
4. App Store Screenshot 4 - PASS
5. App Store Screenshot 5 - PASS
6. App Store Screenshot 6 - PASS
7. App Store Screenshot 7 - PASS
8. App Store Screenshot 8 - PASS
9. What's New - PASS
10. Search is in Beta - PASS
