### ISSUE TITLE
French QA: Apr 10, 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#69]
### 1. App Store Screenshot 1
![Screen Shot 2020-04-10 at 3 21 15 PM](https://user-images.githubusercontent.com/48343061/79026832-ef3a8500-7b3e-11ea-85ea-5401ac30174d.png)

### 2. App Store Screenshot 2 
![Screen Shot 2020-04-10 at 3 21 37 PM](https://user-images.githubusercontent.com/48343061/79026881-0d07ea00-7b3f-11ea-8b72-7ef16e9ec8e1.png)

### 3. App Store Screenshot 3 
![Screen Shot 2020-04-10 at 3 22 25 PM](https://user-images.githubusercontent.com/48343061/79026903-18f3ac00-7b3f-11ea-9d48-4ca72cf30f2e.png)

### 4. App Store Screenshot 4 
![Screen Shot 2020-04-10 at 3 22 46 PM](https://user-images.githubusercontent.com/48343061/79026933-2dd03f80-7b3f-11ea-968b-c4086d79f580.png)

### 5. App Store Screenshot 5
![Screen Shot 2020-04-10 at 3 23 25 PM](https://user-images.githubusercontent.com/48343061/79026951-404a7900-7b3f-11ea-87dc-b5ba85cabf9a.png)

### 6. App Store Screenshot 6 
![Screen Shot 2020-04-10 at 3 23 48 PM](https://user-images.githubusercontent.com/48343061/79026965-50faef00-7b3f-11ea-8504-1773c3188e3f.png)

### 7. App Store Screenshot 7 
_Note: QA only the texts in the red box at the bottom of the screen_

![Screen Shot 2020-04-10 at 3 24 47 PM](https://user-images.githubusercontent.com/48343061/79027043-9ddec580-7b3f-11ea-9a7e-9e30161ad266.png)

### 8. App Store Screenshot 8
![Screen Shot 2020-04-10 at 3 26 33 PM](https://user-images.githubusercontent.com/48343061/79027059-acc57800-7b3f-11ea-8d61-c6bd295e2cba.png)

### 9. What's New
![Screen Shot 2020-04-10 at 3 28 22 PM](https://user-images.githubusercontent.com/48343061/79027130-ed24f600-7b3f-11ea-8554-000c782c10ef.png)

### 10. Search is in Beta
![Screen Shot 2020-04-10 at 3 28 43 PM](https://user-images.githubusercontent.com/48343061/79027152-0037c600-7b40-11ea-9726-fe1da7d09407.png)

### 11. Service Detail
![Screen Shot 2020-04-10 at 5 04 28 PM](https://user-images.githubusercontent.com/48343061/79030446-e309f400-7b4d-11ea-8184-d5ce80ed321b.png)

**Comment by ludivinegh** [comment]
2. App Store Screenshot 2 - PASS
3. App Store Screenshot 3 - PASS
4. App Store Screenshot 4 - PASS
6. App Store Screenshot 6 - PASS
7. App Store Screenshot 7 - PASS
8. App Store Screenshot 8 - PASS
11. Service Detail - PASS

**Comment by ludivinegh** [comment]
Screen Name: 1. App Store Screenshot 1
English Texts: Powered by
Current Texts: Created by
Suggested Texts: Créée par / Powered by
Rationale: Unless there's a specific reason, the string "Powered by" should either be translated into French or left as in the source, not adapted to another string in English. I think it might be best to use French - note that "created" implies that the app (a feminine noun in French) was created.

**Comment by ludivinegh** [comment]
Screen Name: 5. App Store Screenshot 5
English Texts: 1 OF 10
Current Texts: 1 DE 10
Suggested Texts: 1 SUR 10
Rationale: The string was translated out of context and is currently ungrammatical.

**Comment by ludivinegh** [comment]
Screen Name: 9. What's New
English Texts: What's neuf
Current Texts: Quoi de neuf?
Suggested Texts: Actualités
Rationale: The current translation is correct, but quite informal - a back translation would be "What's up?". I would suggest using "Actualités" (News) instead.

Screen Name: 9. What's New
English Texts: N/A
Current Texts: N/A
Suggested Texts: N/A
Rationale: The text highlighted in yellow here: https://drive.google.com/file/d/1qvSFChX2bkpW9aJQtpplxl_kaXP9TP5e/view?usp=drivesdk doesn't show in French. Unless there is a specific reason, please add the string.

Screen Name: 9. What's New
English Texts: What's new
Current Texts: Quoi de neuf
Suggested Texts: Actualités :
Rationale: For consistency with my previous comment, please update this string as well. If it is OK for the punctuation to differ from the source, please add a colon (preceded by a non-breaking space) in French, as suggested here.

**Comment by ludivinegh** [comment]
Screen Name: 10. Search is in Beta
English Texts: Search is currently in beta and only available in English.
Current Texts: L’outil de recherche est actuellement disponible en version bêta et  seulement en anglais.
Suggested Texts: L’outil de recherche est actuellement disponible en version bêta et seulement en anglais.
Rationale: Please remove the double space between "et" and "seulement".

**Comment by jparlina** [comment]
@ludivinegh Thank you for your thorough review. 

I have some questions to clarify with you:

- Screen 1: we actually created the app, so the English text is correct "Created by" instead of "Powered by". So is "Créé par" the correct translation for "Created by" in this context? 

- Screen 9: we use the same string for both "What's new" at the top of the screen and the one in the middle of the screen above the bullet points. The first one has "?" added at the end for all languages. Does it still make sense to use "Actualités" then since there will be a question mark at the end of the first one? 

- Have you reviewed Screen 11? Any issues?

**Comment by jparlina** [comment]
Reviewed QA results:
- Screen 5: screenshot here was old. The latest screenshot shows the correct translation - i.e. "1 SUR 10". @aron-chen-pg updated the screenshots for Apple App Store [here](https://drive.google.com/file/d/1Zj5p5JdQjfOJIulqAPnnF8b4tpxujcoB/view?usp=sharing) and Play Store [here](https://drive.google.com/file/d/1QqQYX3qVWOB7bHRWg6gz7hA0HtgffoIM/view?usp=sharing). 
- Screen 9 & 10: Fixed on weblate directly. 
@jparlina To review edits after next staging release.

**Comment by ludivinegh** [comment]
> @ludivinegh Thank you for your thorough review.
> 
> I have some questions to clarify with you:
> 
> * Screen 1: we actually created the app, so the English text is correct "Created by" instead of "Powered by". So is "Créé par" the correct translation for "Created by" in this context? [LH] Correct.
> * Screen 9: we use the same string for both "What's new" at the top of the screen and the one in the middle of the screen above the bullet points. The first one has "?" added at the end for all languages. Does it still make sense to use "Actualités" then since there will be a question mark at the end of the first one? [LH] Actually, having "Actualités and a question mark would not work. Would it be possible to omit the question mark in fr_CA? Otherwise, you may use "Quelles sont les actualités?" for instance, but that may be a bit too long.
> * Have you reviewed Screen 11? Any issues? [LH] This was a pass. Sorry, my bad, I forgot to include it in the list.

**Comment by jparlina** [comment]
@ludivinegh Thank you for your quick response on my follow-up questions. 
Regarding the string "What's new", I just learned from our developer that the top one "What's new?" is automatically translated on the App Store so we can't edit. So I'll just edit the second one to "Actualités :" as per your suggestion.

**Comment by jparlina** [comment]
**Screen 10. Search in beta** 
Reviewed on Staging V1.29.0 Server V1.3.28 on iOS - PASS
![Screen Shot 2020-04-21 at 5 05 49 PM](https://user-images.githubusercontent.com/48343061/79926778-a0200a00-83f2-11ea-9e3c-dba43bb5d0ab.png)

**Comment by jparlina** [comment]
Still pending QA - Screen 9 What's New
