### ISSUE TITLE
Korean QA - Apr 10, 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#70]
### 1. App Store Screenshot 1
![Screen Shot 2020-04-10 at 3 31 27 PM](https://user-images.githubusercontent.com/48343061/79027301-87853980-7b40-11ea-99e7-549fa9800e0a.png)

### 2. App Store Screenshot 2 
![Screen Shot 2020-04-10 at 3 32 09 PM](https://user-images.githubusercontent.com/48343061/79027307-8d7b1a80-7b40-11ea-8051-179888a46118.png)

### 3. App Store Screenshot 3 
![Screen Shot 2020-04-10 at 3 33 08 PM](https://user-images.githubusercontent.com/48343061/79027315-979d1900-7b40-11ea-8396-8ead6eef65e7.png)

### 4. App Store Screenshot 4 
![Screen Shot 2020-04-10 at 3 33 36 PM](https://user-images.githubusercontent.com/48343061/79027332-ae437000-7b40-11ea-9c71-0072a81726f7.png)

### 5. App Store Screenshot 5
![Screen Shot 2020-04-10 at 3 34 04 PM](https://user-images.githubusercontent.com/48343061/79027339-b8fe0500-7b40-11ea-9031-0e53fe1e5126.png)

### 6. App Store Screenshot 6 
![Screen Shot 2020-04-10 at 3 34 22 PM](https://user-images.githubusercontent.com/48343061/79027359-cc10d500-7b40-11ea-8678-b639deebd5fc.png)

### 7. App Store Screenshot 7 
_Note: QA only the texts in the red box at the bottom of the screen_

![Screen Shot 2020-04-10 at 3 34 53 PM](https://user-images.githubusercontent.com/48343061/79027384-dfbc3b80-7b40-11ea-83fe-ec9f6e4a7b4c.png)

### 8. App Store Screenshot 8
![Screen Shot 2020-04-10 at 3 35 25 PM](https://user-images.githubusercontent.com/48343061/79027394-e9de3a00-7b40-11ea-887c-2b445352613f.png)

### 9. What's New
![Screen Shot 2020-04-10 at 3 35 44 PM](https://user-images.githubusercontent.com/48343061/79027415-f6629280-7b40-11ea-9085-1563b21ce71d.png)

### 10. Search is in Beta
![Screen Shot 2020-04-10 at 3 36 05 PM](https://user-images.githubusercontent.com/48343061/79027445-0d08e980-7b41-11ea-8a24-b6710e365ff1.png)

### 11. Service Detail
![Screen Shot 2020-04-10 at 5 18 13 PM](https://user-images.githubusercontent.com/48343061/79030837-f0c07900-7b4f-11ea-88d5-cc1377235650.png)

**Comment by harjul0618** [comment]
Screen Name: App Store Screenshot 1
English Texts: Powered by
Current Texts: 제작
Suggested Texts: 제공
Rationale: The suggested text is more commonly used in the same context. 

Screen Name: App Store Screenshot 2
English Texts: Trusted information 
                         for newcomers to 
                         British Columbia
Current Texts: 브리티시컬럼비아주 신규 이민
                         자를 위한 신뢰성 있는 정보 
Suggested Texts: BC주 신규 이민자를 위한 
                              신뢰성 있는 정보
Rationale: In the current texts, one word ("이민자를") is divided at the end of the line. The change makes it more readable. 

3. App Store Screenshot 3 - Pass

Screen Name: App Store Screenshot 4
English Texts: Get recommendations based on your situation
Current Texts: 나의 현 상황에 맞는 추천 받기
Suggested Texts: 내 상황에 맞는 추천 받기
Rationale: The change is more concise for the heading. (This change is optional)

Screen Name: App Store Screenshot 5
English Texts: Optional questions to find your most relevant information
Current Texts: 가장 적절한 정보의 탐색을
                         위한 선택 질문들
Suggested Texts: 최적의 정보 탐색을 위한 
                              추가 질문들
Rationale: The change is more concise for the heading.  (This change is optional)

6. App Store Screenshot 6 - Pass
7. App Store Screenshot 7 - Pass
8. App Store Screenshot 8 - Pass

Screen Name: What's new
English Texts: We've made updates and improvements to make your experience even better
Current Texts: -
Suggested Texts: 여러분의 더 나은 경험을 위해 업데이트와 개선된 기능을 제공합니다. 
Rationale: There's no translation for this sentence. (A missing text)

Screen Name: What's new
English Texts: What's new (The second one)
Current Texts: 새로운 기 
Suggested Texts: 새로운 기능
Rationale: A typo

Screen Name: App Store Screenshot 10
English Texts: Search is currently in beta and only available in English.
Current Texts: 검색은 현재 베타 서비스이며 영어로만 가능합니다.
Suggested Texts: 검색 기능은 현재 베타 서비스 중이며 영어로만 가능합니다. 
Rationale:The change sounds more precise. 

11. Service Detail - Pass

**Comment by jparlina** [comment]
QA results review:

### Screen Name: App Store Screenshot 1
English Texts: Powered by
Current Texts: 제작
Suggested Texts: 제공
Rationale: The suggested text is more commonly used in the same context.
_Confirmed with Julie by email that the current translation is correct since the English string "Powered by" had been revised to "Created by"_ on the latest version of the app. 

### Screen Name: App Store Screenshot 2
Updated translations on weblate, and on App Store and Play Store screenshots. 

### Screen Name: What's new
Fixed typo on weblate and missing second sentence (translation was already on weblate, just not showing up on the screen). 

### Screen Name: App Store Screenshot 10
Updated translation on weblate. 

Optional changes for App Store Screenshots 4 and 5 are not implemented due to tight timeline. 

@jparlina to review revisions after next staging release.

**Comment by jparlina** [comment]
**Screen Name: App Store Screenshot 2** 
- [x] revised screenshot for Apple App Store - PASS
<img width="330" alt="Screen Shot 2020-04-21 at 4 48 01 PM" src="https://user-images.githubusercontent.com/48343061/79925736-eb84e900-83ef-11ea-9b20-344140d95c77.png">

- [x] revised screenshot for Play Store - PASS
<img width="337" alt="Screen Shot 2020-04-21 at 4 45 34 PM" src="https://user-images.githubusercontent.com/48343061/79925747-f3dd2400-83ef-11ea-9159-7fc30c01146e.png">

**Screen Name: 10. Search is in beta**
Tested on staging V1.29.0 Server V1.3.28 - PASS
<img width="442" alt="Screen Shot 2020-04-21 at 4 40 48 PM" src="https://user-images.githubusercontent.com/48343061/79925948-854c9600-83f0-11ea-9528-64aadadf3c9e.png">

**Comment by jparlina** [comment]
@tomy-pg Please confirm that the Korean typo on "what's new" has been fixed and you can close this issue. Thanks.

**Comment by tomy-pg** [comment]
Confirmed.
