### ISSUE TITLE
Punjabi QA - Apr 10, 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#71]
### 1. App Store Screenshot 1
![Screen Shot 2020-04-10 at 3 38 51 PM](https://user-images.githubusercontent.com/48343061/79027535-70931700-7b41-11ea-92f7-c55531f0f7e5.png)

### 2. App Store Screenshot 2 
![Screen Shot 2020-04-10 at 3 39 26 PM](https://user-images.githubusercontent.com/48343061/79027570-9f10f200-7b41-11ea-8153-9af0aaf7ed62.png)

### 3. App Store Screenshot 3 
![Screen Shot 2020-04-10 at 3 40 47 PM](https://user-images.githubusercontent.com/48343061/79027580-a9cb8700-7b41-11ea-9034-ead6acca90e6.png)

### 4. App Store Screenshot 4 
![Screen Shot 2020-04-10 at 3 41 06 PM](https://user-images.githubusercontent.com/48343061/79027607-bb149380-7b41-11ea-9bc9-84dc6e0d0219.png)

### 5. App Store Screenshot 5
![Screen Shot 2020-04-10 at 3 41 37 PM](https://user-images.githubusercontent.com/48343061/79027617-c962af80-7b41-11ea-8e90-cb9a67dfb90c.png)

### 6. App Store Screenshot 6 
![Screen Shot 2020-04-10 at 3 42 00 PM](https://user-images.githubusercontent.com/48343061/79027632-dda6ac80-7b41-11ea-9821-49c902e4afb1.png)

### 7. App Store Screenshot 7 
_Note: QA only the texts in the red box at the bottom of the screen_

![Screen Shot 2020-04-10 at 3 42 31 PM](https://user-images.githubusercontent.com/48343061/79027658-f0b97c80-7b41-11ea-9b01-62f7dae3570f.png)

### 8. App Store Screenshot 8
![Screen Shot 2020-04-10 at 3 43 04 PM](https://user-images.githubusercontent.com/48343061/79027672-fadb7b00-7b41-11ea-800e-b67beb661864.png)

### 9. What's New
![Screen Shot 2020-04-10 at 3 43 28 PM](https://user-images.githubusercontent.com/48343061/79027687-09c22d80-7b42-11ea-81ee-f55991b3c04d.png)

### 10. Search is in Beta
![Screen Shot 2020-04-10 at 3 44 00 PM](https://user-images.githubusercontent.com/48343061/79027741-3413eb00-7b42-11ea-8e81-1ff305321942.png)

### 11. Service Detail
![Screen Shot 2020-04-10 at 5 25 44 PM](https://user-images.githubusercontent.com/48343061/79030975-ae4b6c00-7b50-11ea-8b3f-3884c7071023.png)

**Comment by aalam** [comment]
1. App Store Screenshot 1 - PASSED
    2. App Store Screenshot 2 - only the texts in red box - PASSED
    3. App Store Screenshot 3 - ALL texts - PASSED
    4. App Store Screenshot 4 - only the texts in red box - PASSED
    5. App Store Screenshot 5 - ALL texts - PASSED
    6. App Store Screenshot 6 - only the texts in red box - PASSED
    7. App Store Screenshot 7 - only the texts in red box - PASSED
    8. App Store Screenshot 8 - ALL texts - PASSED
    9. What's New - ALL texts - PASSED
    10. Search is in Beta - only the texts in red box - PASSED
    11. Service Detail - only the texts in red box - PASSED

**Comment by jparlina** [comment]
Thank you @aalam! Please email me your invoice.
