### ISSUE TITLE
Tagalog QA - App Store / Play Store Screenshots

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#72]
### 1. App Store Screenshot 1
![Screen Shot 2020-04-10 at 3 49 10 PM](https://user-images.githubusercontent.com/48343061/79027903-dd5ae100-7b42-11ea-8cf1-2b4e21553d66.png)

### 2. App Store Screenshot 2 
_Note: QA only the texts in the red box_

![Screen Shot 2020-04-10 at 3 49 40 PM](https://user-images.githubusercontent.com/48343061/79027958-0a0ef880-7b43-11ea-910f-a098a0c445c1.png)

### 3. App Store Screenshot 3 
![Screen Shot 2020-04-10 at 3 50 55 PM](https://user-images.githubusercontent.com/48343061/79027967-1430f700-7b43-11ea-9414-0682097d395d.png)

### 4. App Store Screenshot 4 
_Note: QA only the texts in the red box_

![Screen Shot 2020-04-10 at 3 51 15 PM](https://user-images.githubusercontent.com/48343061/79027977-29a62100-7b43-11ea-8745-099698237493.png)

### 5. App Store Screenshot 5
![Screen Shot 2020-04-10 at 3 52 05 PM](https://user-images.githubusercontent.com/48343061/79027997-42163b80-7b43-11ea-9314-f27fa1832479.png)

### 6. App Store Screenshot 6 
_Note: QA only the texts in the red box_

![Screen Shot 2020-04-10 at 3 52 32 PM](https://user-images.githubusercontent.com/48343061/79028011-53f7de80-7b43-11ea-867a-286d676857ef.png)

### 7. App Store Screenshot 7 
_Note: QA only the texts in the red box at the bottom of the screen_

![Screen Shot 2020-04-10 at 3 53 04 PM](https://user-images.githubusercontent.com/48343061/79028025-670aae80-7b43-11ea-977c-3336b14b0088.png)

### 8. App Store Screenshot 8
![Screen Shot 2020-04-10 at 3 53 34 PM](https://user-images.githubusercontent.com/48343061/79028039-738f0700-7b43-11ea-97a3-13079dd2e518.png)

**Comment by niko-pg** [comment]
1) App Store Screenshot 1 - PASS
2) App Store Screenshot 2 - PASS
3) App Store Screenshot 3 - PASS
4) App Store Screenshot 6 - PASS
5) App Store Screenshot 7 - PASS
6) App Store Screenshot 8 - PASS

**Comment by niko-pg** [comment]
Screen Name: App Store Screenshot 4 
English Texts: 
Get recommendations based on your situation
Current Texts: 
Makakuha ng rekomendasyon batay sa iyong sitwasyon
Suggested Texts:
Kumuha ng rekomendasyon na batay sa iyong sitwasyon
Rationale:
-"Kumuha" should be the tense to indicate an imperative mood.
- "na" is necessary after "rekomendasyon" to link it to the next phrase

Screen Name: _App Store Screenshot 5_
English Texts:
_Less than 1 year_
Current Texts:
_Kulang 1 taon_
Suggested Texts:
_Wala pang 1 taon_
Rationale:
Kulang does not fit in this sentence as it's close to the word "lacking". _Wala pang 1 taon_ fits better in this context.

Screen Name: _App Store Screenshot 5_
English Texts:
_Next_
Current Texts:
_Susunod_
Suggested Texts:
_Tuloy_
Rationale:
_Susunod_ means "coming up" or "following". _Tuloy_ should be used to denote continue.

Screen Name: _App Store Screenshot 5_
English Texts:
_Optional questions to find your most relevant information_
Current Texts:
_Opsyonal na mga taong upang humanap ng iyong pinakakaugnay na impormasyon_
Suggested Texts:
_Opsyonal na mga tanong upang humanap ng impormasyong nauugnay sa'yo_
Rationale:
-_tanong_ is the correct spelling, not _taong_
-rearranged the words to correctly convey the sense of the text

**Comment by jparlina** [comment]
Fixed on [weblate-app_screenshots](https://translate.peacegeeks.org/projects/ui-strings/app_screenshots/tl/):
**- App Store Screenshot 4:** _Get recommendations based on your situation_
**- App Store Screenshot 5:** _Optional questions to find your most relevant information_

@aron-chen-pg Please update the Tagalog strings on the teal background for the screenshots saved in [this folder](https://drive.google.com/drive/folders/1o1pYvZMOATjemsK-IBsU2XLUjbnGtLKr). 

Fixed on [weblate-questionnaire](https://translate.peacegeeks.org/projects/ui-strings/questionnaire/tl/):
**App Store Screenshot 5:** _Less than 1 year_

**Comment by jparlina** [comment]
@niko-pg 
I just found out that the "Next" button on the App Store Screenshot 5 has been changed to "Skip". The current Tagalog translation on the Staging app is "Laktawan". Please confirm if the translation makes sense. Thank you.

**Comment by aron-chen-pg** [comment]
Both screenshots 4 and 5 have been updated and re-uploaded. Please review.

**For Apple App Store:**
![Screenshot 4 - AA iPhone X - Tagalog](https://user-images.githubusercontent.com/54860686/79314831-14205680-7eb7-11ea-8235-ac0569d4532e.png)
![Screenshot 5 - AA iPhone X - Tagalog](https://user-images.githubusercontent.com/54860686/79314855-1aaece00-7eb7-11ea-888e-63dd29738ea3.png) 

**For Play Store:**
![Screenshot 4 - Tagalog](https://user-images.githubusercontent.com/54860686/79314975-492ca900-7eb7-11ea-9465-d32322be8e0a.png)
![Screenshot 5 - Tagalog](https://user-images.githubusercontent.com/54860686/79315015-55b10180-7eb7-11ea-8e03-b80b1738da85.png)

**Comment by jparlina** [comment]
**Screen Name: App Store Screenshot 5**
Also confirmed revised translations on the app (staging V1.29.0 Server 1.3.29)

![Screen Shot 2020-04-22 at 3 23 44 PM](https://user-images.githubusercontent.com/48343061/80039760-5f38fb80-84ad-11ea-9ee2-fb9923a13a85.png)
