### ISSUE TITLE
Arabic QA: App Strings - Aug 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#73]
See Section A (1 - 13) of [this document](https://drive.google.com/file/d/19BavPcO1V0ioLqf4lMlqB9m6Z4rjvRV2/view?usp=sharing) for screenshots in English and Arabic. Please enter your QA results by entering comments here on Github.

**Comment by hhaboh** [comment]
1. Content Alert: PASS
2. Search - Street: **Fail**.
Order of sentence should match English. If possible, add a LTR mark before number to fix, or leave as is if not possible.
See: http://tinyurl.com/y6ovlb3g
3. Search - Near: PASS
4. Feedback - Suggest an update: PASS
5. Feedback - Discard Changes: PASS
6. Feedback - System Explainer: PASS
7. Feedback - Thank You: PASS
8. Feedback - Other Suggestions: PASS
9. Feedback - Service No Longer Exists: PASS
10. Feedback - Contact Info: **Fail**.
Layout of text from Name to Enter your job title is set to left, meanwhile it should be right.
See http://tinyurl.com/y2zspar2
11. Feedback - Form: **Fail**.
Layout of text should be right not left.
See: http://tinyurl.com/y382hoce
12. Open External Link: PASS
13. Revised Onboarding 2: PASS

**Comment by jparlina** [comment]
2  Search - Street issue: moved to [Frontend issue #1243](https://app.zenhub.com/workspaces/arrival-advisor-5977956f40fbe90e67bb4155/issues/pg-irc/pathways-frontend/1243)

10  Feedback - Contact Info: moved to [Frontend issue #1244 ](https://app.zenhub.com/workspaces/arrival-advisor-5977956f40fbe90e67bb4155/issues/pg-irc/pathways-frontend/1244)

11  Feedback - Form: fixed on Staging V1.42.0 - see [Frontend issue #1221](https://app.zenhub.com/workspaces/arrival-advisor-5977956f40fbe90e67bb4155/issues/pg-irc/pathways-frontend/1221)

**Comment by jparlina** [comment]
Fixed on Staging V1.43.0
