### ISSUE TITLE
Korean QA: App Strings - Aug 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#74]
### 1. Content Alert
![Screen Shot 2020-07-27 at 4 36 25 PM](https://user-images.githubusercontent.com/48343061/88603088-f7083180-d028-11ea-84a7-218a9ce3f542.png)

### 2. Search - Street
![Screen Shot 2020-07-15 at 4 54 57 PM](https://user-images.githubusercontent.com/48343061/87611126-106dbd00-c6bc-11ea-9ea8-1b3bad2bd135.png)

### 3. Search - Near
![Screen Shot 2020-07-16 at 6 13 14 PM](https://user-images.githubusercontent.com/48343061/87737542-1a60f000-c790-11ea-989f-b48ee6a8792e.png)

### 4. Feedback - Suggest an update
<img width="372" alt="Screen Shot 2020-08-03 at 9 45 57 PM" src="https://user-images.githubusercontent.com/48343061/89253991-f3e5e600-d5d2-11ea-8c2b-578c12e2cf66.png">

### 5. Feedback - Discard Changes 
![Screen Shot 2020-07-15 at 5 11 34 PM](https://user-images.githubusercontent.com/48343061/87612384-3fd1f900-c6bf-11ea-8b18-4497012d2dc3.png)

### 6. Feedback - System Explainer (ALL)
<img width="381" alt="Screen Shot 2020-08-03 at 9 46 26 PM" src="https://user-images.githubusercontent.com/48343061/89254019-019b6b80-d5d3-11ea-9c76-802165325906.png">

### 7. Feedback - Thank You
![Screen Shot 2020-07-16 at 10 15 36 AM](https://user-images.githubusercontent.com/48343061/87702111-d3eaa180-c74d-11ea-9917-05e509d51d45.png)

### 8. Feedback - Other Suggestions
![Screen Shot 2020-07-16 at 6 45 06 PM](https://user-images.githubusercontent.com/48343061/87739415-a6751680-c794-11ea-8370-350b8ea95792.png)

### 9. Feedback - Service No Longer Exists
![Screen Shot 2020-07-16 at 6 44 33 PM](https://user-images.githubusercontent.com/48343061/87739466-c1e02180-c794-11ea-9a27-0b83958a7e3e.png)

### 10. Feedback - Contact Info (ALL)
![Screen Shot 2020-07-16 at 9 07 33 PM](https://user-images.githubusercontent.com/48343061/87747522-6d46a180-c7a8-11ea-912b-3ba8af98afb0.png)

### 11. Feedback - Form
![Screen Shot 2020-07-16 at 8 28 26 PM](https://user-images.githubusercontent.com/48343061/87745554-0ffc2180-c7a3-11ea-8614-f7830951f98b.png)

### 12. Open External Link
![Screen Shot 2020-07-16 at 8 34 33 PM](https://user-images.githubusercontent.com/48343061/87745825-cf50d800-c7a3-11ea-81de-3b860b9bdf20.png)

### 13. Revised Onboarding 2
![Screen Shot 2020-07-16 at 8 51 30 PM](https://user-images.githubusercontent.com/48343061/87746732-2a83ca00-c7a6-11ea-8e30-e8dfc4630a3b.png)

**Comment by harjul0618** [comment]
Screen Name: 6. Feedback - System Explainer
English Texts: The services listed on Arrival Advisor come from bc211, a nonprofit information and referral organization that publishes a searchable online directory of community, government, and social services in British Columbia. 
Current Texts: Arrival Advisor에 등록된 서비스들의 출처는 브리티시 컬럼비아주의 공동체와 정부, 사회 복지 제도의 온라인 검색 디렉터리를 게시하는 비영리 정보 및 추천 기관인 0>bc211</0>입니다. 
Suggested Texts: 
Rationale: No change in translation. Just the word '0>bc211</0>' needs a hyperlink.

**Comment by harjul0618** [comment]
Screen Name: 12. Open External Link 
English Texts: This link will open in your device's browser. 
Current Texts: 해당 링크는 
Suggested Texts: 해당 링크는 사용자의 단말기 브라우저에서 열립니다. 
Rationale: Missing texts - The Korean translation for 'will open in your device's browser' is missing.

**Comment by harjul0618** [comment]
1. Content Alert - PASS
2. Search - Street - PASS
3. Search - Near - PASS
4. Feedback - Suggest an update - PASS
5. Feedback - Discard Changes - PASS
7. Feedback - Thank You - PASS 
8. Feedback - Other Suggestions - PASS
9. Feedback - Service No Longer Exists - PASS
10. Feedback - Contact Info - PASS
11. Feedback - Form - PASS
13. Revised Onboarding 2 - PASS

**Comment by jparlina** [comment]
**Amended screenshots:** 

### 6. Feedback - System Explainer
<img width="450" alt="Screen Shot 2020-08-16 at 11 17 59 PM" src="https://user-images.githubusercontent.com/48343061/90363353-69ac7180-e017-11ea-8046-ad816b6cc374.png">

### 12. Open External Link
<img width="442" alt="Screen Shot 2020-08-16 at 11 23 39 PM" src="https://user-images.githubusercontent.com/48343061/90363414-906aa800-e017-11ea-8d7e-b65bdf61c592.png">

**Comment by harjul0618** [comment]
6. Feedback - System Explainer - PASS
12. Open External Link - PASS
