### ISSUE TITLE
Tagalog QA: App Strings - Aug 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#75]
### 1. Content Alert
![Screen Shot 2020-07-27 at 4 36 53 PM](https://user-images.githubusercontent.com/48343061/88603333-6f6ef280-d029-11ea-80a9-17fa089c790f.png)

### 2. Search - Street
![Screen Shot 2020-07-15 at 5 00 54 PM](https://user-images.githubusercontent.com/48343061/87611390-cf29dd00-c6bc-11ea-9790-6355fdc26252.png)

### 3. Search - Near
![Screen Shot 2020-07-16 at 6 17 46 PM](https://user-images.githubusercontent.com/48343061/87737762-b5f26080-c790-11ea-9afa-a0eee3420bf6.png)

### 4. Feedback - Suggest an update
<img width="366" alt="Screen Shot 2020-08-03 at 9 52 47 PM" src="https://user-images.githubusercontent.com/48343061/89254431-f4cb4780-d5d3-11ea-8638-48137ad2718c.png">

### 5. Feedback - Discard Changes 
![Screen Shot 2020-07-15 at 5 11 53 PM](https://user-images.githubusercontent.com/48343061/87612422-5d9f5e00-c6bf-11ea-904c-a4a33a1f7dee.png)

### 6. Feedback - System Explainer (ALL)
![Screen Shot 2020-08-03 at 9 54 40 PM](https://user-images.githubusercontent.com/48343061/89254443-f98ffb80-d5d3-11ea-96cb-f66753ba8ce2.png)

### 7. Feedback - Thank You
![Screen Shot 2020-07-16 at 10 22 12 AM](https://user-images.githubusercontent.com/48343061/87702468-4f4c5300-c74e-11ea-8e9e-9c14cb931c43.png)

### 8. Feedback - Other Suggestions
![Screen Shot 2020-07-16 at 7 25 09 PM](https://user-images.githubusercontent.com/48343061/87741745-1cc84780-c79a-11ea-862c-9361bd9f0be4.png)

### 9. Feedback - Service No Longer Exists
![Screen Shot 2020-07-16 at 7 26 13 PM](https://user-images.githubusercontent.com/48343061/87741818-45504180-c79a-11ea-9fd1-167a11f799c7.png)

### 10. Feedback - Contact Info (ALL)
![Screen Shot 2020-07-16 at 9 09 09 PM](https://user-images.githubusercontent.com/48343061/87747632-b860b480-c7a8-11ea-97da-ed1436aa2a6c.png)

### 11. Feedback - Form
![Screen Shot 2020-07-16 at 8 31 25 PM](https://user-images.githubusercontent.com/48343061/87745688-75501280-c7a3-11ea-911f-c24ed99655e0.png)

### 12. Open External Link
![Screen Shot 2020-07-16 at 8 36 24 PM](https://user-images.githubusercontent.com/48343061/87745926-10e18300-c7a4-11ea-9f04-808725a14f60.png)

### 13. Revised Onboarding 2
![Screen Shot 2020-07-16 at 8 53 18 PM](https://user-images.githubusercontent.com/48343061/87746843-70d92900-c7a6-11ea-9c10-9da8829e1614.png)

**Comment by jparlina** [comment]
Screen Name: 1. Content Alert 

<img width="583" alt="Screen Shot 2020-08-06 at 4 11 07 PM" src="https://user-images.githubusercontent.com/48343061/89591670-a26e6e80-d7ff-11ea-8c45-5f465ebc5749.png">

Suggested Texts
Rationale:

**Comment by jparlina** [comment]
1. Content Alert - PASS 
2. Search - Street - PASS
4. Feedback - Suggest an update - PASS
5. Feedback - Discard Changes  - PASS
6. Feedback - System Explainer  - PASS
7. Feedback - Thank You - PASS
8. Feedback - Other Suggestions - PASS
9. Feedback - Service No Longer Exists - PASS
10. Feedback - Contact Info  - PASS
11. Feedback - Form - PASS
12. Open External Link - PASS
13. Revised Onboarding 2 - PASS

**Comment by sheen-indonela** [comment]
### Screen Name: 1. Content Alert
English Text: learn more from the Government of Canada (Government of Canada is with hyperlink)
Current Text: alamin ninyo ang higit pa sa Pamahalaang ng Canada (Pamahalaang ng Canada is with hyperlink)
Suggested Text: mas alamin ang mga detalye sa Pamahalaan ng Canada (Pamahalaan ng Canada is with hyperlink)
Rationale: Grammar

**Comment by sheen-indonela** [comment]
### Screen Name: 2. Search-Street
 English Text: Street- "1356 Kingsway Vancouver"
 Current Text: Daan- "1356 Kingsway Vancouver"
 Suggested Text: Ngalan ng Kalye- "1356 Kingsway Vancouver"
 Rationale: "Ngalan ng Kalye" is asking for street name, while "Daan" is more like about the road.

**Comment by sheen-indonela** [comment]
Screen Name: Search-Near (Pass)

**Comment by sheen-indonela** [comment]
Screen Name: Feedback-Suggest an update
 English Text: Change name or other details
 Current Text: Palitan ang pangalan o iba pang detalye
 Suggested Text: Pagbabago sa pangalan o iba pang detalye
 Rationale: Palitan means replace, while pagbabago means change

Screen Name: Feedback-Suggest an update
 English Text: This service no longer exists
 Current Text: Wala na itong serbisyo
 Suggested Text: Wala na ang serbisyong ito
 Rationale: Grammar and meaning

Screen Name: Feedback-Suggest an update
 English Text: Your suggestions will be reviewed by our team before making changes to the service information. Learn more (Learn more-hyperlink)
 Current Text: Susuriin iyong mga mungkahi ng aming pangkat bago gumawa ng mga pagbabago sa impormasyon ng serbisyo.
 Suggested Text: Ang iyong mga mungkahi ay susuriin ng aming pangkat bago gumawa ng mga pagbabago sa impormasyon ng serbisyo.
 Rationale: Grammar

**Comment by sheen-indonela** [comment]
Screen Name: Feedback-Discard Changes (Pass)

**Comment by sheen-indonela** [comment]
Screen Name: Feedback-System Explainer (ALL)
 English Text: a nonprofit information and referral organization that publishes a searchable online directory of community, government, and social services in British Columbia.
 Current Text: isang hindi-pangkalakal na organisasyon ng impormasyon at sangguni na naglalathala ng isang direktoryo na mahahanap online ang mga serbisyong komunidad, pamahalaan, at panlipunan sa British Columbia. Tinitipon at binabago ng mga kawani ng BC 211 itong impormasyon ng mga serbisyo.
 Suggested Text: isang hindi-pangkalakal na organisasyon ng impormasyon at sangguni na naglalathala ng isang direktoryo na mahahanap online ukol sa mga serbisyo sa komunidad, pamahalaan, at panlipunan sa British Columbia. Kinokolekta at ina-update ng mga kawani ng bc211 itong impormasyon ng mga serbisyo.
Rationale: Grammar and meaning

**Comment by sheen-indonela** [comment]
### Screen Name: 7. Feedback-Thank you
 English Text: Provided by: MOSAIC
 Current Text: Inilaan ng: MOSAIC
 Suggested Text: Ibinigay ng: MOSAIC
 Rationale: Meaning of inilaan is intended, ibinigay is provided

Salamat sa iyong tulong! (pass)

**Comment by sheen-indonela** [comment]
Screen Name: Feedback-Other Suggestions
 English Text: Tell us more about this service
 Current Text: Sabihin pa sa amin tungkol nitong serbisyo
 Suggested Text: Sabihin pa sa amin ang tungkol sa serbistong ito
 Rationale: Grammar and meaning

**Comment by sheen-indonela** [comment]
Update: not serbistong it should be serbisyong

### Screen Name: 8. Feedback-Other Suggestions
 English Text: Tell us more about this service
 Current Text: Sabihin pa sa amin tungkol nitong serbisyo
 Suggested Text: Sabihin pa sa amin ang tungkol sa serbisyong ito
 Rationale: Grammar and meaning

**Comment by sheen-indonela** [comment]
### Screen Name: 9. Feedback-Service No Longer Exists
 English Text: This service no longer exists
 Current Text: Wala na itong serbisyo
 Suggested Text: Wala na ang serbisyong ito
 Rationale: Grammar and meaning

**Comment by sheen-indonela** [comment]
Screen Name: Feedback-Contact Info (ALL)
 English Text: Enter your email if you would like to be contacted about this issue
 Current Text: Ibigay iyong email kung nais ninyong makipag-ugnay tungkol nitong isyu.
 Suggested Text: Ibigay ang iyong email kung nais mong makipag-ugnay tungkol sa isyung ito.
 Rationale: Grammar and meaning

 English Text: Do you work at this service or organization?
 Current Text: Ikaw ba ay kasalukuyang pumapasok sa tanggapang ito?
 Suggested Text: Nagtratrabaho ka ba sa serbisyo o organisasyon na ito?
 Rationale: Grammar and meaning

**Comment by sheen-indonela** [comment]
Screen Name: Feedback-Form (Pass)

**Comment by sheen-indonela** [comment]
Screen Name: Open External Link
 English Text: Opening External Link
 Current Text: Pagbubukas na Panlabas na Link
 Suggested Text: Pagbubukas ng Panlabas na Link
 Rationale: Grammar and meaning

**Comment by sheen-indonela** [comment]
Screen Name: Revised Onboarding 2 (Pass)

**Comment by sheen-indonela** [comment]
### Screen Name: 4. Feedback-Suggest an update
 
**(1) English Text: Change name or other details**
 Current Text: Palitan ang pangalan o iba pang detalye
 Suggested Text: Pagbabago sa pangalan o iba pang detalye
 Rationale: Palitan means replace, while pagbabago means change

 **(2) English Text: This service no longer exists**
 Current Text: Wala na itong serbisyo
 Suggested Text: Wala na ang serbisyong ito
 Rationale: Grammar and meaning (for the meaning, the current text have a different meaning, it means "no longer have service" in other words it means "no use"

**(3) English Text: Your suggestions will be reviewed by our team before making changes to the service information. Learn more (Learn more-hyperlink)**
 Current Text: Susuriin iyong mga mungkahi ng aming pangkat bago gumawa ng mga pagbabago sa impormasyon ng serbisyo.
 Suggested Text: Ang iyong mga mungkahi ay susuriin ng aming pangkat bago gumawa ng mga pagbabago sa impormasyon ng serbisyo.
 Rationale: Grammar

**Comment by sheen-indonela** [comment]
### Screen Name: 6. Feedback-System Explainer (ALL)
 English Text: a nonprofit information and referral organization that publishes a searchable online directory of community, government, and social services in British Columbia. bc211's staff members collect and update this services information. 
 Current Text: isang hindi-pangkalakal na organisasyon ng impormasyon at sangguni na naglalathala ng isang direktoryo na mahahanap online ang mga serbisyong komunidad, pamahalaan, at panlipunan sa British Columbia. Tinitipon at binabago ng mga kawani ng BC 211 itong impormasyon ng mga serbisyo.
 Suggested Text: isang hindi-pangkalakal na organisasyon ng impormasyon at sangguni na naglalathala ng isang direktoryo na mahahanap online ukol sa mga serbisyo sa komunidad, pamahalaan, at panlipunan sa British Columbia. Kinokolekta at ina-update ng mga kawani ng bc211 itong impormasyon ng mga serbisyo.
 Rationale: For the 1st sentence is grammar, and needs to add an adjective which is the "ukol". For the 2nd sentence, "binabago" means is changing the information, "ina-update" is to update the information.

**Comment by sheen-indonela** [comment]
### Screen Name: 8. Feedback-Other Suggestions
 English Text: Tell us more about this service
 Current Text: Sabihin pa sa amin tungkol nitong serbisyo
 Suggested Text: Sabihin pa sa amin ang tungkol sa serbisyong ito
 Rationale: Grammar

**Comment by sheen-indonela** [comment]
### Screen Name: 10. Feedback-Contact Info (ALL)
 English Text: Enter your email if you would like to be contacted about this issue
 Current Text: Ibigay iyong email kung nais ninyong makipag-ugnay tungkol nitong isyu.
 Suggested Text: Ibigay ang iyong email kung nais mong makipag-ugnay tungkol sa isyung ito.
 Rationale: Grammar 

English Text: Do you work at this service or organization?
 Current Text: Ikaw ba ay kasalukuyang pumapasok sa tanggapang ito?
 Suggested Text: Nagtratrabaho ka ba sa serbisyo o organisasyon na ito?
 Rationale: Grammar and meaning, for the meaning "pumapasok" means attending or enter while "nagtratrabaho means "working or work.

**Comment by sheen-indonela** [comment]
### Screen Name: 12. Open External Link
 English Text: Opening External Link
 Current Text: Pagbubukas na Panlabas na Link
 Suggested Text: Pagbubukas ng Panlabas na Link
 Rationale: Grammar

**Comment by jparlina** [comment]
### Amended screenshots: 

### (1) Content Alert
![Screen Shot 2020-08-17 at 5 16 56 PM](https://user-images.githubusercontent.com/48343061/90456320-898e7480-e0ad-11ea-9f72-28c37a2554c3.png)

### (2) Search - Street
![Screen Shot 2020-08-17 at 5 18 28 PM](https://user-images.githubusercontent.com/48343061/90456410-c6f30200-e0ad-11ea-8c7e-ee6423b823fa.png)

### (4) Feedback - Suggest an update
![Screen Shot 2020-08-17 at 5 27 24 PM](https://user-images.githubusercontent.com/48343061/90456988-27367380-e0af-11ea-977b-8206c975b24a.png)

### (6) Feedback - System Explainer
![Screen Shot 2020-08-17 at 5 33 55 PM](https://user-images.githubusercontent.com/48343061/90457255-e8ed8400-e0af-11ea-8f47-5087e8f3b7cc.png)

### (7) Feedback - Thank you
![Screen Shot 2020-08-17 at 5 29 51 PM](https://user-images.githubusercontent.com/48343061/90457039-4fbe6d80-e0af-11ea-81c3-ad62bc21e6ca.png)

### (8) Feedback - Other Suggestions
![Screen Shot 2020-08-17 at 6 04 56 PM](https://user-images.githubusercontent.com/48343061/90458838-569baf00-e0b4-11ea-9a0c-0e488605bf97.png)

### (9) Feedback - Service No Longer Exists
![Screen Shot 2020-08-17 at 6 05 40 PM](https://user-images.githubusercontent.com/48343061/90458959-af6b4780-e0b4-11ea-96c2-e1f9cb707f6f.png)

### (10) Feedback - Contact Info
![Screen Shot 2020-08-17 at 6 07 34 PM](https://user-images.githubusercontent.com/48343061/90459025-dc1f5f00-e0b4-11ea-97a3-aff0e9846e43.png)

### (12) Open External Link 
![Screen Shot 2020-08-17 at 6 10 42 PM](https://user-images.githubusercontent.com/48343061/90459070-0244ff00-e0b5-11ea-8ddd-154925690d4e.png)

**Comment by sheen-indonela** [comment]
Screen Name: Content Alert
English Texts: Government of Canada (hyperlink)
Current Texts: Pamahalaang ng Canada (hyperlink)
Suggested Texts: Pamahalaan ng Canada
Rationale: Typo

**Comment by sheen-indonela** [comment]
Screen Name: Content Alert
 English Texts: Government of Canada (hyperlink)
 Current Texts: Pamahalaang ng Canada (hyperlink)
 Suggested Texts: Pamahalaan ng Canada (hyperlink)
 Rationale: Typo

**Comment by sheen-indonela** [comment]
Screen Name: Search Street (PASS)

**Comment by sheen-indonela** [comment]
Screen Name: Feedback- Suggest an update (PASS)

**Comment by sheen-indonela** [comment]
Screen Name: Feedback-System Explainer (PASS)

**Comment by sheen-indonela** [comment]
Screen Name: Feedback-Thank you (PASS)

**Comment by sheen-indonela** [comment]
Screen Name: Feedback-Other suggestions (PASS)

**Comment by sheen-indonela** [comment]
Screen Name: Feedback - Service No Longer Exists (PASS)

**Comment by sheen-indonela** [comment]
Screen Name:  Feedback - Contact Info (PASS)

**Comment by sheen-indonela** [comment]
Screen Name: Open External Link (PASS)

**Comment by tomy-pg** [comment]
Amended Screenshot:
![Screenshot_20200821-112615_Arrival Advisor](https://user-images.githubusercontent.com/47794846/90922687-40863b00-e3a1-11ea-9691-3b32308ac1fe.jpg)
