### ISSUE TITLE
Punjabi QA: App Strings  - Aug 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#76]
### 1. Content Alert
![Screen Shot 2020-07-27 at 4 36 40 PM](https://user-images.githubusercontent.com/48343061/88603229-359dec00-d029-11ea-8640-d3a0e845ee2f.png)

### 2. Search - Street
![Screen Shot 2020-07-15 at 4 59 00 PM](https://user-images.githubusercontent.com/48343061/87611334-aace0080-c6bc-11ea-9a2b-f9822bf71f9e.png)

### 3. Search - Near
![Screen Shot 2020-07-16 at 6 16 45 PM](https://user-images.githubusercontent.com/48343061/87737711-93f8de00-c790-11ea-8ff2-36d8aaac48d3.png)

### 4. Feedback - Suggest an update (ALL)
<img width="382" alt="Screen Shot 2020-08-03 at 9 49 13 PM" src="https://user-images.githubusercontent.com/48343061/89254161-54752300-d5d3-11ea-84f2-a2a0bacd6797.png">

### 5. Feedback - Discard Changes 
![Screen Shot 2020-07-15 at 5 11 41 PM](https://user-images.githubusercontent.com/48343061/87612409-54ae8c80-c6bf-11ea-8513-6a4bbe8f0ce6.png)

### 6. Feedback - System Explainer (ALL)
<img width="376" alt="Screen Shot 2020-08-03 at 9 49 41 PM" src="https://user-images.githubusercontent.com/48343061/89254167-5a6b0400-d5d3-11ea-8be1-77d179850316.png">

### 7. Feedback - Thank You
![Screen Shot 2020-07-16 at 10 20 01 AM](https://user-images.githubusercontent.com/48343061/87702274-0e543e80-c74e-11ea-953b-ff69321dad17.png)

### 8. Feedback - Other Suggestions
![Screen Shot 2020-07-16 at 7 17 46 PM](https://user-images.githubusercontent.com/48343061/87741324-16859b80-c799-11ea-965e-b5aab6ff43d0.png)

### 9. Feedback - Service No Longer Exists
![Screen Shot 2020-07-16 at 7 16 55 PM](https://user-images.githubusercontent.com/48343061/87741291-f950cd00-c798-11ea-95a5-946bb29e4c6a.png)

### 10. Feedback - Contact Info (ALL)
![Screen Shot 2020-07-16 at 9 08 26 PM](https://user-images.githubusercontent.com/48343061/87747555-86e7e900-c7a8-11ea-85a3-c542a8662049.png)

### 11. Feedback - Form 
![Screen Shot 2020-07-16 at 8 30 23 PM](https://user-images.githubusercontent.com/48343061/87745619-4174ed00-c7a3-11ea-9ce4-7f1c80193c9f.png)

### 12. Open External Link
![Screen Shot 2020-07-16 at 8 35 29 PM](https://user-images.githubusercontent.com/48343061/87745869-ebed1000-c7a3-11ea-8ef6-b65185c42dfc.png)

### 13. Revised Onboarding 2
![Screen Shot 2020-07-16 at 8 52 39 PM](https://user-images.githubusercontent.com/48343061/87746791-53a45a80-c7a6-11ea-8737-4eb9a4714f4c.png)

**Comment by aalam** [comment]
Content Alert - PASSED
Search - Street - PASSED
Search - Near - PASSED
Feedback - Suggest an update - PASSED
Feedback - Discard Changes - PASSED
Feedback - System Explainer - PASSED
Feedback - Thank You - PASSED
Feedback - Other Suggestions - PASSED
Feedback - Service No Longer Exists - PASSED
Feedback - Contact Info  - PASSED
Feedback - Form - PASSED
Open External Link - PASSED
Revised Onboarding 2 - PASSED
