### ISSUE TITLE
Arabic QA: Website - Aug 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#78]
See Section C (1 - 5) of [this document ](https://drive.google.com/file/d/19BavPcO1V0ioLqf4lMlqB9m6Z4rjvRV2/view?usp=sharing)for screenshots in English and Arabic. Please enter your QA results by entering comments here on Github.

**Comment by hhaboh** [comment]
1. FAQ - Info Source: **Fail**.
There are two issues as shown in screenshot: http://tinyurl.com/y66zyx5c
A. The word here is repeated; once in Arabic without hyperlink, and the second in English with a hyperlink.
B. Copying text might have been messed up, as part of the third paragraph is at the end of the first paragraph.
Current text for paragraph 3: PeaceGeeks في توسيع نطاق محتوى تطبيق Arrival Advisor ليشمل المزيد من المصادر والمعلومات للقادمين الجدد. لو توفر لديك مصدر ترغب في مشاركته، يرجى التواصل معنا. اتصل بنا
Suggested text for paragraph 3: كما يرغب فريق PeaceGeeks في توسيع نطاق محتوى تطبيق Arrival Advisor ليشمل المزيد من المصادر والمعلومات للقادمين الجدد. لو توفر لديك مصدر ترغب في مشاركته، يرجى التواصل معنا. اتصل بنا
2. FAQ - To be listed: **Fail**.
There are two issues as shown in screenshot: http://tinyurl.com/yycvdor4
A. Compared to English screenshot in the same PDF file, there should be no hyperlink. English screenshots provided in the GitHub ticket has a hyperlink. Please check which one is correct.
B. There is text missing from the last sentence.
Current text: لو كنت ترى أن منظمتك أو خدماتك تنطبق عليها معايير الضم، يمكنك إرسال رسالة بريد إلكتروني إلى updates@bc211.ca http://www.bc211.ca لتطلع على المزيد من المعلومات. يتعاون فريق تطبيق Arrival Advisor مع منظمة bc211 بهدف إضافة دليل الخدمات الذي تقدمه bc211 على تطبيقنا.
Suggested text: لو كنت ترى أن منظمتك أو خدماتك تنطبق عليها معايير الضم، يمكنك إرسال رسالة بريد إلكتروني إلى updates@bc211.ca حتى يتولى فريق bc211 التحقق من منظمتك أو خدماتك. يمكنك أيضا زيارة http://www.bc211.ca لتطلع على المزيد من المعلومات. يتعاون فريق تطبيق Arrival Advisor مع منظمة bc211 بهدف إضافة دليل الخدمات الذي تقدمه bc211 على تطبيقنا.
This screenshot shows how the target text should look like after applying changes: http://tinyurl.com/yyol4o33
3. FAQ - Website Version: PASS
4. FAQ - Checkmarked & Bookmarked Topics: PASS
5. Home - Available in your language: **Fail**.
List of languages in Arabic lists French, meanwhile English lists French (Canadian). Please use suggested text.
Current text: تطبيق Arrival Advisor متوفر باللغات الإنكليزية والفرنسية والعربية والصينية المبسطة والصينية التقليدية والكورية والبنجابية والتاغلوغية.
Suggested text: تطبيق Arrival Advisor متوفر باللغات الإنكليزية والعربية والصينية المبسطة والصينية التقليدية والفرنسية (الكندية) والكورية والبنجابية والتاغلوغية.

**Comment by tomy-pg** [comment]
Amended Screenshots:
### 1. FAQ - Info Source:
![Screen Shot 2020-08-12 at 2 57 13 PM](https://user-images.githubusercontent.com/47794846/90072805-e7395000-dcac-11ea-8420-9250141be976.png)

### 2. FAQ - To be listed: 
![Screen Shot 2020-08-12 at 3 01 37 PM](https://user-images.githubusercontent.com/47794846/90072839-f7512f80-dcac-11ea-95dd-9fb6e08ddf40.png)

### 5 Home - Available in your language:
![Screen Shot 2020-08-12 at 2 56 37 PM](https://user-images.githubusercontent.com/47794846/90072860-00da9780-dcad-11ea-98b4-84b626a59f5b.png)

If I have made any mistakes for 1 - FAQ Info Source, can you please send the entire set of paragraphs for easier copy and paste? Thank you

**Comment by hhaboh** [comment]
(1) FAQ - Info Source PASS
(2) FAQ - To be listed: PASS
(5) Available in Your Languages: PASS
