### ISSUE TITLE
Korean QA: Website - Aug 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#80]
### 1. FAQ - Info Source
![Screen Shot 2020-07-15 at 1 19 29 PM](https://user-images.githubusercontent.com/47794846/87591864-d55c9100-c69d-11ea-82bb-8bd4229f708e.png)

**Pleasure correct areas missing hyperlinks**

### 2. FAQ - To be listed
![Screen Shot 2020-07-15 at 1 20 13 PM](https://user-images.githubusercontent.com/47794846/87591935-eefdd880-c69d-11ea-9110-bc95c0d9233a.png)

### 3. FAQ - Website Version
![Screen Shot 2020-07-15 at 1 21 09 PM](https://user-images.githubusercontent.com/47794846/87592055-118ff180-c69e-11ea-8040-f2a18a7a1156.png)

### 4. FAQ - Checkmarked & Bookmarked Topics
![Screen Shot 2020-07-15 at 1 23 25 PM](https://user-images.githubusercontent.com/47794846/87592270-6c294d80-c69e-11ea-982c-2e1dd55b457e.png)

### 5. Home - Available in your language
![Screen Shot 2020-07-15 at 1 25 33 PM](https://user-images.githubusercontent.com/47794846/87592422-ae528f00-c69e-11ea-8d61-2fc3a3bd3de3.png)

**Comment by harjul0618** [comment]
Screen Name: 1. FAQ - Info Source
English Texts: Information for newcomers: 
Current Texts: None
Suggested Texts: 새 이민자를 위한 정보:
Rationale: Missing Texts

Screen Name: 1. FAQ - Info Source
English Texts: You can view the PDF version of the Newcomers' Guide, available in 15 languages, here.
Current Texts: 에서 15개의 언어로 번역된 "새 이민자 안내서'의 PDF 파일을 열람할 수 있습니다. 
Suggested Texts: 여기에서 15개의 언어로 번역된 "새 이민자 안내서'의 PDF 파일을 열람할 수 있습니다. 
Rationale: Missing hyperlink. Please add the word '여기' (meaning 'here') and a hyperlink to it. (The current sentence is incomplete!) 

Screen Name: 1. FAQ - Info Source
English Texts: The PeaceGeeks team would also like to expand the Arrival Advisor app content with more resources and information for newcomers. If you have a resource you would like to share, Contact us. 
Current Texts: None
Suggested Texts:  PeaceGeeks는 새 이민자를 위한 보다 많은 자원과 정보를 활용해 Arrival Advisor앱의 콘텐츠를 확장하고자 합니다. 공유하고자 하는 정보가 있을 경우, 저희에게 알려주세요.
Rationale: Missing Texts. Please add the (suggested) texts and insert a hyperlink to '저희에게 알려주세요' (meaning Contact us).

**Comment by harjul0618** [comment]
Screen Name: 2. FAQ -To be listed
English Texts: You can read bc211's inclusion Policy to see what organizations and services are listed. 
Current Texts: bc211의 등록 정책에서 어떤 기관이나 서비스가 등록되는지 확인할 수 있습니다. 
Suggested Texts: 
Rationale: No change in translation. Please extend the current hyperlink to cover the phrase 'bc211의 등록 정책'.

Screen Name: 2. FAQ -To be listed
English Texts: You can also visit http://www.bc211.ca for more information 
Current Texts: 더 자세한 정보 확인을 위해 <2>http://www.bc211.ca를 클릭하세요. 
Suggested Texts:  더 자세한 정보 확인을 위해 http://www.bc211.ca를 클릭하세요. 
Rationale: No change in translation. Please insert to a hyperlink to 'http://www.bc211.ca'.

**Comment by harjul0618** [comment]
Screen Name: 3. FAQ - Website Version 
English Texts: Stay tuned on our blog or by following PeaceGeeks on social media. 
Current Texts: 저희 블로그 를 수시로 확인하거나, PeaceGeeks의 SNS를 팔로우해 보세요.
Suggested Texts: 저희 블로그를 수시로 확인하거나, PeaceGeeks의 SNS를 팔로우해 보세요.
Rationale: No space needed between '블로그' and '를'.

**Comment by harjul0618** [comment]
Screen Name: 4. FAQ - Checkmarked & Bookmarked Topics
English Texts: What is the difference between check marked and bookmarked topics?
Current Texts: 별표 주제와 북마크 주제의 차이는 무엇인가요? 
Suggested Texts: 체크 마크 주제와 북마크 주제의 차이는 무엇인가요?
Rationale: For accuracy and consistency,  '별표' should be changed into '체크 마크.'

**Comment by harjul0618** [comment]
5. Home - Available in your language - PASS

**Comment by tomy-pg** [comment]
Amended Screenshots:
### 1. FAQ - Info Source
![Screen Shot 2020-08-12 at 3 53 12 PM](https://user-images.githubusercontent.com/47794846/90076297-3afb6780-dcb4-11ea-8abe-a5a94e9f40f3.png)

### 2. FAQ -To be listed:
![Screen Shot 2020-08-12 at 3 53 31 PM](https://user-images.githubusercontent.com/47794846/90076340-51a1be80-dcb4-11ea-850b-69fc7017fc07.png)


### 3. FAQ - Website Version
![Screen Shot 2020-08-12 at 3 54 14 PM](https://user-images.githubusercontent.com/47794846/90076357-5bc3bd00-dcb4-11ea-8e46-cb5c6f5869de.png)


### 4. FAQ - Checkmarked & Bookmarked Topics
![Screen Shot 2020-08-12 at 3 54 42 PM](https://user-images.githubusercontent.com/47794846/90076369-62523480-dcb4-11ea-974a-61ea9621be73.png)

**Comment by harjul0618** [comment]
1. FAQ - Info Source - PASS
2. FAQ - To be listed - PASS

**Comment by harjul0618** [comment]
Screen Name: 3. FAQ - Website Version
English Texts: Unfortunately there isn't a website version of Arrival Advisor right now, but we may release one in the future. Stay tuned on our blog or by following PeaceGeeks on social media.
Current Texts: 안타깝게도 현재로서는 Arrival Advisor의 웹사이트 버전을 제공하진 않지만, 향후에는 출시할 계획입니다.저희 블로그를 수시로 확인하거나 PeaceGeeks의 SNS를 팔로우해보세요. 
Suggested Texts: 안타깝게도 현재로서는 Arrival Advisor의 웹사이트 버전을 제공하진 않지만, 향후에는 출시할 계획입니다. 저희 블로그를 수시로 확인하거나 PeaceGeeks의 SNS를 팔로우해보세요. 
Rational: No change in translation and the previous request was successfully met. But I guess, in doing so, the space between two sentences was removed. Please leave a space between two sentences like (계획입니다. 저희 블로그를)

**Comment by harjul0618** [comment]
Screen Name: 4. FAQ - Checkmarked & Bookmarked Topics
English Texts: The check marked topics are recommended for the user based on their answers to the questionnaire, whereas bookmarked topics are the ones that are saved by the user. You can bookmark topics that have been recommended to you, as well as topics in general from the Learn page! By saving Bookmarks, you can build a plan of all the steps you plan to take on your newcomer journey. 
Current Texts: It's not in Korean!!
Suggested Texts: 체크 마크는 설문에 대한 사용자의 대답을 바탕으로 추천된 주제이고, 북마크는 사용자가 직접 저장한 주제입니다. 알아보기 페이지에서 찾은 일반 주제는 물론, 추천받은 주제들을 북마크할 수 있어요! 북마크로 저장하면 새 이민자 여정에 필요한 모든 단계를 계획할 수 있습니다. 
Rational: OMG! The current texts are not in Korean. (Chinese maybe?)

**Comment by tomy-pg** [comment]
Amended Screenshots 3. FAQ - Website Version
![Screen Shot 2020-08-21 at 12 50 25 PM](https://user-images.githubusercontent.com/47794846/90929072-e3908200-e3ac-11ea-8b53-411bcfbe5069.png)

**Comment by tomy-pg** [comment]
Amended Screenshots: 4. FAQ - Checkmarked & Bookmarked Topics🤦🏽‍♂️
![Screen Shot 2020-08-21 at 12 54 14 PM](https://user-images.githubusercontent.com/47794846/90929356-6ca7b900-e3ad-11ea-97c5-11ef7974e8e8.png)

**Comment by harjul0618** [comment]
3. FAQ - Website Version - PASS
4. FAQ - Checkmarked & Bookmarked Topics - PASS 😄
