### ISSUE TITLE
Punjabi QA: Website - Aug 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#81]
### 1. FAQ - Info Source
<img width="1386" alt="Screen Shot 2020-08-05 at 4 43 07 PM" src="https://user-images.githubusercontent.com/48343061/89474690-2dd1fc00-d73b-11ea-8c04-2c3374b5925a.png">

### 2. FAQ - To be listed
![Screen Shot 2020-07-15 at 12 59 03 PM](https://user-images.githubusercontent.com/47794846/87590012-fa9bd000-c69a-11ea-8b70-fbe6785b6ce2.png)

### 3. FAQ - Website Version
![Screen Shot 2020-07-15 at 1 04 09 PM](https://user-images.githubusercontent.com/47794846/87590486-b0ffb500-c69b-11ea-8a0f-45371efa1719.png)

### 4. FAQ - Checkmarked & Bookmarked Topics
![Screen Shot 2020-07-15 at 1 06 06 PM](https://user-images.githubusercontent.com/47794846/87590637-f623e700-c69b-11ea-936c-6de42c14f6a7.png)

### 5. Home - Available in your language
![Screen Shot 2020-07-15 at 1 08 51 PM](https://user-images.githubusercontent.com/47794846/87590891-5f0b5f00-c69c-11ea-8444-fab65e60f2ef.png)

**Comment by aalam** [comment]
FAQ - Info Source - PASSED
FAQ - To be listed - PASSED
FAQ - Website Version - PASSED
FAQ - Checkmarked & Bookmarked Topics - PASSED
Home - Available in your language - PASSED
