### ISSUE TITLE
Tagalog QA: Website - Aug 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#82]
### 1. FAQ - Info Source
<img width="767" alt="Screen Shot 2020-08-05 at 4 25 59 PM" src="https://user-images.githubusercontent.com/47794846/89473722-71773680-d738-11ea-8194-c3fad1b95d68.png">

**Pleasure correct areas missing hyperlinks**

### 2. FAQ - To be listed
![Screen Shot 2020-07-15 at 11 19 29 AM](https://user-images.githubusercontent.com/47794846/87581014-26b05480-c68d-11ea-8b01-3223981ac730.png)

### 3. FAQ - Website Version
![Screen Shot 2020-07-15 at 11 21 40 AM](https://user-images.githubusercontent.com/47794846/87581188-65460f00-c68d-11ea-9234-8c4097eae5cb.png)

### 4. FAQ - Checkmarked & Bookmarked Topics
![Screen Shot 2020-07-15 at 11 24 18 AM](https://user-images.githubusercontent.com/47794846/87581411-be15a780-c68d-11ea-8232-564dd37bdc9d.png)

### 5. Home - Available in your language
![Screen Shot 2020-07-15 at 11 27 37 AM](https://user-images.githubusercontent.com/47794846/87581708-3f6d3a00-c68e-11ea-82e8-4c2d0427850b.png)

**Comment by sheen-indonela** [comment]
Screen Name: FAQ-Info Source
English Text: Information for newcomers:
Current Text: (no text)
Suggested Text: Impormasyon para sa mga bagong dating:

English Text: Where does Arrival Advisor get its information?
Current Text: Saan makakakuha ng impormasyong ito ang Arrival Advisor?
Suggested Text: Saan kinuha ng Arrival Advisor ang mga impormasyon nito?
Rationale: Meaning

English Text: The topics provided by Arrival Advisor currently all come from the Newcomer's Guide to British Columbia(hyperlink), a resource made possible thanks to the Province of British Columbia through the Ministry of Jobs, Trade and Technology. 
Current Text: Ang mga paksang inilalaan ng Arrival Advisor ay kasalukuyang nagmula sa Gabay ng mga Bagong Dating Sa British Columbia (hyperlink the "Gabay ng mga Bagong Dating Sa British Columbia"), ang mapagkukunang inilaan ng Probinsya ng British Columbia sa pamamagitan ng Ministry of Jobs, Trade and Technology.
Suggested Text: Ang mga paksang ibinibigay ng Arrival Advisor ay kasalukuyang nagmula sa Gabay ng mga Bagong Dating sa British Columbia (hyperlink the "Gabay ng mga Bagong Dating sa British Columbia") isang mapagkukunan na ginawang possible, salamat sa Probinsya ng British Columbia at sa pamamagitan ng Ministeryo ng Trabaho, Kalakal at Teknolohiya.
Rationale: Meaning

English Text: The B.C. Newcomers' Guide provides newcomers and their families the information they need to settle in BC quickly and easily.
Current Text: Ang Gabay sa mga Bagong Dating ay naglalaan sa mga bagong dating at sa kanilang mga pamilya ng impormasyong kailangan nila upang madali at maalwang makapanirahan sa BC.
Suggested Text: Ang Gabay ng mga Bagong Dating sa BC ay nagbibigay sa mga bagong dating at sa kanilang mga pamilya ng impormasyong kailangan nila upang madali at maalwang makapanirahan sa BC.
Rationale: Meaning 

English Text: You can view the PDF version of the Newcomers' Guide , available in 15 languages, here (hyperlink "here")
Current Text: Missing translation
Suggested Translation: Maaari mong tingnan ang PDF na bersyon ng Gabay ng mga Bagong Dating, ito ay magagamit sa 15 na mga wika, dito. (hyperlink "ditto")
Rationale: Missing text

English Text: We will be updating the Arrival Advisor App as new editions becomes available.
Current Text: Babagohin namin ang Arrival Advisor app hanggat magagamit ang mga bagong edisyon.
Suggested Text: Magkakaroon kami ng pag-update sa Arrival Advisor App kung mayroon ng bagong edisyon.
Rationale: Meaning

Paragraph 2
English Text: a nonprofit information and referral organization that publishes a searchable online directory of community, government, and social services in British Columbia.
Current Text: isang hindi-pangkalakal na organisasyon ng impormasyon at sangguni na naglalathala ng isang direktoryo na mahahanap online ang mga serbisyong komunidad, pamahalaan, at panlipunan sa British Columbia. Tinitipon at binabago ng mga kawani ng BC 211 itong impormasyon ng mga serbisyo.
Suggested Text: isang hindi-pangkalakal na organisasyon ng impormasyon at sangguni na naglalathala ng isang direktoryo na mahahanap online ukol sa mga serbisyo sa komunidad, pamahalaan, at panlipunan sa British Columbia. Kinokolekta at ina-update ng mga kawani ng bc211 itong impormasyon ng mga serbisyo.
 Rationale: Grammar and meaning

**Comment by sheen-indonela** [comment]
Screen Name: FAQ-To be listed (Pass)

**Comment by sheen-indonela** [comment]
Screen Name: FAQ-Website Version
 English Text: Unfortunately there isn't a website version of Arrival Advisor right now, but we may release one in the future.
 Current Text: Ikinalulungkot na walang bersyong website ng Arrival Advisor sa ngayon, ngunit maari kaming maghatid ng isa sa hinaharap.
 Suggested Text: Sa kasamaang palad walang bersyong website ang Arrival Advisor sa ngayon, ngunit maaaring kaming maglabas ng isa sa hinaharap.
Rationale: Grammar and meaning

**Comment by sheen-indonela** [comment]
Screen Name: FAQ- Checkmarked & Bookmarked Topics
 English Text: What is the difference between check marked and bookmarked topics?
 Current Text: Ano ang pagkakaiba ng mga pagsang may star at naka-bookmark?
 Suggested Text: Ano ang pagkakaiba sa pagitan ng mga paksa na may tsek na marka at naka-bookmark?
Rationale: Grammar and meaning

**Comment by sheen-indonela** [comment]
### Screen Name: 5. Home-Available in your language
English Text: Arrival Advisor is offered in English, Arabic, Chinese Simplified, Chinese Traditional, French (Canadian), Korean, Punjabi, and tagalog
Current Text: Iniaalok ang Arrival Advisor sa English, Pranses, at Arabe, Malapit na ang Chinese (Pinasimple at Tradisyonal) Koreano, Punjabi, at Tagalog.
Suggested Text: Iniaalok ang Arrival Advisor sa Ingles, Arabe, Pinasemple at Tradisyonal na Chinese, Pranses, Koreano, Punjabi, at Tagalog
Rationale: Meaning of :Malapit na ang Chinese" is not related to the English content.

**Comment by jparlina** [comment]
@sheen-indonela Please clarify: 
- Is **_paragraph 3_** of the first screenshot (FAQ - Info Source) ok as it is? 
- For the rationale where you noted "meaning" above, please clarify how the meaning of the current texts is different from your suggested edits. Thank you.

**Comment by sheen-indonela** [comment]
Hi @jparlina, there is no revision for the paragraph 3 for the 1st screenshot.

**Comment by sheen-indonela** [comment]
### Screen Name: 1. FAQ-Info Source
 English Text: Information for newcomers:
 Current Text: (no text)
 Suggested Text: Impormasyon para sa mga bagong dating:

English Text: **Where does Arrival Advisor get its information?**
 Current Text: Saan makakakuha ng impormasyong ito ang Arrival Advisor?
 Suggested Text: Saan kumuha ang Arrival Advisor ng mga impormasyon nito?
 Rationale: Meaning of "makakakuha" (is to be able to get,) or the current text is that (it's asking where can Arrival Advisor get the information, no information yet)  "kumuha" means get, meaning of the suggested text is (the information is already at Arrival Advisor and it's asking where does it get it's information.

English Text: **The topics provided by Arrival Advisor currently all come from the Newcomer's Guide to British Columbia(hyperlink), a resource made possible thanks to the Province of British Columbia through the Ministry of Jobs, Trade and Technology**.
 Current Text: Ang mga paksang inilalaan ng Arrival Advisor ay kasalukuyang nagmula sa Gabay ng mga Bagong Dating Sa British Columbia (hyperlink the "Gabay ng mga Bagong Dating Sa British Columbia"), ang mapagkukunang inilaan ng Probinsya ng British Columbia sa pamamagitan ng Ministry of Jobs, Trade and Technology.
 Suggested Text: Ang mga paksang ibinibigay ng Arrival Advisor ay kasalukuyang nagmula sa Gabay ng mga Bagong Dating sa British Columbia (hyperlink the "Gabay ng mga Bagong Dating sa British Columbia") isang mapagkukunan na ginawang possible, salamat sa Probinsya ng British Columbia at sa pamamagitan ng Ministeryo ng Trabaho, Kalakal at Teknolohiya.
 Rationale: Meaning of the "inilalaan" is allocated, while the "ibinibigay" is provided

English Text: **The B.C. Newcomers' Guide provides newcomers and their families the information they need to settle in BC quickly and easily.**
 Current Text: Ang Gabay sa mga Bagong Dating ay naglalaan sa mga bagong dating at sa kanilang mga pamilya ng impormasyong kailangan nila upang madali at maalwang makapanirahan sa BC.
 Suggested Text: Ang Gabay ng mga Bagong Dating sa BC ay nagbibigay sa mga bagong dating at sa kanilang mga pamilya ng impormasyong kailangan nila upang madali at maalwang makapanirahan sa BC.
 Rationale: Meaning of the "naglalaan" is allocating, while the "nagbibigay" is provides or gives.


English Text: **You can view the PDF version of the Newcomers' Guide , available in 15 languages, here (hyperlink "here")**
 Current Text: Missing translation
 Suggested Translation: Maaari mong tingnan ang PDF na bersyon ng Gabay ng mga Bagong Dating, ito ay magagamit sa 15 na mga wika, dito. (hyperlink "ditto")
 Rationale: Missing text

English Text: **We will be updating the Arrival Advisor App as new editions becomes available.**
 Current Text: Babagohin namin ang Arrival Advisor app hanggat magagamit ang mga bagong edisyon.
 Suggested Text: Magkakaroon kami ng pag-update sa Arrival Advisor App kung mayroon ng bagong edisyon.
 Rationale: Meaning of the current text is "changing the Arrival Advisor until the new edition can be use", while the suggested text is "there will be an update to Arrival Advisor App as new editions becomes available

### Paragraph 2
 English Text: **a nonprofit information and referral organization that publishes a searchable online directory of community, government, and social services in British Columbia. bc211's staff members collect and update this services information.**
 Current Text: isang hindi-pangkalakal na organisasyon ng impormasyon at sangguni na naglalathala ng isang direktoryo na mahahanap online ang mga serbisyong komunidad, pamahalaan, at panlipunan sa British Columbia. Tinitipon at binabago ng mga kawani ng BC 211 itong impormasyon ng mga serbisyo.
 Suggested Text: isang hindi-pangkalakal na organisasyon ng impormasyon at sangguni na naglalathala ng isang direktoryo na mahahanap online ukol sa mga serbisyo sa komunidad, pamahalaan, at panlipunan sa British Columbia. Kinokolekta at ina-update ng mga kawani ng bc211 itong impormasyon ng mga serbisyo.
 Rationale: For the 1st sentence is grammar, and needs to add an adjective which is the "ukol". For the 2nd sentence, "binabago" means is changing the information, "ina-update" is to update the information.

**Comment by sheen-indonela** [comment]
### Screen Name: 3. FAQ-Website Version
 English Text: Unfortunately there isn't a website version of Arrival Advisor right now, but we may release one in the future.
 Current Text: Ikinalulungkot na walang bersyong website ng Arrival Advisor sa ngayon, ngunit maari kaming maghatid ng isa sa hinaharap.
 Suggested Text: Sa kasamaang palad walang bersyong website ang Arrival Advisor sa ngayon, ngunit maaaring kaming maglabas ng isa sa hinaharap.
 Rationale: Grammar and meaning. "Ikinalulungkot" means sad, suggested text is "kasamaang palad" means unfortunately. 
"maghatid" means bring, while "maglabas" means release.

**Comment by sheen-indonela** [comment]
### Screen Name: 4. FAQ- Checkmarked & Bookmarked Topics
 English Text: What is the difference between check marked and bookmarked topics?
 Current Text: Ano ang pagkakaiba ng mga paksang may star at naka-bookmark?
 Suggested Text: Ano ang pagkakaiba sa pagitan ng mga paksa na may tsek na marka at naka-bookmark?
 Rationale: Grammar and different meaning of "paksang may star" is not equivalent to check marked.

**Comment by tomy-pg** [comment]
Amended screenshots:
### 1. FAQ - Info Source
![Screen Shot 2020-08-12 at 1 27 19 PM](https://user-images.githubusercontent.com/47794846/90064421-9a02b180-dc9f-11ea-9de7-4efec014365b.png)


### 3. FAQ - Website Version
![Screen Shot 2020-08-12 at 11 08 00 AM](https://user-images.githubusercontent.com/47794846/90062169-201cf900-dc9c-11ea-90d4-aac18c4fed8c.png)

### 4. FAQ - Checkmarked & Bookmarked Topics
![Screen Shot 2020-08-12 at 1 32 41 PM](https://user-images.githubusercontent.com/47794846/90064944-59576800-dca0-11ea-8dfd-19c690687b28.png)

### 5. Home - Available in your language
![Screen Shot 2020-08-12 at 9 35 47 AM](https://user-images.githubusercontent.com/47794846/90064992-6bd1a180-dca0-11ea-99cc-09904bd401c1.png)

**Comment by sheen-indonela** [comment]
Screen Name: FAQ - Info Source (PASS)

**Comment by sheen-indonela** [comment]
Screen Name: 3. FAQ-Website Version
English Text: Unfortunately there isn't a website version of Arrival Advisor right now, but we may release one in the future. Stay tuned on our blog or by following PeaceGeeks on social media.
 Current Text:  Sa kasamaang palad walang bersyong website ang Arrival Advisor sa ngayon, ngunit maaaring kaming maglabas ng isa sa hinaharap. Mananatiling nakatutok sa aming blog o sundan ang PeaceGeeks sa social media.
Suggested Text: Sa kasamaang palad walang bersyong website ang Arrival Advisor sa ngayon, ngunit maaari kaming maglabas ng isa sa hinaharap. Manatiling tumutok sa aming blog o sundan ang PeaceGeeks sa sosyal medya.
 Rationale:  Typo, grammar.

**Comment by sheen-indonela** [comment]
Screen Name: FAQ - Checkmarked & Bookmarked Topics (PASS)
Screen Name: Home - Available in your language (PASS)

**Comment by tomy-pg** [comment]
Amended screenshot: 3. FAQ - Website Version
![Screen Shot 2020-08-21 at 12 58 51 PM](https://user-images.githubusercontent.com/47794846/90929688-11c29180-e3ae-11ea-9302-f04472cc0cf5.png)
