### ISSUE TITLE
Arabic QA: Release Notes - Aug 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#83]
See Section B of [this document](https://drive.google.com/file/d/19BavPcO1V0ioLqf4lMlqB9m6Z4rjvRV2/view?usp=sharing ) for screenshots in English and Arabic. Please enter your QA results by entering comments here on Github.

**Comment by hhaboh** [comment]
Release Notes for Android Store: **Fail**.
Lines have unnatural lines ends, which affects readability. Please remove additional line ends, or use the following text.
ما الجديد •
شكرا لك على استخدام تطبيق Arrival Advisor! لقد أجرينا بعض التحديثات والتحسينات كي نجعل من خبرة استخدامك للتطبيق أفضل من ذي قبل.
ما الجديد
•	يمكنك الآن اقتراح إجراء تحديثات على تفاصيل الخدمات. حينما تبحث عن خدمة، لو رأيت وجود معلومات ناقصة أو غير صحيحة تتعلق بالخدمة المدرجة، لا تتردد في الضغط على زر «اقتراح تحديث» كي تبلغ فريق تطبيق Arrival Advisor بالأمر حتى يتمكنوا من تصويبه.
•	لقد حسنّا نتائج البحث حينما تبحث عن أي من الخدمات.
See this screenshot that shows how the entire text should look like when line ends are natural http://tinyurl.com/y4sh2w2r

**Comment by tomy-pg** [comment]
### Amended Screenshot
![Screenshot_20200813-152233_Google Play Store](https://user-images.githubusercontent.com/47794846/90193379-a8250080-dd79-11ea-8731-251f57313b43.jpg)

**Comment by hhaboh** [comment]
Release Notes for Android Store: PASS
