### ISSUE TITLE
French QA: Release Notes - Aug 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#84]
<img width="371" alt="Screen Shot 2020-07-28 at 12 48 29 PM" src="https://user-images.githubusercontent.com/48343061/88713794-aea44e80-d0d0-11ea-9a45-9513658de099.png">

**Comment by tomy-pg** [comment]
**Please note**
> We've made updates and improvements to make your experience even better.

has been cut from the FR locale as the release notes exceeded the character limit on the play store.

**Comment by ludivinegh** [comment]
As reported for the app, there is an inconsistency with straight and curly apostrophes being used here. If possible, replace with ' with ’. If you would prefer me to provide each of the affected strings, please let me know and I can do it. This affects the strings in scope and out of scope on the screenshot.

**Comment by jparlina** [comment]
@ludivinegh Thank you for pointing out the inconsistency. We'll replace ' with ’.

**Comment by tomy-pg** [comment]
![Screenshot_20200817-093847_Google Play Store](https://user-images.githubusercontent.com/47794846/90421148-d0f51080-e06d-11ea-89af-57daee04dd53.jpg)
