### ISSUE TITLE
Punjabi QA: Release Notes - Aug 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#85]
<img width="371" alt="Screen Shot 2020-07-28 at 12 47 16 PM" src="https://user-images.githubusercontent.com/48343061/88713671-861c5480-d0d0-11ea-89c5-0bf7b5710931.png">

**Comment by aalam** [comment]
There is missing a " mark and \ sign need to remove. add more information.
Original Translation:
ਤੁਸੀਂ ਸੇਵਾ ਵੇਰਵਿਆਂ ਦੇ ਅੱਪਡੇਟ ਬਾਰੇ ਹੁਣ ਸੁਝਾਅ ਦੇ ਸਕਦੇ ਹੋ। ਜਦੋਂ ਸੇਵਾ ਲਈ ਖੋਜ ਕਰਦੇ ਹੋ ਤਾਂ ਜੇ ਦਿਖਾਈ ਦਿੰਦੀ ਸੇਵਾ ਦੇ ਬਾਰੇ ਕੋਈ ਵੀ ਜਾਣਕਾਰੀ ਗ਼ੈਰ-ਮੌਜੂਦ ਜਾਂ ਗਲਤ ਹੈ ਤਾਂ ਅੱਪਡੇਟ ਲਈ ਸੁਝਾਅ\" ਬਟਨ ਨੂੰ ਕਲਿੱਕ ਕਰਕੇ Arrival Advisor ਦੀ ਟੀਮ ਨੂੰ ਇਹ ਠੀਕ ਕਰਨ ਲਈ ਦੱਸੋ। 

Updated Translation (added " and removed \":
ਤੁਸੀਂ ਸੇਵਾ ਵੇਰਵਿਆਂ ਦੇ ਅੱਪਡੇਟ ਬਾਰੇ ਹੁਣ ਸੁਝਾਅ ਦੇ ਸਕਦੇ ਹੋ। ਜਦੋਂ ਸੇਵਾ ਲਈ ਖੋਜ ਕਰਦੇ ਹੋ ਤਾਂ ਜੇ ਦਿਖਾਈ ਦਿੰਦੀ ਸੇਵਾ ਦੇ ਬਾਰੇ ਕੋਈ ਵੀ ਜਾਣਕਾਰੀ ਗ਼ੈਰ-ਮੌਜੂਦ ਜਾਂ ਗਲਤ ਹੈ ਤਾਂ "ਅੱਪਡੇਟ ਲਈ ਸੁਝਾਅ" ਬਟਨ ਨੂੰ ਕਲਿੱਕ ਕਰਕੇ Arrival Advisor ਦੀ ਟੀਮ ਨੂੰ ਇਹ ਠੀਕ ਕਰਨ ਲਈ ਦੱਸੋ।

**Comment by tomy-pg** [comment]
Amended Screenshot
![Screenshot_20200813-152532_Google Play Store](https://user-images.githubusercontent.com/47794846/90193454-d3a7eb00-dd79-11ea-9f01-825198e0fd07.jpg)

**Comment by jparlina** [comment]
@tomy-pg The amended screenshot is still missing " and have the \ which needs to be removed. Please copy and paste the revised complete sentence above. 
![Screen Shot 2020-08-14 at 4 51 44 PM](https://user-images.githubusercontent.com/48343061/90300395-1be50d00-de4f-11ea-8d41-79a4c28c5391.png)

**Comment by tomy-pg** [comment]
![Screenshot_20200817-093721_Google Play Store](https://user-images.githubusercontent.com/47794846/90421063-aefb8e00-e06d-11ea-924e-34a39820c910.jpg)

**Comment by aalam** [comment]
> 
> 
> ![Screenshot_20200817-093721_Google Play Store](https://user-images.githubusercontent.com/47794846/90421063-aefb8e00-e06d-11ea-924e-34a39820c910.jpg)

This screenshot looks good.
