### ISSUE TITLE
Tagalog QA: Release Notes - Aug 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#87]
<img width="367" alt="Screen Shot 2020-07-28 at 12 44 46 PM" src="https://user-images.githubusercontent.com/48343061/88713448-2b82f880-d0d0-11ea-8ebf-89af9be47137.png">

**Comment by tomy-pg** [comment]
**Please note**
> We've made updates and improvements to make your experience even better. 
has been cut from TL as the release notes exceeded the character limit on the playstore.

**Comment by sheen-indonela** [comment]
Task 2 Screen:
English Text: What's new
Current Text: Ano'ng bago
Suggested Text: Ano ang bago
Rationale: Typo and grammar

English Text: You can now suggest updates on service details.
Current Text: Maaari kayong magmungkahi ngayon ng mga pagbabago sa mga detalye ng serbisyo.
Suggested Text: Maari na kayong magmungkahi ng mga pagbabago sa mga detalye ng serbisyo.
Rationale: Grammar and meaning

**Comment by tomy-pg** [comment]
`What's new` - they are both consistent and the first `What's new` is generated by the Play store. I think they should be consistent for now.

**Comment by tomy-pg** [comment]
Amended Screenshot
![Screenshot_20200813-152359_Google Play Store](https://user-images.githubusercontent.com/47794846/90193418-c0951b00-dd79-11ea-807c-43b80df6f0aa.jpg)
