### ISSUE TITLE
Chinese Traditional QA: Website - Aug 2020

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/arrival-advisor-qa#88]
### 1. FAQ - Info Source
![Screen Shot 2020-07-15 at 2 49 19 PM](https://user-images.githubusercontent.com/47794846/87601673-62a5e280-c6aa-11ea-838b-051829ecb50a.png)

### 2. FAQ - To be listed
![Screen Shot 2020-07-15 at 2 51 45 PM](https://user-images.githubusercontent.com/47794846/87601825-b87a8a80-c6aa-11ea-8591-3e9d18b32960.png)

### 3. FAQ - Website Version
![Screen Shot 2020-07-15 at 2 52 20 PM](https://user-images.githubusercontent.com/47794846/87601863-cd571e00-c6aa-11ea-8a3e-7593ef10c9c3.png)

### 4. FAQ - Checkmarked & Bookmarked Topics
![Screen Shot 2020-07-15 at 2 53 02 PM](https://user-images.githubusercontent.com/47794846/87601921-e6f86580-c6aa-11ea-95e9-ee5475c366ce.png)

### 5. Home - Available in your language
![Screen Shot 2020-07-15 at 2 55 54 PM](https://user-images.githubusercontent.com/47794846/87602142-4eaeb080-c6ab-11ea-8e03-6da5f1438bb3.png)

**Comment by ian-lin-PG** [comment]
Screen Name: FAQ - Info Source
English Texts: `available in 15 languages, here`
Current Texts: `共有15共有15種語言版本`
Suggested Texts: `共有15種語言版本`
Rationale: In Chinese the phrase `共有15` is repeated twice, thus redundant. Either the part in the hyper link can be removed or the part preceding the hyper link is removed.

**Comment by ian-lin-PG** [comment]
Screen Name: FAQ - To be listed
English Texts: `you can email updates@bc211.ca so the bc211 can review your organization or service. You can also visit bc211.ca for more information.`
Current Texts: `您可以發郵件至updatesbc211.cahttp://bc211.caa了解更多信息。`
Suggested Texts: `您可以發郵件至updatesbc211.ca， 以便bc211可以查看您的組織或服務。請至bc211.ca了解更多信息`
Rationale: In Chinese the two sentences merged together, especially at the hyperlinks which makes it illegible. I split the 2 sentences up and removed the extra `a` at the end of the bc211 url. Also I added a second part to the first sentence about bc211 reviewing the request to be included.

**Comment by jparlina** [comment]
@ian-lin-PG For the first screenshot above,  are we missing the 3rd paragraph? This was pointed out by our Chinese Simplified QA as well. I don't see "PeaceGeeks" any where on that screenshot. Please confirm, [here](https://github.com/pg-irc/arrival-advisor-qa/issues/100)'s the English SS for your reference. Thank you.

**Comment by ian-lin-PG** [comment]
@jparlina you are correct, the last sentence seems to be missing. It is the part with `Contact us`. Sorry for missing it.

**Comment by jparlina** [comment]
The third paragraph on the following screenshot is **missing** in the Chinese Traditional version
<img width="797" alt="Screen Shot 2020-08-07 at 2 19 40 PM" src="https://user-images.githubusercontent.com/48343061/89689558-829b8100-d8b9-11ea-87ee-e079fb0b2b1a.png">

Here's the Chinese Traditional translations from row 9 of [this spreadsheet](https://docs.google.com/spreadsheets/d/1nuthpy0uGfna-5MFyh-tUGrnBeaTZfIymjjiff9aP3g/edit#gid=0): 
PeaceGeeks團隊還希望為新移民提供更多的資源和信息，擴大Arrival Advisor應用的內容。如果您有想要共享的資源，請聯繫我們

**Comment by ian-lin-PG** [comment]
@jparlina the translation is correct, the link part of the sentence is `請聯繫我們`. That part might be formatted specially.

**Comment by tomy-pg** [comment]
Amended screenshots:
### 1 FAQ - Info Source
![Screen Shot 2020-08-13 at 9 56 58 AM](https://user-images.githubusercontent.com/47794846/90163837-7c8b2180-dd4b-11ea-8dbe-4e7f64e177ea.png)

### 2 FAQ - To be listed
![Screen Shot 2020-08-13 at 9 57 18 AM](https://user-images.githubusercontent.com/47794846/90163855-83199900-dd4b-11ea-9944-38f99d05110d.png)

**Comment by jparlina** [comment]
@ian-lin-PG Please review the amended screenshots above. Thanks.

**Comment by ian-lin-PG** [comment]
The change looks good, missing a Chinese period `。` and we are done on that front.

**Comment by ian-lin-PG** [comment]
Screen Name: FAQ - Info Source
English Texts: 
The topics provided by Arrival Advisor currently all come from the <ins>Newcomers' Guide to British Columbia</ins>, a resource made possible thanks to the Provide of British Colmbia through the Ministry of Jobs, Trade and Technology. The B.C. Newcomers' Guide provides newcomers and their families the information they need to settle in B.C. quickly and easily.

Current Texts: 
目前Arrival Advisor 的主題內容全部來自不列顛哥倫比亞省（BC省）<ins>不列顛哥倫比亞省（BC省）新移民指南</ins>，感謝不列顛哥倫比亞省（BC省）的省政府工作，貿易及科技廳所贊助之資源。不列顛哥倫比亞省（BC省）新移民指南為新移民及其家人提供在BC省輕鬆安家定居所需的訊息。

Suggested Texts: 
目前Arrival Advisor 的主題內容全部來自<ins>卑詩省新移民指南</ins>，感謝卑詩省政府工作，貿易及科技廳所贊助之資源。卑詩省新移民指南為新移民及其家人提供在卑詩省輕鬆安家定居所需的訊息。

Rationale: Too much redundancy with the 2 translated version of BC province through the entire paragraph.

**Comment by ian-lin-PG** [comment]
Screen Name: FAQ - Info Source
English Texts:
The services listed on arrival advisor come from <ins>bc211</ins>, a nonprofit information and referral organization that publishes a searchable online directory of community, government, and social services in British Columbia.

Current Texts:
Arrival Advisor中列出的服務來自<ins>bc211</ins>，這是一家非盈利的信息和轉介機構，發布英屬哥倫比亞省的社區，政府和社會服務的可搜索在線目錄。

Suggested Texts:
Arrival Advisor中列出的服務來自<ins>bc211</ins>，這是一家非盈利的信息和轉介機構，發布卑詩省的社區，政府和社會服務的可搜索在線目錄。

Rationale: A third translation of BC province is replaced with the standard shorter translation.

**Comment by tomy-pg** [comment]
Amended screenshot - FAQ - Info Source
![Screen Shot 2020-08-21 at 12 44 54 PM](https://user-images.githubusercontent.com/47794846/90928642-22720800-e3ac-11ea-8d1e-6336e3470964.png)
