### ISSUE TITLE
Chinese Simplified QA: Website - Aug 2020

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/arrival-advisor-qa#89]
### 1. FAQ - Info Source
![Screen Shot 2020-07-15 at 3 03 48 PM](https://user-images.githubusercontent.com/47794846/87602761-6cc8e080-c6ac-11ea-890e-a6dabc8dcc56.png)

### 2. FAQ - To be listed
![Screen Shot 2020-07-15 at 3 04 26 PM](https://user-images.githubusercontent.com/47794846/87602801-7fdbb080-c6ac-11ea-9993-233423a1c108.png)

### 3. FAQ - Website Version
![Screen Shot 2020-07-15 at 3 06 40 PM](https://user-images.githubusercontent.com/47794846/87603247-cdf0b400-c6ac-11ea-86c3-cb199a444ae2.png)

### 4. FAQ - Checkmarked & Bookmarked Topics
![Screen Shot 2020-07-15 at 3 10 41 PM](https://user-images.githubusercontent.com/47794846/87604791-5e2ef900-c6ad-11ea-9896-9947a4c86987.png)

### 5. Home - Available in your language
![Screen Shot 2020-07-15 at 3 12 15 PM](https://user-images.githubusercontent.com/47794846/87605374-959da580-c6ad-11ea-8a9b-c6c6b93f545e.png)

**Comment by cjburnaby** [comment]
1. FAQ - Info Source

English Texts: 
The PeaceGeeks team would also like to expand the Arrival Advisor app content with more resources and information for newcomers. If you have a resource you would like to share, Contact us.
Current Texts: 
PeaceGeeks团队还希望为新移民提供更多的资源和信息，扩大Arrival Advisor应用的内容。如果您有想要共享的资源，请联系我们。
Suggested Texts: 
Same texts but needs to shift from the end of the first paragraph to the end and stand as the third paragraphs. See attached pic.
![FAQ-Info Source](https://user-images.githubusercontent.com/47732055/89538474-b8575000-d84e-11ea-893e-aaba8582a4ae.jpg)

Rationale: 
Wrong position in the paragraphs.

2. FAQ - To be listed

English Texts: bc211’s Inclusion Policy
Current Texts: bc211的包容性政策
Suggested Texts: Same texts but should be hyperlinked all.
Rationale: Was not hyperlinked completely.

2. FAQ - To be listed

English Texts: bc211 (in the 3rd line)
Current Texts: bc211
Suggested Texts: Same texts but hyperlink should be removed.
Rationale: No hyperlink in English version.

3. FAQ - Website Version: Pass

4. FAQ - Checkmarked & Bookmarked Topics
Suggested: To remove the garbled. See as red circle in attached pic.
![FAQ - Checkmarked   Bookmarked Topics](https://user-images.githubusercontent.com/47732055/89538437-ab3a6100-d84e-11ea-945e-79752df43fcc.jpg)

Rationale: Garbled character.


5. Home - Available in your language
English Texts: 
Arrival Advisor is offered in English, French, and Arabic. Coming soon in Chinese (Simplified and Traditional), Korean, Punjabi, and Tagalog.

Current Texts: 
Arrival Advisor提供英语、法语、阿拉伯语、中文简体、中文繁体、韩语、旁遮普语和菲律宾语等版本。

Suggested Texts: 
Arrival Advisor提供英语、法语和阿拉伯语版本。即将提供中文简体、中文繁体、韩语、旁遮普语和菲律宾语等版本。

Rationale: 
The missing translation of ‘Coming soon’ should be added and the sentences need segmentation.

**Comment by jparlina** [comment]
@cjburnaby Regarding **_5 Home - Available in your language_**, I previously provided the wrong [English screenshot](https://github.com/pg-irc/arrival-advisor-qa/issues/100), which yesterday had been updated as shown below (i.e. no "Coming soon"). Please review if this is consistent with the Chinese Simplified version provided above. Thank you. 
<img width="602" alt="Screen Shot 2020-08-07 at 11 39 14 AM" src="https://user-images.githubusercontent.com/48343061/89677793-ea929d00-d8a2-11ea-8bd5-848a14a215a5.png">

**Comment by cjburnaby** [comment]
5. Home - Available in your language
English Texts:
Arrival Advisor is offered in English, Arabic, Chinese Simplified, Chinese Traditional, French (Canadian), Korean, Punjabi, and Tagalog.
Current Texts:
Arrival Advisor提供英语、法语、阿拉伯语、中文简体、中文繁体、韩语、旁遮普语和菲律宾语等版本。

Suggested Texts:
Arrival Advisor提供英语、阿拉伯语、中文简体、中文繁体、加拿大法语、韩语、旁遮普语和菲律宾语等版本。

Rationale:
The word Canadian in the English version was missing in the translation, and the order of the languages is changed.

**Comment by tomy-pg** [comment]
Amended Screenshots

### 4 FAQ - Checkmarked & Bookmarked Topics
![Screen Shot 2020-08-12 at 4 25 28 PM](https://user-images.githubusercontent.com/47794846/90078078-99c2e000-dcb8-11ea-9dc8-079314b9a404.png)

### 5 Home - Available in your language
![Screen Shot 2020-08-12 at 4 22 33 PM](https://user-images.githubusercontent.com/47794846/90078086-a1828480-dcb8-11ea-9e46-8044e871ad01.png)

**Comment by jparlina** [comment]
@tomy-pg Missing hyperlinks: 

### (1) FAQ - Info Source
![Screen Shot 2020-08-14 at 6 33 52 PM](https://user-images.githubusercontent.com/48343061/90302681-c4e63480-de5c-11ea-96c6-ac1a8a76a6ca.png)

### (2) FAQ - To be listed
![Screen Shot 2020-08-14 at 6 35 08 PM](https://user-images.githubusercontent.com/48343061/90302704-f19a4c00-de5c-11ea-959e-c4abab0e0ec3.png)

**Comment by tomy-pg** [comment]
### Amended Screenshots:

### 1. FAQ - Info Source
![Screen Shot 2020-08-17 at 10 35 17 AM](https://user-images.githubusercontent.com/47794846/90425943-6c3db400-e075-11ea-94b9-2a1f84d7eaad.png)

### 2. FAQ - To be listed
![Screen Shot 2020-08-17 at 10 35 26 AM](https://user-images.githubusercontent.com/47794846/90425975-719afe80-e075-11ea-926e-390da4803a00.png)

**Comment by cjburnaby** [comment]
4. FAQ - Checkmarked & Bookmarked Topics: PASS
5. Home - Available in your language: PASS


2. FAQ - To be listed: PASS

**Comment by cjburnaby** [comment]
1. FAQ - Info Source: FAIL

1st:
English Texts:

The topics provided by Arrival Advisor currently all come from the [Newcomer's Guide to British Columbia](url), a resource made possible thanks to the Province of British Columbia through the Ministry of Jobs, Trade and Technology. 

Current Texts:
Arrival Advisor目前提供的主题都取自于[《卑诗省新移民指南》（Newcomers' Guide to British Columbia）](url)，这是不列颠哥伦比亚省经由工作、贸易及科技厅拨款而汇编的资源。

Suggested Texts:
Arrival Advisor目前提供的主题都取自于[《卑诗省新移民指南》（Newcomers' Guide to British Columbia）](url)，这是卑诗省经由工作、贸易及科技厅拨款而汇编的资源。

Rationale: consistency of translation on British Columbia

**Comment by cjburnaby** [comment]
1. FAQ - Info Source: FAIL

2nd:
English Texts:
The B.C Newcomers' Guide provides newcomers and their families the information they need to settle in B. C. quickly and easily. 

Current Texts:
《卑诗省新移民指南》为新移民及其家人提供了在B.C省快速轻松地安家落户所需的信息。

Suggested Texts:
《卑诗省新移民指南》为新移民及其家人提供了在卑诗省快速轻松地安家落户所需的信息。

Rationale: consistency of translation on British Columbia and B. C.

**Comment by cjburnaby** [comment]
1. FAQ - Info Source
3rd:
English Texts:
The services listed on Arrival Advisor come from [bc211](url), a nonprofit information and referral organization that publishes a searchable online directory of community, government, and social services in British Columbia. 

Current Texts: 
Arrival Advisor中列出的服务来自[bc211](url)，这是一家非盈利的信息和转介机构，发布英属哥伦比亚省的社区、政府和社会服务的可搜索的在线目录。

Suggested Texts:
Arrival Advisor中列出的服务来自[bc211](url)，这是一家非盈利的信息和转介机构，发布卑诗省的社区、政府和社会服务的可搜索的在线目录。

Rationale: consistency of translation on British Columbia

**Comment by cjburnaby** [comment]
1. FAQ - Info Source

4th:

English Texts: View the directory or learn more at [bc211.ca](url)

Current Texts: 
可登录网站[bc211.ca](url)
查看目录或了解更多信息。

Suggested Texts: 可登录网站[bc211.ca](url)查看目录或了解更多信息。

Rationale: To remove the line break as it is one sentence. Please see attached pic.
![90425943-6c3db400-e075-11ea-94b9-2a1f84d7eaad](https://user-images.githubusercontent.com/47732055/90577733-beb5d680-e215-11ea-89e5-c9df53fd9752.png)

**Comment by tomy-pg** [comment]
Amended screenshot FAQ - Info Source
![Screen Shot 2020-08-21 at 12 40 17 PM](https://user-images.githubusercontent.com/47794846/90928301-7a5c3f00-e3ab-11ea-8ab5-2ef43598907e.png)

**Comment by cjburnaby** [comment]
The amended screenshot FAQ - Info Source as shown above looks all right.

Thanks Tomy.
