### ISSUE TITLE
Punjabi QA: Content alert - July 2020

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/arrival-advisor-qa#96]
![Screenshot_20200716-101608_Arrival Advisor](https://user-images.githubusercontent.com/47794846/87702719-9cc8c000-c74e-11ea-9def-93b7ba8564ed.jpg)
> Get the latest information on health guidance and government support from the [Province of BC](https://www2.gov.bc.ca/gov/content/safety/emergency-preparedness-response-recovery/covid-19-provincial-support). For COVID-19 financial assistance for newcomers, learn more from the [Government of Canada](https://www2.gov.bc.ca/gov/content/safety/emergency-preparedness-response-recovery/covid-19-provincial-support).

**Comment by jparlina** [comment]
Combined Content Alert QA with App Strings QA (issue #76)
