### ISSUE TITLE
Arabic QA: Content alert - July 2020

### ISSUE THREAD

**Issue by tomy-pg** [pg-irc/arrival-advisor-qa#98]
See Section A of [this document](https://docs.google.com/document/d/1CpTl_zjDxwucffi7YI_n14w-PNbRJkADKNyLV-q4IaY/edit#bookmark=id.e2du4yl04y7b) for screenshots in English and Arabic.

**Comment by jparlina** [comment]
Combined Content Alert QA with App Strings QA (issue #73)
