### ISSUE TITLE
English Screenshots as Reference - App Strings - Aug 2020

### ISSUE THREAD

**Issue by jparlina** [pg-irc/arrival-advisor-qa#99]
### 1. Content Alert
![Screen Shot 2020-07-27 at 3 39 18 PM](https://user-images.githubusercontent.com/48343061/88598941-59f4cb00-d01f-11ea-85a1-999916620c6a.png)

### 2. Search - Street
![Screen Shot 2020-07-16 at 6 04 29 PM](https://user-images.githubusercontent.com/48343061/87737055-cefa1200-c78e-11ea-8830-a92ca9a38fda.png)

### 3. Search - Near
![Screen Shot 2020-07-16 at 6 01 03 PM](https://user-images.githubusercontent.com/48343061/87736984-9823fc00-c78e-11ea-9c7b-de47cceecfee.png)

### 4. Feedback - Suggest an update
![Screen Shot 2020-07-31 at 4 38 06 PM](https://user-images.githubusercontent.com/48343061/89088282-45307400-d34c-11ea-8df2-77a2da4bb6b7.png)

### 5. Feedback - Discard Changes 
![Screen Shot 2020-07-16 at 6 06 56 PM](https://user-images.githubusercontent.com/48343061/87737212-344e0300-c78f-11ea-85be-5dc9dab29daa.png)

### 6. Feedback - System Explainer (ALL)
![Screen Shot 2020-07-31 at 4 42 08 PM](https://user-images.githubusercontent.com/48343061/89088392-dc95c700-d34c-11ea-9ef0-bcd000ba50ea.png)

### 7. Feedback - Thank You
![Screen Shot 2020-07-16 at 6 19 26 PM](https://user-images.githubusercontent.com/48343061/87737844-e9cd8600-c790-11ea-8db4-f4240ef3a8c7.png)

### 8. Feedback - Other Suggestions
![Screen Shot 2020-07-16 at 6 34 40 PM](https://user-images.githubusercontent.com/48343061/87738806-1387ac80-c793-11ea-95cb-d5e012e8d231.png)

### 9. Feedback - Service No Longer Exists
![Screen Shot 2020-07-16 at 6 33 14 PM](https://user-images.githubusercontent.com/48343061/87738707-da4f3c80-c792-11ea-9a18-af6f4f190199.png)

### 10. Feedback - Contact Info (ALL)
![Screen Shot 2020-07-16 at 1 58 43 PM](https://user-images.githubusercontent.com/48343061/87738672-c6a3d600-c792-11ea-97fa-96aec43cb58f.png)

### 11. Feedback - Form
![Screen Shot 2020-07-16 at 8 22 32 PM](https://user-images.githubusercontent.com/48343061/87745236-39687d80-c7a2-11ea-852b-2af821ae8ac8.png)

### 12. Open External Link
![Screen Shot 2020-07-16 at 8 38 35 PM](https://user-images.githubusercontent.com/48343061/87746038-69b11b80-c7a4-11ea-828c-1c55a660518c.png)

### 13. Revised Onboarding 2
![Screen Shot 2020-07-16 at 8 46 16 PM](https://user-images.githubusercontent.com/48343061/87746460-7da94d00-c7a5-11ea-933a-9d3d0a075888.png)

**Comment by rasmus-storjohann-PG** [comment]
This story was used to help translators, no work to do on them, closing.
